devitocodes/devito

function_manager.py, jit_manager.py
This commit does an initial integration with pyMIC. I have already reviewed this, @mlange05 . Please take a look and merge.
=> Integration with pyMIC

AcousticWave2D.py, AcousticWave2D_codegen.py, benchmark.py, interfaces.py, operators.py, propagator.py, tests/test_adjointA.py
All four functions match up properly on benchmark
=> Reconciliation of Devito version of AcousticWave with the latest version complete

devito/cgen_wrapper.py, devito/function_manager.py, devito/jit_manager.py, devito/operators.py, devito/propagator.py, setup.cfg, tests/test_oi.py
Initial steps for roofline. Functions to get kernel arithmetic intensity.
=> Calculating overall kernel AI

.travis.yml, devito/function_manager.py, devito/jit_manager.py, devito/operators.py, devito/propagator.py
Generating code with openmp support. The build fails on osx because clang does not support openmp. I tried some workarounds but none of them worked. I also noticed that the code has not been vectorized by the toolchain compiling with gcc, but typing the command  by hand the code is vectorized. Any ideias about it?
=> Pragmas for paralelization and vectorization

devito/function_manager.py, devito/operators.py, devito/propagator.py, examples/AcousticWave2D.py, examples/fwi_operators.py, tests/test_cache_blocking.py
Inviting review/comments on this.
This branch builds on https://github.com/opesci/devito/pull/17 so it should only be accepted after that.
=> Cache blocking

devito/operators.py, examples/AcousticWave2D_codegen.py, tests/test_operator.py
Debug mode support for operators. Adding debug=True to the apply call will now execute the operator in python mode. Highly experimental. Tests welcome.
=> Debug mode

devito/__init__.py, devito/finite_difference.py, devito/interfaces.py, devito/operator.py, devito/propagator.py, examples/fwi_operators.py, examples/tti_operators.py, tests/test_diffusion.py, tests/test_oi.py, tests/test_symbolic_data.py
This merge facilitates the symbolic creation of stencil equations directly from our data objects in the FWI examples. This replaces the need to manually perform symbolic manipulation into the "indexed access" format expected by the Propagator, and allows us to remove a fair bit of pre-processing from the FWI operators. It also defines the different roles of the `Operator` and `Propagator` more clearly and introduces the first pieces of further automation to derive various other meta-parameters. The key contributions are:
* Additional derivative symbols provided by symbolic data objects, including the dimension-independent `laplace` operator and cross-derivatives. The symbolic derivatives now also honour `space_dim` and `time_dim` arguments set on the symbolic data objects to easily …
=> Automated symbolic substitution

.travis.yml, docs/deploy.sh
This fixes the auto deployment of the documentation.
=> Auto deployment of Sphinx documentation

devito/finite_difference.py
Fixes some warnings generated by the docstrings in finite_difference and displays function calls as inline code blocks
=> Documentation fix

devito/logger.py, docs/devito.rst, tests/test_diffusion.py
A basic logging infrastructure 
Example of use in test_diffusion. I think all prints and similar stuff should be moved to this
PERF_OK and PERF_WARN should be used to emit messages concerning performance (times, flop reductions etc)
Fixes #19
=> Logging infrastructure

devito/operator.py, devito/propagator.py, tests/test_instance.py, tests/test_numpy.py
Some initialization logic for the Propagator was part of the Operator code. 
This PR moves it down to the Propagator.
=> Moved initialization logic from Operator to Propagator

devito/function_manager.py, tests/test_value_params.py
Value parameters were added twice to function signature
=> Fixed bug introduced in #80

devito/compiler.py, devito/finite_difference.py, devito/function_manager.py, devito/interfaces.py, devito/iteration.py, devito/operator.py, devito/profiler.py, devito/propagator.py, examples/TTI_codegen.py, examples/containers.py, examples/fwi_operators.py, examples/tti_example.py, examples/tti_example2D.py, examples/tti_operators.py, setup.cfg, tests/test_adjointA.py, tests/test_cache_blocking.py, tests/test_diffusion.py, tests/test_gradient.py, tests/test_oi.py, tests/test_save.py
Enforcing 90 line length rule as @FabioLuporini suggested and updating existing files accordingly.
Close issue 83 and 64 after merging.
=> Enforcing 90 line length rule

devito/profiler.py, devito/propagator.py, tests/test_oi.py
An addition to PR#89, allows profiling under OpenMP settings.
=> Openmp profiling

devito/propagator.py
reduction clause needs to go onto each #pragma simd aligned  line otherwise vectorization is broken
=> Reduction clause onto the simd line.

devito/finite_difference.py, devito/interfaces.py, devito/profiler.py, examples/tti_benchmark.py, examples/tti_operators.py, tests/test_symbolic_data.py
Just a few extra finite-difference shortcuts used to have density in the operators.
=> few more FD shortcut

devito/propagator.py
Fairly non-controversial. Removing the redundant lines of code pointed out in https://github.com/opesci/devito/issues/121
=> Removing redundant concept of pre and post kernel steps

devito/operator.py
Some temporaries in CSE had the form
`float tempX = arr[t][x][y][z]`
This is fairly useless assuming the array is cached. This PR reverts this kind of temporaries.
=> CSE: Temporaries to array elements are reverted

requirements.txt
Making our version dependency on `numpy` explicit to address issue #96.
=> Adding explicit numpy requirement

examples/benchmark.py
Resulting plots have now more customisation and look cooler. Requires opescibench PR #3.
=> Adapting new `RooflinePlotter` API from opescibench in benchmarks

devito/operator.py, devito/propagator.py, tests/test_numpy.py, tests/test_propagator.py
This PR adds a test that exposes the bug related to setting the `space_dims` parameter in the Propagator. 
It also includes a fix for the bug.
=> Space dims fix

devito/operator.py, devito/propagator.py, devito/symbolics.py
This PR factorizes all functions that inspect and manipulate sympy expressions in a new module called ``symbolics.py``. These functions are also renamed by using the prefix ``dse_`` (devito symbolic engine). 
I'm planning to add more functionalities to the symbolic engine in the following weeks
=> Clean up prior introduction of symbolic engine

devito/__init__.py, devito/codeprinter.py, devito/interfaces.py, devito/logger.py, devito/memory.py, devito/operator.py, devito/propagator.py, devito/stencilkernel.py, devito/symbolics.py, devito/tools.py, examples/acoustic/Acoustic_codegen.py, examples/benchmark.py, tests/test_value_params.py
Memory allocation using malloc_aligned. Also implements first_touch.
=> Memory allocation in C

devito/function_manager.py, devito/memory.py, devito/profiler.py, devito/symbolics.py
Fixing a set of minor import sins, mainly to address issue #110.
=> Fix imports

.gitignore, .travis.yml, devito/__init__.py, devito/finite_difference.py, devito/memory.py, devito/operator.py, devito/propagator.py, devito/stencilkernel.py, devito/symbolics.py
This merge cleans up the travis build matrix to use the proper builtin Python images and test Python 3.3, as well 2.7. It also fixes the various compatibility issues with Python3.
=> Python3 compatibility and Travis housekeeping

devito/compiler.py, devito/dse/extended_sympy.py, devito/dse/graph.py, devito/dse/inspection.py, devito/dse/symbolics.py, devito/expression.py, devito/operator.py, devito/propagator.py, examples/tti/tti_operators.py, tests/test_rewriter.py
You'll see lots of edits in this PR, but no worries: it's mostly just moving stuff around and dropping useless functionalities.
Now the DSE has its own subdirectory ``dse``, and its components are split over multiple files.
The Bhaskara polynomials approximation is now applicable by the DSE; as such, it's been removed from TTI.
A few more things:
- Now we always print the compilation time
- The ``factorized`` attribute has finally been dropped 
- Added basic infrastructure for creating ``temporaries graphs``, which will be used in subsequent versions of the DSE
All new functionalities are properly tested
I'm happy to rebase if #161 lands first
=> DSE restructuring and improvements

devito/dse/extended_sympy.py, devito/dse/inspection.py, devito/dse/manipulation.py, devito/dse/symbolics.py, devito/function_manager.py, devito/operator.py, devito/propagator.py, examples/benchmark.py
A number of improvements of various nature
Performance-wise, the most important thing is the introduction of the MACROs to prevent denormal numbers at run-time. This greatly improve performance (I might show some numbers in the next few days)
This must go after #167
=> Various DSE improvements

tests/test_gradient.py
Rewrote the gradient test.
- passes in bot h `float32` and `float64`
- removed xfail
=> gradient test fixed.

devito/dimension.py, devito/dle/manipulation.py, devito/dle/transformer.py, devito/logger.py, devito/nodes.py, devito/stencilkernel.py, devito/visitors.py, tests/test_dle.py, tests/test_visitors.py
This PR introduces cache blocking in the DLE and a number of other niceties.
The infrastructure to make cache blocking usable through the StencilKernel interface is also introduced.
Several tests are included. All of the cache blocking tests are passing; I still have to tweak a few other failing tests, but this should be doable without too much pain tomorrow, so hopefully Travis will be green soon.
=> DLE cache blocking

devito/dle/inspection.py, devito/dle/transformer.py, devito/dse/symbolics.py, devito/nodes.py, devito/stencilkernel.py, devito/tools.py, devito/visitors.py, examples/benchmark.py, requirements.txt
This PR introduces:
- a new transformation step in the Devito Loop Engine to emit nontemporal stores
- a simple auto-tuning system through ``StencilKernel`` that doesn't depend on the old AT system
- extensions to benchmark.py
This PR should go in **after** #183
=> Devito3.0 further improvements

devito/codeprinter.py, devito/dimension.py, devito/dle/transformer.py, devito/dse/__init__.py, devito/dse/extended_sympy.py, devito/dse/graph.py, devito/dse/inspection.py, devito/dse/symbolics.py, devito/interfaces.py, devito/logger.py, devito/nodes.py, devito/propagator.py, devito/stencilkernel.py, devito/tools.py, devito/visitors.py, examples/benchmark.py, tests/test_dle.py, tests/test_oi.py
This PR brings Devito3.0 steps closer to feature completeness.
Support for running several Acoustic operators is introduced. This mainly consists of properly dealing with the DSE-produced temporaries during the various DLE passes as well as for code generation (eg, inferring the right data types). However, to run the Acoustic operators, we'll need #187 .
Performance profiling has been extended, improved, and fixed where necessary (fixes were minor).
On top of all this, a number of improvements of various nature have been introduced.
=> Devito3.0: more and more features

examples/containers.py
Small fix of the computational time-step for anisotropy.
=> fix dt scale for tti

.travis.yml
=> HAHAHAHAHAHAHAHAHA freeeddooooooommmm

devito/interfaces.py
Skip unnecessary JIT calls since our NUMA support isn't complete anyway.
=> Add flag to make first touch optional

devito/dle/transformer.py, devito/dse/graph.py, devito/dse/inspection.py, devito/dse/symbolics.py, devito/interfaces.py, devito/nodes.py, devito/stencilkernel.py, devito/tools.py, devito/visitors.py, examples/benchmark.py, examples/tti/TTI_codegen.py, tests/test_dle.py, tests/test_visitors.py
This PR ships everything needed to run TTI with full fledged DSE and DLE in Devito3.0
This however is not ready for merge yet. In particular, what's missing:
- Minor bug fixes for non square/cubic grids [EDIT: Fixed!] 
- Tests !! 
I open the PR in case people wanna try it or simply find the time to go through the code and write some tests.
I appreciate bug reports, but please bear in mind this is WIP
=> Devito3 and TTI

devito/compiler.py
OSX compatibility of `-march=native` with the extra `-mno-avx`.
=> fix gnu flag

setup.py
Added missing dependencies to the `setup.py`
=> misssing dependency

devito/compiler.py, devito/finite_difference.py, devito/interfaces.py, devito/operator.py, devito/stencilkernel.py, devito/visitors.py, examples/acoustic/Acoustic_codegen.py, examples/acoustic/acoustic_example.py, examples/acoustic/fwi_operators.py, examples/seismic/model.py, examples/tti/tti_operators.py, tests/test_adjointA.py, tests/test_adjointJ.py, tests/test_cache_blocking.py, tests/test_gradient.py, tests/test_save.py, tests/test_timestepping.py
Still a lot to do to migrate everything to 3.0 but 
1- Time axis flag is in (thanks to @mlange05 )
2 - Adjoint test passes with everything using StencilKernel
So I am creating the PR for the sake of it and also because there is a major crash in travis after the first test, and I have no idea where it comes from (runs fine on my machine).
EDIT:
Segfault seems fixed. StencilKernel throws error (dse I think) with
`save=True` in forward
Born
=> Adjoint3 0

devito/dse/graph.py, examples/acoustic/acoustic_example.py, tests/test_adjointJ.py, tests/test_gradient.py, tests/test_save.py
A small set of fixes that circumvent DSE failures some corner cases laid bare by the current seismic operators. These are meant as an intermediate steps to fix issue #218 while @FabioLuporini finishes the full engine re-write.
=> DSE stopgap fixes

devito/dse/manipulation.py
fixes #268 
@mloubout pls confirm this
=> DSE: Do not rebuild unless really needed

examples/seismic/acoustic/gradient_example.py, examples/seismic/tti/tti_example3D.py
Removed debug prints
`dse` to advanced as default in TTI
=> leftover fixes

requirements.txt, setup.py
This PR is not a solution but a hack so that people don't have problem installing devito while we figure out how to handle sympy 1.1
Only change the setup to force 1.0
=> Force sympy 1.0

devito/core/autotuning.py, devito/dle/backends/advanced.py, devito/dle/backends/basic.py, devito/dle/backends/common.py, devito/dle/blocking_utils.py, devito/dle/transformer.py, devito/dse/aliases.py, devito/dse/symbolics.py, devito/nodes.py, devito/operator.py, devito/parameters.py, devito/visitors.py, examples/benchmark.py, examples/seismic/tti/tti_example3D.py, tests/test_dle.py, tests/test_dse.py, tests/test_operator.py
Final tweaks making the Cross-Stencil Redundancies Elimination algorithm fully operative, but still not automatically enabled yet. For that, still need one more set of changes.
=> CSRE finalization

devito/dle/backends/advanced.py, devito/dle/backends/common.py, devito/dle/manipulation.py, devito/dle/transformer.py, devito/dse/aliases.py, devito/dse/backends/advanced.py, devito/dse/backends/basic.py, devito/dse/backends/common.py, devito/dse/backends/speculative.py, devito/dse/clusterizer.py, devito/dse/graph.py, devito/dse/inspection.py, devito/dse/manipulation.py, devito/dse/queries.py, devito/interfaces.py, devito/nodes.py, devito/operator.py, devito/stencil.py, examples/benchmark.py, tests/conftest.py, tests/test_dle.py, tests/test_dse.py
This PR adds some features on top of #295
=> CSRE enhancements

devito/dle/backends/advanced.py, devito/dle/blocking_utils.py, devito/dse/backends/advanced.py, devito/dse/clusterizer.py, devito/dse/manipulation.py, devito/nodes.py, devito/operator.py, examples/benchmark.py, tests/conftest.py, tests/test_operator.py
- A further DLE pass to minimise the negative impact of remainder loops when using 3D blocking
- Update benchmark.py  [depends on https://github.com/opesci/opescibench/pull/5]
- Fix a few issues, see below
- more tests
fixes #299 #304
=> Misc improvements and fixes

devito/arguments.py, devito/operator.py, devito/yask/interfaces.py, devito/yask/kernel.py, devito/yask/operator.py, devito/yask/utils.py, tests/test_yask.py
This PR brings us to a state in which we can automatically execute through Devito+YASK the operator
```
u[t+1,x,y,z] = u[t,x,y,z] + 1
```
on a ``[16,16,16]`` grid
Also:
- Tests fixes
- Refactoring and improvements
=> Yask integration phase4

devito/dse/graph.py
=> dse: Fix time invariance calculation

devito/logger.py, devito/yask/interfaces.py, devito/yask/kernel.py, devito/yask/operator.py, devito/yask/utils.py, tests/test_yask.py
Now support halo, so we can use offsets in our equations.
Probably I'll add another test tomorrow.
EDIT: Done.
=> Yask integration phase5

devito/dse/aliases.py, devito/dse/backends/advanced.py, devito/dse/manipulation.py, devito/interfaces.py, tests/test_dse.py, tests/test_symbol_caching.py
We should reopen #225 
@navjotk : you're gonna love this
EDIT: added potential fix
=> Yet another symbolic cache bug, plus potential fix

devito/dse/clusterizer.py, devito/dse/graph.py, tests/test_operator.py
=> Fix loop scheduling bc

devito/arguments.py, devito/base.py, devito/core/__init__.py, devito/dle/backends/advanced.py, devito/dle/backends/basic.py, devito/foreign/__init__.py, devito/interfaces.py, devito/nodes.py, devito/operator.py, devito/pointdata.py, devito/yask/__init__.py, devito/yask/interfaces.py, devito/yask/operator.py, examples/cfd/example_diffusion.py, tests/conftest.py, tests/test_autotuner.py, tests/test_dle.py, tests/test_operator.py, tests/test_yask.py
=> ConstantData

devito/core/autotuning.py, devito/dse/aliases.py, devito/dse/backends/advanced.py, devito/dse/backends/common.py, devito/dse/manipulation.py, devito/nodes.py, tests/test_dse.py
A few minor fixes/improvements, one per commit
=> small fixes and improvements

devito/arguments.py, devito/dimension.py, devito/dle/backends/advanced.py, devito/nodes.py, devito/operator.py, devito/profiling.py, tests/conftest.py, tests/test_adjointA.py, tests/test_operator.py
=> Revert "Separate the case where Dimensions have a known size into its own class"

devito/core/autotuning.py
=> hotfix autotuning

devito/cgen_utils.py, devito/dse/extended_sympy.py, devito/operator.py, devito/yask/__init__.py, devito/yask/operator.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/test_yask.py
This will have to be rebased and should go *after* #352
=> yask: Fixes to make the acoustic wave equation test take off

devito/arguments.py, devito/dimension.py, devito/dle/backends/advanced.py, devito/nodes.py, devito/operator.py, devito/profiling.py, tests/conftest.py, tests/test_adjointA.py, tests/test_dimension.py, tests/test_operator.py
=> Bring back FixedDimension

devito/dse/aliases.py, devito/profiling.py, tests/test_dse.py
=> dse: Fix aliases detection

devito/__init__.py, devito/cgen_utils.py, devito/dse/aliases.py, devito/dse/extended_sympy.py, devito/dse/graph.py, devito/dse/manipulation.py, devito/dse/queries.py, devito/interfaces.py, devito/operator.py, devito/pointdata.py, devito/stencil.py, environment.yml, examples/seismic/acoustic/operators.py, examples/seismic/tti/operators.py, requirements.txt, setup.py, tests/conftest.py, tests/test_autotuner.py, tests/test_derivatives.py, tests/test_dle.py, tests/test_dse.py, tests/test_finite_difference.py, tests/test_operator.py, tests/test_save.py, tests/test_timestepping.py, tests/test_visitors.py, tests/test_yask.py
This merge adds the necessary compatibility changes to make Devito work with the new `sympy-1.1` and updates the dependencies everywhere.
**Note: This is not backwards compatible with `sympy-1.0` and all environments have to be upgraded!**
=> Sympy-1.1 update

devito/cgen_utils.py, devito/dle/manipulation.py, devito/dse/backends/advanced.py, devito/dse/extended_sympy.py, devito/yask/__init__.py, devito/yask/operator.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/test_yask.py
These make the tests in ``test_yask.py`` pass when running on top of ~YASK:v2_alpha:9b87b4b21~ YASK:v2_alpha:ac9f784bf7d , which changed quite a few things w.r.t. to the ``develop`` branch
It also ships the required tweaks after the sympy1.1 switch
=> Misc YASK updates

devito/dse/backends/advanced.py, devito/dse/manipulation.py, devito/tools.py, devito/types.py, devito/yask/__init__.py, devito/yask/function.py, devito/yask/operator.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/conftest.py, tests/test_dse.py, tests/test_yask.py
- Support for temporary grids
- tests for reverse loops, temporary grids, adjoint operator
- Misc improvements all over the yask backend
- Small fixes to some DSE routines
=> yask: Support for acoustic adjoint operator and misc

devito/function.py, devito/types.py, devito/yask/__init__.py, devito/yask/function.py, devito/yask/operator.py, devito/yask/wrappers.py, tests/test_yask.py
plus a few minor tweaks/additions
=> yask: Support for Constant objects

devito/grid.py
=> Grid: Add string representation for use in notebooks

devito/dse/backends/advanced.py, devito/dse/backends/basic.py, devito/dse/backends/speculative.py, devito/dse/manipulation.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/dfg/graph.py, tests/test_dse.py
@mloubout : this **should** fix your issue in ``time-free-sparse``. Pls let me know
=> Fix and improve TemporariesGraph

.travis.yml, setup.cfg, tests/test_checkpointing.py
This PR primarily adds a test for correct index alignment in `test_checkpointing.py`. 
It also: 
- ~adds a check for missing argument values~
- ~adds a test for the above~
=> Test index alignment for checkpointing

.travis.yml, devito/types.py, devito/yask/__init__.py, devito/yask/function.py, devito/yask/operator.py, devito/yask/wrappers.py, examples/seismic/benchmark.py, tests/test_yask.py
- Allow reusing the same Operator w/ different input data (added test)
- Make it possible to drive the YASK autotuning system
- Handle rationals and powers when constructing operators (thanks Tim)
- Switch Travis from ``v2_alpha`` to ``develop``
fixes #418 #419
=> YASK fixes

examples/seismic/tutorials/01_modelling.ipynb, examples/seismic/tutorials/02_rtm.ipynb
let's see how Travis reacts with this...
=> notebook testing: NBVAL_IGNORE_OUTPUT -> NBVAL_SKIP

.travis.yml, devito/tools.py, examples/checkpointing/checkpointing_example.py, setup.cfg, tests/test_checkpointing.py
Adds a decorator to temporarily change log levels and uses it to silence checkpointing output. Also updates `flake8` rules.
=> Silence checkpointing

tests/test_autotuner.py
Fixes issue #438 
Requires #429
=> Fix logging

tests/test_checkpointing.py
Adds three new tests that cover the three basic sweep types one might
segment, ie. execute in multiple operator invocations. Each compares
against a reference solution and against a full single-invocation sweep.
The three types are:
* One-sided, first order in time; stencil(t)=(1, 0)
* One-sided, second order in time; stencil(t)=(2, 0)
* Two-sided, second order in space; stencil(x)=(1, 1)
This largely demonstrates the current conventions used to prescribe the
segmented dimension limits and will inform discussions on #449.
=> Checkpointing: Adding tests to demonstrate segmented dimension sweeps

devito/dse/backends/common.py, examples/seismic/benchmark.py
=> Benchmark.py tweaks

devito/data.py, devito/function.py, devito/yask/data.py, devito/yask/function.py, devito/yask/wrappers.py, examples/seismic/benchmark.py, examples/seismic/tti/wavesolver.py, tests/test_data.py, tests/test_yask.py
This builds the foundation for the domain allocation switch
I think commit messages and edits are quite self-explanatory.
Having simplified ``yask.Data`` also makes me extremely happy
=> domain, halo, padding

devito/function.py, tests/test_save.py
Test_save hotfix for @FabioLuporini 
- save setup properly in `TimeFunction`
- No `initializer`
This PR only fix the test, not the `initilizer` overall removall
=> test save fix

devito/cgen_utils.py, devito/dimension.py, devito/function.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/equations/equation.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/operator.py, devito/profiling.py, devito/symbolics/extended_sympy.py, devito/tools.py, environment.yml, requirements.txt, tests/test_dimension.py, tests/test_ir.py, tests/test_operator.py
Tests in ``test_dimension.py`` show how time subsampling can be triggered. I'm not claiming this is incredibly robust, but at least it works in basic cases. Also, the design seems OK to me, so this should be at least a good start.
@tjb900 this also includes the constant argument fix (with a test) and your subsampling test with shifted dimension
EDIT: introduces a new (tiny) package dependency: ``frozendict``
=> Embryonic support for subsampling

devito/symbolics/extended_sympy.py, tests/test_dimension.py
Small fix on the new `IntDiv`
- set as `is_Atom` to avoid any evalutaion or `.args` access and print as is in the C code
- Added a test for `ConditionalDimension` used as stencil value instead of index only
- Fix the `assert` in test dimension that were not checking anything.
Should fix #490
=> IntDiv hotfix

devito/function.py, devito/operator.py, devito/yask/operator.py, examples/checkpointing/checkpointing_example.py, examples/seismic/acoustic/acoustic_example.py, examples/seismic/acoustic/gradient_example.py, examples/seismic/acoustic/wavesolver.py, examples/seismic/model.py, examples/seismic/tti/operators.py, examples/seismic/tti/wavesolver.py, tests/test_adjointA.py, tests/test_adjointJ.py, tests/test_checkpointing.py, tests/test_gradient.py, tests/test_interpolation.py, tests/test_operator.py, tests/test_tti.py
This should fix Issue #485 by switching the oder of argument processing.
~`Test_checkpoint` is broken I have no idea why and gonna take me a bi to fix navigating through its architecture~ Fixed
=> switch input/default order

.travis.yml, devito/dimension.py, examples/misc/linalg.py
Some trivial examples showing how to express basic linear algebra operations
=> Non-FD examples

devito/dimension.py, devito/dse/backends/advanced.py, devito/dse/backends/basic.py, devito/dse/backends/common.py, devito/dse/backends/speculative.py, devito/dse/manipulation.py, devito/dse/transformer.py, devito/function.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/equations/equation.py, devito/ir/iet/analysis.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/ir/support/basic.py, devito/ir/support/space.py, devito/ir/support/stencil.py, devito/ir/support/utils.py, devito/symbolics/manipulation.py, devito/tools.py, devito/yask/operator.py, tests/test_dimension.py, tests/test_dle.py, tests/test_dse.py, tests/test_operator.py, tests/test_yask.py
This PR does a minor cleanup and, most importantly, fixes a number of issues associated with SubDimensions
fixes #503
fixes #508
fixes #513
fixes #521 
Tests for each of these issues are shipped
@mloubout @tjb900 please double check that the issues are actually gone with this PR
=> Stronger SubDimensions

devito/dimension.py, devito/function.py, devito/operator.py, devito/tools.py, devito/yask/function.py
I think this PR makes understanding and changing the arguments processing **way** easier than in current master
=> better arguments processing

devito/cgen_utils.py, devito/core/autotuning.py, devito/dle/backends/advanced.py, devito/dle/backends/common.py, devito/dle/backends/utils.py, devito/dse/backends/advanced.py, devito/dse/backends/basic.py, devito/dse/backends/speculative.py, devito/dse/manipulation.py, devito/dse/transformer.py, devito/function.py, devito/ir/clusters/cluster.py, devito/ir/equations/equation.py, devito/ir/iet/analysis.py, devito/ir/iet/nodes.py, devito/ir/iet/properties.py, devito/ir/iet/scheduler.py, devito/operator.py, devito/types.py, devito/yask/utils.py, tests/test_dle.py, tests/test_ir.py, tests/test_visitors.py
This PR generates ``#pragma atomic`` over associative and commutative increments so that loops with local reductions can be safely parallelised. 
For seismic, the typical use case is injection loops
EDIT: this is based on #528 ...
=> Parallel loops with local reductions

devito/symbolics/extended_sympy.py, tests/test_dimension.py
Properly track ``args`` so that ``free_symbols`` works
fixes #537
=> Fix custom expression objects

devito/core/__init__.py, devito/dle/__init__.py, devito/dle/backends/__init__.py, devito/dle/backends/advanced.py, devito/dle/backends/common.py, devito/dle/backends/parallelizer.py, devito/dle/backends/utils.py, devito/dle/transformer.py, devito/ir/support/utils.py, devito/yask/__init__.py, devito/yask/dle.py, devito/yask/operator.py, tests/test_autotuner.py
Gonna be useful soon. In essence, in the YASK backend we can now specialize individual DLE passes or provide entirely new Rewriters.
Also:
fixes #540
=> Give YASK more freedom to drive the DLE

devito/ir/clusters/algorithms.py, tests/conftest.py, tests/test_dimension.py
Fixes this error, encountered in some cases when using `ConditionalDimension`s:
```
ValueError: Unsupported Cluster [mixed integer arithmetic ?]
```
=> handle case where ConditionalDimension has no action on one branch

devito/ir/equations/equation.py, devito/ir/support/stencil.py, devito/ir/support/utils.py, tests/test_dimension.py
=> Better conddims

devito/__init__.py, devito/data.py, devito/dle/backends/advanced.py, devito/dle/backends/parallelizer.py, devito/dse/backends/basic.py, devito/function.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/parameters.py, devito/symbolics/extended_sympy.py, devito/tools.py, devito/yask/__init__.py, devito/yask/dle.py, devito/yask/function.py, devito/yask/operator.py, devito/yask/types.py, devito/yask/utils.py, devito/yask/wrappers.py, examples/seismic/benchmark.py, tests/test_yask.py
Add:
- support for libnuma to place data on a certain socket (see additions to `data.py` for more info). Nothing changes in user code if not interested in this feature.
- atomics in the YASK backend
=> libnuma support and atomics in YASK

devito/ir/equations/algorithms.py, devito/ir/equations/equation.py, devito/symbolics/inspection.py, devito/tools.py, tests/test_ir.py, tests/test_tools.py
@tjb900 I'm sorry you've been hit by the bugs in #559 -- these are due to archaic code that I should have changed a long time ago. Anyway, this PR hopefully fixes all of the issues that you pointed out, and also improves the code quality in general.
Hopefully this will make Travis happy. Should you encounter analogous issues in the future, please append the failing tests either here:
``test_ir.py::test_dimension_sort``
or
``test_tools.py::test_toposort``
I also took the opportunity to relocate some code
fixes #559
=> Fix and improve dimension_sort

devito/dimension.py, devito/function.py, devito/ir/clusters/algorithms.py, devito/ir/iet/scheduler.py, tests/test_derivatives.py, tests/test_dimension.py, tests/test_operator.py
Adds support fr spatial conditionals
- extends arguments checks as in the spatial case, the size needs to be passed as an argument
- remove unnecessary modulo for non stepping dimension (breaks compilation for multi conditionals)
- test
fixes #563
=> Spatial conditionals

devito/dimension.py, tests/test_dimension.py, tests/test_symbol_caching.py
Critical fix for caching of Dimension object
The test that I added would fail w/o this fix. Quite embarrassing.
=> Fix Dimension caching

devito/__init__.py, devito/compiler.py, devito/logger.py, devito/tools/__init__.py, devito/tools/algorithms.py, devito/tools/data_structures.py, devito/tools/memoization.py, devito/tools/mixins.py, devito/tools/utils.py, devito/tools/validators.py, devito/tools/visitors.py, devito/utilities/__init__.py, devito/utilities/mixins.py
Besides improving the organisation of the various support functions and classes, this PR removes an annoying dependence between tools and ``configuration``.
=> Split tools.py into separate files under tools/

devito/data.py
Without this, we were passing wacky addresses and sizes to numa_free - which blindly unmaps virtual memory areas, or does nothing, depending on the phase of the moon.
=> ensure correct types are passed to numa_free

environment.yml, requirements.txt
=> Forcing numpy1.14

devito/parameters.py
Fix cache hit issue on compiled code for modified logging level or first touch that do not impact the generated code.
fixes #625
=> Logging issue fix for cached coed

docs/tutorials.rst
List of Tutos update for the website and documentation.
=> tutos list update

devito/function.py, devito/types.py, requirements.txt
Update custom `Indexed` and `.dot` deprecation for symyp 1.2 
fixes #615
=> compat with sympy 1.2 and requirements

devito/core/operator.py, devito/dle/backends/advanced.py, devito/dle/backends/basic.py, devito/dle/blocking_utils.py, devito/function.py, devito/grid.py, devito/ir/iet/analysis.py, devito/ir/iet/nodes.py, devito/ir/iet/properties.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/ir/stree/algorithms.py, devito/ir/stree/tree.py, devito/ir/support/basic.py, devito/ir/support/space.py, devito/mpi/__init__.py, devito/mpi/distributed.py, devito/mpi/halo_scheme.py, devito/mpi/routines.py, devito/mpi/utils.py, devito/operator.py, devito/tools/utils.py, devito/tools/visitors.py, tests/conftest.py, tests/test_mpi.py, tests/test_visitors.py
This PR enhances C-level MPI . We now support a larger range of Operators (see new tests). This was achieved through non-trivial coordination of several compilation passes (schedule trees, IET analysis, DLE).
A number of minor fixes everywhere are also shipped.
=> Stronger MPI

devito/ir/clusters/algorithms.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/yask/data.py, devito/yask/function.py, devito/yask/operator.py, devito/yask/transformer.py, devito/yask/wrappers.py, tests/test_yask.py
sits on top of #629 , hence the big diff
REMINDER: A YASK fork update is necessary
=> YASK: time subsampling

devito/function.py, devito/types.py, devito/yask/data.py, devito/yask/function.py, examples/seismic/source.py, tests/test_pickle.py
Pickling extensions introduced:
* Unconditionally dump Function ``data`` 
* Fix pickling for SparseFunction objects
Also, some polishing to docstrings and minor improvements in the Function setup
=> Extend pickling support

devito/ir/iet/analysis.py, devito/ir/support/basic.py, devito/symbolics/manipulation.py, devito/types.py
As suggested by @FabioLuporini
=> More performance improvements

devito/types.py, tests/test_dimension.py
Small PR to fix `indexify` for Sub/Conditional dimensions
Added two test for FD in combination with Sub/Conditional dimensions.
=> Indexify-hotfix

examples/cfd/03_diffusion.ipynb
fix typo in 03_diffusion.ipynb
=> fix typo in 03_diffusion.ipynb

environment.yml
Fix versions of dask and distributed to get consistent behaviour
=> Fix dask and distributed versions

examples/cfd/01_convection_revisited.ipynb, examples/cfd/02_convection_nonlinear.ipynb, examples/cfd/03_diffusion.ipynb, examples/cfd/04_burgers.ipynb, examples/cfd/05_laplace.ipynb
Nothing serious, just familiarising with some aspects of rebasing.
=> Fixed typos for cfd

devito/function.py, devito/symbolics/extended_sympy.py, devito/types.py
No tests, but hopefully these are pretty obvious changes.
=> Some pickling fixes

devito/function.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/clusters/graph.py, devito/ir/equations/equation.py, devito/ir/support/utils.py, devito/profiling.py, devito/symbolics/manipulation.py, devito/symbolics/search.py, tests/test_dse.py, tests/test_interpolation.py
fixes + bunch of tests
I'm also dropping the now useless `group_expressions` routine, which might even improve the compilation speed. Like this.
=> Fix Static Single Assignment (SSA) translation

examples/cfd/tools.py
=> Fix for `plot_field` function failing on non-square grids #666

README.md, docker/entrypoint.sh
Added environment variables inside the docker entry point script to make it easy to get a shell with devito using docker. 
Added instructions in README to get such a shell
=> Docker: Add env variables inside Docker environment, and update README

tests/conftest.py, tests/test_derivatives.py, tests/test_interpolation.py
Small rewrite of conftest and test to avoid new errors with latest pytest
=> Pytest fix

devito/yask/transformer.py
This must be accompanied by an update of https://github.com/opesci/yask.git from https://github.com/intel/yask.git. Otherwise, the code will fail.
=> Changes required to upgrade to YASK 2.15.10.

examples/seismic/tutorials/01_modelling.ipynb
Small typos while going through modelling tutorial
=> Typos for 01_modelling.ipynb tutorial

docs/source/download.rst
Installation page was not well redirected last time fixed
=> Installation page updated as should

devito/yask/wrappers.py, tests/test_yask.py
Small changes. Main one is to turn on checking in YASK when in develop-mode.
=> Yask tweaks

devito/core/operator.py, devito/data/meta.py, devito/mpi/distributed.py, devito/mpi/routines.py, devito/types/dense.py, devito/types/grid.py, tests/test_mpi.py, tests/test_pickle.py
Better halo exchange routines -- in terms of both implementation in Devito and  quality of the generated code
~depends on #748 , so the diff looks bigger than it actually is~
Note that the branch name is misleading so ignore it
=> MPI codegen improvements

tests/test_constant.py
Update incorrect headers in `test_constant.py`.
=> Fix incorrect headers.

.travis.yml, devito/__init__.py, devito/cgen_utils.py, devito/compiler.py, devito/data/meta.py, devito/dle/blocking_utils.py, devito/dle/rewriters.py, devito/ir/iet/analysis.py, devito/ir/iet/efunc.py, devito/ir/iet/nodes.py, devito/ir/iet/properties.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/mpi/distributed.py, devito/mpi/halo_scheme.py, devito/mpi/routines.py, devito/operator.py, devito/symbolics/extended_sympy.py, devito/tools/abc.py, devito/tools/data_structures.py, devito/types/basic.py, devito/types/sparse.py, tests/conftest.py, tests/test_mpi.py
Not ready for review. 
I'm opening it only to trigger `pipelines`. 
The huge diff is mainly due to  #762
=> MPI: computation/communication overlap

CONTRIBUTING.md, devito/__init__.py, devito/dle/rewriters.py, devito/mpi/routines.py, devito/operator.py, devito/symbolics/extended_sympy.py, devito/types/basic.py, tests/test_dle.py, tests/test_mpi.py
The newly introduced ``overlap2`` mode only (yet drastically) improves the quality of the generated code over the ``overlap`` mode.
Performance should be in the same ballpark numbers, though as you know MPI experimentation hasn't begun yet.
=> MPI: Introduce overlap2 mode

devito/builtins.py, devito/mpi/distributed.py, examples/seismic/model.py
=> Fix TTI setup when using MPI

devito/symbolics/extended_sympy.py, devito/symbolics/queries.py, devito/types/basic.py, devito/types/constant.py, devito/types/dimension.py, tests/test_dimension.py, tests/test_pickle.py, tests/test_symbol_caching.py
- Symbol and Scalar pickling
- ConditionalDimension pickling
- SubDimension pickling
- ConditionalDimension usage with symbolic ``factor``
all equipped with tests
=> fix bunch of minor bugs

devito/yask/data.py, devito/yask/wrappers.py
Must land with https://github.com/opesci/yask/pull/9
=> Yask update

examples/cfd/example_diffusion.py, examples/cfd/tools.py, examples/checkpointing/checkpoint.py, examples/seismic/acoustic/operators.py, examples/seismic/acoustic/wavesolver.py, examples/seismic/elastic/operators.py, examples/seismic/elastic/wavesolver.py, examples/seismic/model.py, examples/seismic/plotting.py, examples/seismic/tti/operators.py, examples/seismic/tti/wavesolver.py, tests/test_derivatives.py
Numpy-doc-ization leftovers related to Issue #753.
Work under progress.
Left in purpose blanks to do them in chunks later
Questions: Expression **Symbol to** is widely used in 
the examples/*. How do we handle that? I mean should that be kept?
=> Numpy-doc examples/* and  tests/test_derivatives.py 

examples/cfd/tools.py
Adding xmin/ymin/zmin functionality
=> plot_field(...) enhancements

examples/mpi/overview.ipynb
Testing fix for MPI overview notebook to pass the tests...
=> notebook: nbval fix

examples/mpi/overview.ipynb
Try to fix random failure of mpi notebook
=> mpi: block and force grouping of output in notebook

devito/ops/node_factory.py, devito/ops/operator.py, devito/ops/transformer.py, devito/ops/types.py, devito/ops/utils.py, devito/symbolics/printer.py, tests/test_ops.py
supersedes #876.
Uses the new API to translate expressions and generates callables for OPS kernels
@FabioLuporini
=> OPS translation using new API and OPS Kernel generation

devito/ir/iet/utils.py, devito/ops/operator.py, devito/ops/utils.py, devito/symbolics/extended_sympy.py
This commit is including the ops_partition("") call into code generated by Devito using OPS backend.
The class Literal was created in the codebase.
=> Including ops_partition("") call

.travis.yml, azure-pipelines.py, devito/__init__.py, devito/builtins.py, devito/dle/rewriters.py, devito/ir/iet/analysis.py, devito/ir/iet/nodes.py, devito/ir/iet/properties.py, devito/ir/stree/algorithms.py, devito/mpi/halo_scheme.py, devito/mpi/routines.py, devito/types/dense.py, devito/types/sparse.py, examples/seismic/tutorials/05_staggered_acoustic.ipynb, examples/seismic/tutorials/06_elastic.ipynb, tests/test_derivatives.py, tests/test_mpi.py, tests/test_operator.py
Fix:
* MPI and staggered grids
* MPI and non perfect loop nests:
```
for x  # *Must not* be OpenMP-parallelized
for y
...
haloupdate()  # *Must not* go before `x`
for y
...
```
* MPI and naming of halo exchange routines (was mistakenly reusing the same name for different routines)
Also:
* Restrict some MPI tests to pipelines
=> more and more mpi fixes

.travis.yml, devito/dle/rewriters.py, devito/logger.py, devito/mpi/routines.py, tests/test_mpi.py
Reuse MPI halo exchange routines for multiple Functions/halo-exchanges whenever possible
=> Generate less code with MPI

.travis.yml, azure-pipelines.py, examples/seismic/viscoelastic/operators.py
Fix some silly python mistakes.
=> Viscoelastic example python corrections

devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/support/basic.py, devito/ir/support/space.py, tests/test_operator.py
have a look at the new test to understand what this patch fixes
=> Fix loop scheduling in presence of free Dimensions 

devito/core/autotuning.py, tests/test_autotuner.py
trivial patch for a stupid bug
=> Fix autotuning (tiny time loop was causing OOB accesses)

.travis.yml, azure-pipelines.py, devito/compiler.py, examples/seismic/model.py, tests/test_dse.py, tests/test_mpi.py
Switch the damp initialization from numpy to an operator. I think there is some slight value difference with previous implementation I am tracking down but this is a lot cleaner and works with mpi/.... and avoid the allocation of an extra massive array in 3D.
=> Model cleanup

examples/seismic/model.py, examples/seismic/viscoelastic/operators.py, examples/seismic/viscoelastic/viscoelastic_example.py
Fix a typo in the 2d viscoelastic benchmark equations. Update the preset models and viscoelastic_example.py accordingly.
=> 2D Visco benchmark fix

benchmarks/user/benchmark.py, devito/operator.py, devito/profiling.py, examples/seismic/model.py, examples/seismic/tutorials/07_DRP_schemes.ipynb, examples/seismic/tutorials/09_viscoelastic.ipynb
also drop switchconfig from examples
=> Add FD-GPoints/s metric to Operator output

devito/ir/stree/algorithms.py, tests/test_dimension.py
=> Fix scheduling of ConditionalDimension-ed equations

devito/ir/clusters/algorithms.py, devito/ir/support/basic.py, examples/checkpointing/checkpoint.py, tests/test_operator.py
=> Fix handling of mixed anti- and output-dependences during clustering

devito/ops/compiler.py, devito/ops/operator.py
Moving forward OPS compiler.
Since PR [886](https://github.com/opesci/devito/pull/886) has created the OPS Compiler, in this PR the code is being compiled for NVIDIA GPUs.
=> Created and using compiler to CUDA architecture

devito/ops/compiler.py, devito/ops/operator.py
This PR fixes the case in which there isn't affine trees to be converted
into OPS.
There are some fixings on ops/compiler as well.
=> ops: fixing specializing_iet

devito/data/allocators.py, tests/test_data.py, tests/test_docstrings.py
Add a new type of allocator backed by an externally allocated numpy array
@btrb
=> Numpy allocator

environment.yml, requirements-optional.txt, requirements.txt
I'm sure we're all happy to see it go :)
=> Remove PyZFP from environment.yml and requirements.txt, move to optional

devito/finite_differences/coefficients.py, tests/test_symbolic_coefficients.py
Small PR to allow custom FD weights to be set using Devito Functions. Relevant test included.
=> Functions as fd weights

benchmarks/user/benchmark.py
To add some plotting fixes for benchmark.py
=> Add mpi_mode in json

devito/dse/rewriters.py, tests/test_dse.py
@mloubout : hopefully this fixes the explosion in number of hoisted time invariants 
can you check again with the use case you provided me with long time ago?
=> dse: Fix handling of nested aliases

devito/finite_differences/tools.py
@fablup not the highest fan of only up to order 6 shortcuts but don't think anyone would use higher than that indeed so should give you a decent speedup for codegen.
=> Speedup shortcut generation

devito/data/data.py, tests/test_data.py
This PR addresses issues #1006 and #1007.
=> Misc data fixes

devito/dle/parallelizer.py, devito/dle/rewriters.py, devito/yask/dle.py, tests/test_dle.py
- deterministic code generation
- collapse more loops
- minor refactoring
- more tests
=> Fixups for OpenMP-based GPU offloading

examples/seismic/tutorials/07_DRP_schemes.ipynb
- Added evaluate to equations because of lazy evaluation.
- Fixed link to Yang Liu paper.
=> Small fixes in DRP schemes notebook

devito/ir/clusters/algorithms.py, devito/ir/support/basic.py, devito/tools/memoization.py, devito/types/grid.py, devito/yask/types.py, tests/test_operator.py
This is something I've been working part time over the last weeks . Unfortunately, it was very low priority so it took a while to get here.
By reworking the way cluster fissioning is performed, the devito compilation speed should have improved in problems with large stencil expressions. 
I need to see how CIs react , and may still need some clean up before landing. But I opened the PR, so at least you can start taking a look
=> Rework cluster fissioning 

.travis.yml
Restore coverage report build at pytest
=> restore coverage

devito/ir/support/basic.py, tests/test_ir.py
It feels like it can't be this easy, but will see what CI has to say!
=> change DependenceGroup to subclass set instead of list

.github/workflows/flake8.yml, .github/workflows/pythonapp.yml
Added github action to perform flake8 using the same arguments as existing travis test.
=> Added gh action for flake8

docker/Dockerfile
Bug fixes for bug nos: #1024 #1062
=> Updated Dockerfile to #1024 #1062

docs/source/equation.rst, docs/source/operator.rst, docs/source/symbolic.rst, docs/source/tensorfunction.rst, docs/source/tensortimefunction.rst, docs/source/vectorfunction.rst, docs/source/vectortimefunction.rst
Update out of date and missing rest files
=> doc update

.github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-ops.yml, .github/workflows/pytest-yask.yml, devito/targets/common/blocking.py, tests/test_dle.py
fixes #1060 
@georgebisbas can you check that this actually fixes the execution through benchmark.py as well?
=> Fix issue 1060

devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/support/basic.py, devito/types/dimension.py, tests/test_dimension.py
fixes #1081 
basically a performance issue due to too much Clusters fusion -- Clusters with ConditionalDimensions shouldn't be fused with so called dense Clusters, as they won't be optimized by the DSE
This PR fixes this
Issue was introduced by #1026 . Was fixing a thing and I ended up causing this. Anyway, now suitable tests added so we should be golden
=> Fix issue 1081

devito/ir/clusters/analysis.py, devito/ir/clusters/cluster.py, devito/ir/clusters/queue.py, devito/ir/iet/analysis.py, devito/ir/iet/efunc.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/ir/stree/algorithms.py, devito/ir/support/basic.py, devito/ir/support/properties.py, devito/ir/support/space.py, devito/mpi/halo_scheme.py, devito/operator/operator.py, devito/passes/clusters/cse.py, devito/passes/iet/misc.py, devito/passes/iet/mpi.py, devito/symbolics/manipulation.py, devito/tools/algorithms.py, examples/compiler/03_iet-A.ipynb, tests/test_ir.py, tests/test_mpi.py
This PR cleans up some code, enhance some classes by adding properties and methods (mostly mere utilities), fix ups a small set of minor (stupid) bugs and... that's it. This PR is just in preparation for the actual consolidation PR which I've been promising for a while. That second PR is ready-ish already, but I will wait for this one to land before opening it
=> Misc clean up and consolidation

devito/core/gpu.py, devito/passes/iet/definitions.py, tests/test_dle.py, tests/test_operator.py
This makes iso-acoustic work again
More PRs (and tests !) to follow this one
=> Resurrect openmp device offloading

docs/source/download.rst
environment -> environment-dev
=> docs: fix environment-dev typo

.github/workflows/pytest-gpu.yml
Fix gpu ci workflow so that it also works for master...
=> Fix gpu ci workflow

.github/workflows/pytest-gpu.yml
Change gpu workflow so that it only executes on a PR. Also some tidying and a new method for extracting the current branch name.
=> GPU workflow cleanup

devito/core/gpu_openmp.py, tests/test_gpu_openmp.py
I tested it quickly and seems to do its job
I will run more tests later, but for now I'll open it
=> Fix memory leaks on GPU

examples/seismic/acoustic/operators.py
Remove the use of `solve` from the acoustic wave-solver.
=> Acoustic wavesolver: Specify stencil explicitly

devito/types/tensor.py, tests/test_tensors.py
indices were wrong with save leading to incorrect stencil with save (.forward was not correct)
=> save with tensor

benchmarks/user/benchmark.py
This PR fixes issue #1128 related to printing `dle` and `autotuning` options.
=> Fixes issue #1128

devito/types/equation.py, tests/test_symbolic_coefficients.py
Fix missing `kwarg` from equations `xreplace` and add a suitable test for this.
=> Fix equation xreplace

examples/seismic/preset_models.py
=> model: fix 3d marmousi setup

.github/workflows/pytest-gpu.yml
This PR adds OpenACC testing to CI.
It is built on top of #1178.
=> Add OpenACC testing to CI  Fixes: #1168

devito/core/gpu_openacc.py, devito/operator/operator.py, devito/passes/clusters/aliases.py, devito/symbolics/manipulation.py, tests/test_dse.py
=> Fix OOB access caused by CIRE

devito/finite_differences/tools.py, tests/test_derivatives.py
- Fix low order (1, 2) indices for cartesian FD
- Removed some unnecessary if/else
=> Low order FD

devito/core/cpu.py, devito/core/gpu_openmp.py, devito/finite_differences/differentiable.py, devito/ir/equations/equation.py, devito/ir/support/space.py, devito/passes/clusters/aliases.py, devito/passes/clusters/factorization.py, devito/passes/clusters/misc.py, devito/symbolics/queries.py, tests/test_dse.py, tests/test_operator.py
This should bring #1212 back to green (@ofmla )
=> Fix scheduling of CIRE-detected aliasing expressions

.github/azure/startVM.ps1, .github/azure/stopVM.ps1, .github/workflows/asv.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-gpu.yml
Main addition is to start and stop the runner during the workflow.
=> asv workflow updates

devito/types/dimension.py, examples/seismic/tutorials/08_snapshotting.ipynb
Minor patch fixing Conditional doc
=> docs:fix Conditional type docs

devito/ir/clusters/cluster.py, devito/ir/support/space.py, devito/mpi/halo_scheme.py, devito/tools/data_structures.py, devito/types/basic.py, requirements.txt
one less dependency for us
supersedes #1238 
fixes #1239
=> Embed frozendict

devito/builtins.py, tests/test_builtins.py
Allow asymmetric padding such as in numpy with `pad((left, right))` and added test
Will be necessary for proper subdomain freesurface for example that would not pad the top.
=> asymmetric padding

requirements.txt
Temporary hold for new sympy-1.6
=> reqs: sympy<1.6

benchmarks/user/benchmark.py, examples/seismic/model.py, examples/seismic/skew_self_adjoint/wavesolver.py, examples/seismic/utils.py, tests/test_benchmark.py
- Enables adjoint/born/gradien if implemented
- Addedd ssa operators
Needs tweaking for `born`
Needed for https://github.com/devitocodes/thematrix/issues/30
=> Bench update

.github/workflows/asv.yml
Update the checkout action. Now corresponds to the version used in `TheMatrix`.
=> update asv action versions

.github/release-drafter.yml, .github/workflows/release-notes.yml
=> CI: add autolog of PRs

devito/types/basic.py, tests/test_symbolics.py
handle non-symbolc indices witg sympify then float-to-ind
=> Indexify with non-symbolic numeric indices 

devito/passes/iet/mpi.py, tests/test_mpi.py
=> Improve detection of redundant halo exchanges

devito/core/cpu.py, devito/core/gpu_openacc.py, devito/core/gpu_openmp.py, devito/ir/clusters/analysis.py, devito/ir/iet/nodes.py, devito/ir/support/basic.py, devito/ir/support/properties.py, devito/ir/support/space.py, devito/ir/support/vector.py, devito/passes/iet/misc.py, devito/passes/iet/mpi.py, examples/compiler/03_iet-A.ipynb, tests/test_ir.py, tests/test_mpi.py
Also drop the unused `loop_wrapping` pass, which in turn enabled dropping some other nearly-dead stuff in data dependence analysis
PR equipped with MFE
=> Fix missing halo exchange over invariants fields

devito/types/dense.py
Update to the halo warning in `dense.py` - as discussed in #1331.
=> Update halo warning

examples/seismic/acoustic/wavesolver.py, examples/seismic/elastic/wavesolver.py, examples/seismic/skew_self_adjoint/wavesolver.py, examples/seismic/tti/wavesolver.py, examples/seismic/viscoacoustic/wavesolver.py, examples/seismic/viscoelastic/wavesolver.py
make dt a solver property to allow model parameter changes
=> Make dt a solve property to use latest model parameters

.github/workflows/cancel.yml
Long-awaited, there is an action for that now, sweet.
=> Cancel previous CI at new commit

devito/symbolics/inspection.py, devito/types/basic.py, devito/types/dimension.py, examples/performance/00_overview.ipynb, tests/test_dse.py
Without this patch the CIRE pass is tricked to hoist more than it should (performance-wise)
=> Fix estimate_cost

.github/workflows/pytest-gpu.yml, examples/seismic/acoustic/acoustic_example.py, examples/seismic/elastic/elastic_example.py, examples/seismic/self_adjoint/example_iso.py, examples/seismic/tti/tti_example.py, examples/seismic/utils.py, examples/seismic/viscoacoustic/viscoacoustic_example.py, examples/seismic/viscoelastic/viscoelastic_example.py
This PR enhances testing on GPUs
- adds MPI+openacc runs for elastic, visco-{acoustic,elastic}
=> Add MPI+GPU runs to CI

devito/compiler.py
One more MPI version that can be sniffed.
=> Added sniffing Intel MPI as MPI version in compiler.py

devito/passes/clusters/aliases.py, tests/test_dse.py
fixes #1477 
EDIT: depends on #1487 , hence the big diff
=> Patch issue #1477

benchmarks/user/advisor/README.md, benchmarks/user/advisor/roofline.py
- Minor doc improvement
- Add a relative path to improve logging
=> Advisor miscellaneous improvements

.github/workflows/asv.yml, .github/workflows/examples-mpi.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-gpu.yml, devito/core/gpu_openmp.py
- Removes repeated example runs
- Examples are now tested with and without MPI
- All examples tested on openacc + openmp
=> Tidy gpu CI workflow

devito/ir/iet/scheduler.py, tests/test_operator.py
This makes _lower_stepping_dims to replace indices by iteration.
Fix #1486
=> ir: Fixup _lower_stepping_dims

.github/workflows/tutorials.yml, devito/builtins.py, devito/builtins/__init__.py, devito/builtins/arithmetic.py, devito/builtins/initializers.py, devito/builtins/utils.py, devito/finite_differences/differentiable.py, devito/finite_differences/operators.py, devito/passes/clusters/aliases.py, devito/types/tensor.py, tests/test_builtins.py, tests/test_derivatives.py
- Fixes #1250 
- Fixes #1177
- Adds shifted div/grad
=> builtins: initialize FD halo

devito/operator/operator.py
Adds global gflops/s to the operator log
=> perf: Add global gflopss to operator log

devito/operator/profiling.py
Advisor workflow was broken after merging #1514 .
This PR fixes the issue.
Advisor workflow is still not tested in CI and is a work in progress feature.
=> Fix profiling IET for Intel Advisor benchmarking

devito/operator/operator.py, devito/types/dense.py, devito/types/dimension.py, devito/types/sparse.py, tests/test_operator.py
=> operator: Patch grid-carried argument overrides

devito/archinfo.py, devito/ir/clusters/analysis.py, devito/ir/equations/equation.py, devito/ir/support/basic.py, tests/test_dle.py
=> Fix loop collapsing

devito/passes/clusters/aliases.py, tests/test_dse.py
=> Patch aliases' min-storage option

.github/workflows/docker-publish.yml
Fix job dependencies in docker workflow.
=> Fix docker ci

.github/workflows/docker-publish.yml
Further docker workflow updates due to build-push-action v2 changes.
=> Docker workflow updates

.github/workflows/docker-publish.yml
A few further tweaks to the docker publish workflow.
=> docker publish tweaks

.github/workflows/pytest-gpu.yml, devito/archinfo.py, devito/core/cpu.py, devito/core/gpu_openmp.py, examples/performance/README.md, tests/test_gpu_common.py
Add common (openacc+openmp) test file to the workflow.
=> Common gpu tests

.github/workflows/asv.yml, .github/workflows/pytest-gpu.yml
Tweak asv + gpu workflow possible activation methods.
=> Tweak asv + gpu workflows

devito/finite_differences/differentiable.py, devito/finite_differences/tools.py, devito/types/tensor.py, tests/test_derivatives.py, tests/test_tensors.py
Shift argument of div/grad accepted as a float or a tuple (Fix #1554)
Add shift option to divergence of TensorFunction and gradient of VectorFunction.
=> Shift argument as a tuple

devito/data/allocators.py
=> Fix find_library issue to MacOS Big Sur

devito/mpi/halo_scheme.py, tests/test_dimension.py
=> compiler: Patch issue #1592 (HaloScheme with time subdimensions)

devito/arch/compiler.py, examples/seismic/viscoacoustic/viscoacoustic_example.py
=> compiler: Target gpu for PGI openacc

devito/arch/archinfo.py, tests/test_gpu_common.py
@FabioLuporini , please check review comments. We could also improve another points (e.g.,  get physical id also from `lspci` and `nvidia-smi`)
=> arch: Review get_gpu_info

devito/core/__init__.py, devito/core/cpu.py, devito/core/gpu.py, devito/ir/stree/algorithms.py, devito/ir/support/basic.py, devito/ir/support/space.py, devito/mpi/halo_scheme.py, devito/symbolics/inspection.py, examples/performance/README.md, tests/test_dimension.py, tests/test_dse.py, tests/test_gpu_common.py, tests/test_gpu_openacc.py, tests/test_gpu_openmp.py, tests/test_ir.py, tests/test_mpi.py
fixes #1610 
fixes #1613 
fixes #1614 
fixes #1616
=> compiler: Fix ScheduleTree construction in presence of guards and/or syncs

devito/operator/operator.py, devito/types/basic.py, devito/types/dense.py, devito/types/dimension.py, devito/types/grid.py, devito/types/sparse.py, tests/test_autotuner.py, tests/test_caching.py, tests/test_derivatives.py, tests/test_dimension.py, tests/test_interpolation.py, tests/test_mpi.py, tests/test_pickle.py
=> compiler: Fix processing of grid spacing

.github/workflows/examples.yml
see conda-incubator/setup-miniconda/issues/162
=> ci: Fix conda build

devito/passes/clusters/asynchrony.py, devito/passes/iet/orchestration.py, devito/types/parallel.py, tests/test_gpu_common.py
hopefully fixes currently broken master, due to a bug that has always been around, but only now pops up (randomly)
=> gpu: Fix leaks due to excessive fetching/prefetching

.github/workflows/docker-publish.yml, .github/workflows/examples-mpi.yml
Slight changes to the mpi-examples workflow owing to its migration.
=> ci: Modify mpi-example workflow and update docker actions

devito/passes/iet/languages/openacc.py, devito/passes/iet/parpragma.py, devito/types/sparse.py, tests/test_gpu_common.py
=> gpu: Fix offloading when zero-size arrays

examples/seismic/tutorials/13_LSRTM_acoustic.ipynb
Good day!
Hello everyone, I would like to change something on the theory part that has been left in portuguese and a equation number.
On the code everything is the same.
Thank you,
Best.
=> examples: Tweak LSRTM_acoustic notebook

examples/seismic/tutorials/13_LSRTM_acoustic.ipynb
Hello All,
Just taking out the source illumination computation from the shots loop.
Regards,
=> examples: Fix source illumination

examples/seismic/viscoacoustic/operators.py, examples/seismic/viscoacoustic/viscoacoustic_example.py, examples/seismic/viscoacoustic/wavesolver.py, tests/test_adjoint.py, tests/test_gradient.py
Hi Guys,
We developed the first-order SLS viscoacoustic Born operator. We hope that the Devito team appreciates the contribution.
=> examples: Add viscoacoustic Born operator to 1st sls equation

benchmarks/user/benchmark.py
=> bench: Patch jacobian operators + MPI (see issue #1744)

devito/core/cpu.py, devito/core/gpu.py, devito/ir/clusters/algorithms.py, devito/ir/equations/algorithms.py, devito/ir/support/space.py, devito/ir/support/utils.py, devito/passes/clusters/aliases.py, devito/passes/clusters/misc.py, devito/types/grid.py, tests/test_dse.py, tests/test_subdomains.py
=> compiler: Patch and improve SubDomainSet

devito/types/grid.py, tests/test_gpu_common.py
=> compiler: Patch SubDomainSet with NVC

.github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, devito/data/data.py, tests/test_data.py
=> mpi: Add MPI support for python3.9

devito/core/gpu.py, tests/conftest.py, tests/test_gpu_openacc.py, tests/test_gpu_openmp.py
Enable code generation of loop tiling for GPU
=> gpu: Loop tiling for GPU

devito/arch/archinfo.py, devito/arch/compiler.py
Add compute capability autodetection to Nvidia GPUs
=> compiler: add nvidia gpu compute capability auto-detection

.github/workflows/examples.yml, examples/seismic/tti/tti_example.py
@FabioLuporini now supports same command line args as acoustic.
=> examples: add adjoint, born, gradient, checkpointing to the tti example

.github/workflows/pytest-gpu.yml, devito/__init__.py, devito/arch/compiler.py, devito/core/gpu.py, devito/ir/clusters/analysis.py, devito/ir/clusters/cluster.py, devito/ir/equations/equation.py, devito/ir/iet/efunc.py, devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, devito/ir/support/utils.py, devito/operator/registry.py, devito/passes/iet/definitions.py, devito/passes/iet/langbase.py, devito/passes/iet/linearization.py, devito/passes/iet/parpragma.py, devito/symbolics/extended_sympy.py, devito/symbolics/printer.py, devito/types/basic.py, docker-compose.yml, tests/test_iet.py, tests/test_linearize.py, tests/test_operator.py
I want to use the JIT backdoor to play with CUDA/HIP/SYCL.
This PR goes in this direction adding misc features concerning both execution and code generation
=> CUDA/HIP/SYCL preliminaries + misc improvements

MANIFEST.in
adding requirements.txt and requirements-optional.txt to create working pypi packages
=> misc: Add requirements.txt and requirements-optional.txt to MANIFEST.in

.github/workflows/pytest-core-mpi.yml, devito/types/sparse.py, tests/test_gpu_common.py, tests/test_mpi.py
=> mpi: Fix mask ordering for sparse gather

devito/passes/iet/linearization.py, tests/test_linearize.py
=> compiler: Patch linearization pass

CITATION.md
Add a citation file, to trigger citation button.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
=> misc: Add citation button

.github/workflows/pytest-core-mpi.yml, docker/Dockerfile, docker/Dockerfile.nvidia, docker/entrypoint.sh, docker/run-jupyter.sh, docker/run-jupyterlab.sh, docker/run-print-defaults.sh, docker/run-tests.sh, setup.py
Add mpi and nvidia options to setup.py
Small cleanup of docker file to actually install devito rather than setting python path for every command
=> Installation: update setup.py and cleanup docker files

docker/Dockerfile, docker/Dockerfile.nvidia
Fix end of line typo on gpu dockerfile
=> install: Fix EOL typo

examples/seismic/tti/operators.py
=> Fix 2D Gzz when sintheta==0

docker/Dockerfile.nvidia
=> install: Fix cflag for nvidia mpi4py

devito/builtins/arithmetic.py, devito/ir/clusters/cluster.py, tests/test_builtins.py
=> compiler: Patch norm enforcing double precision accumulation

devito/builtins/arithmetic.py, devito/builtins/utils.py, tests/test_builtins.py
=> compiler: Patch norm accumulation

devito/ir/support/guards.py, tests/test_ir.py
Used in DevitoPRO but added here because 1) why not and 2) I suspect I'm going to use it in the near future for other stuff
=> compiler: Add GuardOverflow

tests/test_dimension.py
=> tests: Add MFE for issue 1753

devito/finite_differences/coefficients.py, devito/finite_differences/derivative.py, devito/finite_differences/differentiable.py, devito/finite_differences/finite_difference.py, devito/finite_differences/tools.py, devito/passes/clusters/aliases.py, devito/symbolics/__init__.py, devito/symbolics/manipulation.py, devito/symbolics/printer.py, devito/types/array.py, devito/types/basic.py, devito/types/dimension.py, tests/test_derivatives.py
Not sure you'll like everything @mloubout ... anyway, opened for debate
=> compiler: Minor FD refactorings

devito/passes/clusters/implicit.py, tests/test_subdomains.py
E.g. dummy operators with a parallel time dimensions
=> compiler: Patch generate_implicit for corner cases

devito/ir/support/space.py, devito/passes/clusters/misc.py, tests/test_fission.py
=> compiler: Patch fission (issue 1921)

devito/arch/archinfo.py, devito/arch/compiler.py, devito/tools/memoization.py
Add flags and libs for openmp support on apple m1. Leads to decent performance gain (over gcc-11 on my laptop)
=> arch: Support OpenMP on Apple M1

devito/finite_differences/derivative.py, devito/finite_differences/differentiable.py, devito/finite_differences/elementary.py, devito/finite_differences/finite_difference.py, devito/finite_differences/tools.py, devito/operations/interpolators.py, devito/types/basic.py, devito/types/dimension.py, devito/types/equation.py, devito/types/lazy.py, devito/types/tensor.py, tests/test_derivatives.py
There still is a lot of work to do, and this PR itself would greatly benefit from in-depth testing and adjustments, so please feel free to contribute , directly (commits) or indirectly (comments).
The PR isn't too big, but it touches a fairly delicate piece of code, so it needs careful reviewing.
Note that this PR is _not_ deploying two-stage evaluation -- there still is a long way to go. But it builds on the previous one and now at least exploits `StencilDimension` in the context of the newly introduced `IndexSet`.
PR equipped with tests.
=> compiler: Inception of two-stage derivative evaluation

devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, devito/passes/iet/definitions.py, devito/types/__init__.py, devito/types/basic.py, devito/types/object.py, tests/test_iet.py
This is the smallest of my stream of PRs, nothing big going on
=> compiler: Restructure basic.Object sub-hierarchy

.github/workflows/docker-devito.yml, .github/workflows/pytest-gpu.yml
Tested and working as can bee seen for dev:
https://github.com/mloubout/CIDebug/actions/runs/2776343404
and release (latest fixed in this PR as well):
https://github.com/mloubout/CIDebug/runs/7615747425?check_suite_focus=true
=> docker: Fix docker tags for publish

docker/Dockerfile.nvidia
=> install: Patch Dockerfile.nvidia

.github/workflows/docker-devito.yml
Remove bad condition preventing build and deploy on release
=> docker: fix deployment condition

devito/arch/compiler.py
=> compiler: Check jit_dir existence when saving

devito/ir/clusters/algorithms.py, devito/ir/support/utils.py, devito/passes/clusters/blocking.py, tests/test_dimension.py, tests/test_dse.py
=> compiler: Patch placement of ConditionalDimension with multi-Dimension conditions

devito/operations/interpolators.py, devito/types/sparse.py, tests/test_interpolation.py
- Fixes remaining hardcoded `-1` for the position of the sparse index
- - Fix missing implicit dims for the final equation of interpolation
Added test for it
=> types: Minor fixes to sparse function indices and implicit dims

devito/builtins/initializers.py, devito/builtins/utils.py, devito/ir/iet/efunc.py, devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, devito/operator/operator.py, devito/passes/iet/asynchrony.py, devito/passes/iet/definitions.py, devito/passes/iet/engine.py, devito/passes/iet/langbase.py, devito/passes/iet/languages/openacc.py, devito/passes/iet/languages/openmp.py, devito/passes/iet/linearization.py, devito/passes/iet/parpragma.py, devito/tools/data_structures.py, devito/types/dimension.py, devito/types/misc.py, devito/types/parallel.py, examples/compiler/03_iet-A.ipynb, examples/compiler/04_iet-B.ipynb, tests/test_builtins.py, tests/test_derivatives.py, tests/test_dimension.py
fixes #1927 
proves that issue #1435 has actually been fixed, by adding the attached test
Some more misc improvements, polishing, tweaks
=> compiler: Further misc improvements

devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/iet/utils.py, devito/ir/iet/visitors.py, devito/ir/support/properties.py, devito/ir/support/space.py, devito/operator/operator.py, devito/passes/clusters/aliases.py, devito/passes/clusters/blocking.py, devito/passes/clusters/buffering.py, devito/passes/clusters/cse.py, devito/passes/iet/engine.py, devito/passes/iet/linearization.py, devito/passes/iet/misc.py, devito/types/basic.py, devito/types/misc.py, tests/test_dimension.py, tests/test_dle.py, tests/test_linearize.py
This PR fixes some compilation issues emerging in the CUDA/HIP backends in devitopro
The PR is equipped with tests that capture the origin of such issues
=> compiler: Better blocking heuristics and revamped linearization

CONTRIBUTING.md, FAQ.md, README.md, docker-compose.yml, docker/README.md, docker/entrypoint.sh, docs/source/download.rst, examples/seismic/source.py, examples/seismic/utils.py
- Mainly updates Docker instructions
- Split Docker CPU-GPU
- Add Devito pip package
- Drop duplicated text
=> misc: Update docker/README.md

docs/source/download.rst, tests/conftest.py, tests/test_autotuner.py, tests/test_dse.py
=> ci: Add Arm skip option to tests

devito/finite_differences/elementary.py, devito/ir/iet/visitors.py, devito/mpi/routines.py, devito/operator/operator.py, devito/passes/iet/misc.py, devito/passes/iet/mpi.py, devito/symbolics/inspection.py, devito/symbolics/printer.py, examples/performance/00_overview.ipynb, tests/test_linearize.py, tests/test_symbolics.py
=> compiler: Fix and improve MIN/MAX codegen

.github/workflows/cancel.yml, .github/workflows/pytest-aws.yaml, devito/arch/archinfo.py, devito/arch/compiler.py
AWS gravition arch and aws-ec2 on-demand self-hosted runners
Fixes #1106
=> arch: Support aws graviton

.github/workflows/asv.yml, benchmarks/regression/asv.conf.json, setup.py
=> CI: fix asv setup

devito/passes/clusters/buffering.py
Test is in PRO (not practical to test it here)
=> compiler: Patch double buffering

devito/symbolics/extended_sympy.py
=> misc: fix short/ushort codegen

devito/finite_differences/differentiable.py
=> compiler: Tweak Weights.value

devito/tools/utils.py
=> dsl: Correct retention of wrong branch in filter_ordered

devito/passes/clusters/unevaluate.py, tests/test_pickle.py
Fix issue with pickling operator with sparse + subs
=> compiler: fix unevaluation of sparse cluster

devito/ir/clusters/algorithms.py, devito/ir/equations/equation.py
Symptom: norm(SparseTimeFunction) slightly off with CUDA or HIP
Test added to PRO
=> compiler: Patch mapify-reduce for SparseTimeFunctions

devito/ir/iet/visitors.py, devito/passes/iet/misc.py
=> compiler: Hotfix and simplify minimize_symbols

devito/ir/support/properties.py
=> compiler: Fix update_properties

requirements.txt
I keep getting tripped up by this every time I create a new `venv`
=> install: Add packaging to requirements

.github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml
See: https://github.com/actions/runner-images/issues/11101
=> Update 20.04 runners to 22.04

.github/workflows/pytest-core-nompi.yml, devito/finite_differences/differentiable.py, devito/ir/cgen/printer.py, devito/symbolics/extended_sympy.py, devito/tools/utils.py, examples/seismic/tutorials/05_staggered_acoustic.ipynb, tests/test_dse.py, tests/test_symbolic_coefficients.py, tests/test_symbolics.py
=> compiler: Fix issue 2577 - edit printer for unevaluation Mul

devito/mpi/halo_scheme.py, devito/passes/iet/mpi.py, tests/test_mpi.py
One extra test is added in PRO
=> compiler: Patch merge and reduction HaloScheme passes

devito/ir/clusters/algorithms.py, devito/ir/clusters/analysis.py, devito/ir/clusters/visitors.py, devito/ir/support/basic.py, devito/operator/operator.py, devito/tools/memoization.py, tests/test_ir.py, tests/test_tools.py
Reverts devitocodes/devito#2669
=> Revert "compiler: Cache `Scope` + `Dependence` instances"

devito/ir/clusters/algorithms.py, devito/ir/clusters/analysis.py, devito/ir/clusters/visitors.py, devito/ir/support/basic.py, devito/operator/operator.py, devito/tools/memoization.py, tests/test_ir.py, tests/test_tools.py
=> compiler: Reapply "Cache `Scope` + `Dependence` instances"

devito/finite_differences/differentiable.py
=> compiler: Enable late evaluation
