devitocodes/devito

.travis.yml
Currently requires explicit setup of the python env via homebrew and apt.
=> Travis: Test linux and osx builds

README.md, devito/operator.py, devito/propagator.py, tests/test_cache_blocking.py
Allows user to specify which dimensions he does not want to block by setting block sizes to `None`.
Fixed "#pragma openmn for" bracket bug.
Fixes the cache blocking error that caused segmentation faults.
Fixes remainder loop logic. Now there will be separate remainder loop for each block. To make sure we iterate through each element.
Rewriten test_cache_blocking.py tests to cover full range of models.
=> Cache blocking Update

devito/interfaces.py, tests/test_save.py
- Added methods to initialize spatial data and retrieve results from TimeData objects. 
- Added a test for the save parameter.
A little issue: The final result is at `timesteps - 2` while one would expect it to be at `timesteps - 1` since the Devito calculated values start from 0.
My guess is that the result when `save=False` is not the 100th timestep, but the 99th. I can't see why that would happen though.
EDIT: Added issue https://github.com/opesci/devito/issues/69 regarding this problem
=> Fixed and tested Interfaces.TimeData save parameter

devito/propagator.py
Changed the time_substitutions method to build a dictionary of changes to be made by Sympy.subs before calling it instead of calling subs every time as suggested by @mlange05
=> Optimized time_substitution method

devito/__init__.py, devito/codeprinter.py, devito/interfaces.py, devito/iteration.py, devito/operator.py, devito/propagator.py, examples/Acoustic_codegen.py, examples/TTI_codegen.py, examples/fwi_operators.py, examples/tti_operators.py, tests/test_adjointA.py
This merge is primarily intended to fix issue #48 by extending the Propagator API to insert user-defined loops over low-level "indexed access" expressions to perform sparse point interpolation. For this purpose a new class `Iteration` is introduced that encapsulates a single loop over a defined dimension. In more detail this PR brings:
* A new symbolic data object `CoordinateData` that gets attached to `PointData` objects and stores the coordinates of the sparse points.
* Fixes to the Operators `input_params` and `output_params` lists, including a more general way of avoiding duplication in the function signature. It also makes the call to `initialize()` on input params optional.
* New `Iteration` class that encapsulates a single loop iteration over a defined iteration space. It …
=> Point interpolation via `Iteration` blocks

devito/interfaces.py, tests/test_save.py
This PR tries to address some of the problems discussed in issue #71 .
- It is now possible to initialize TimeData objects using an `initializer` function. (Note: This is also the only way to initialize them if `save=True`). `test_save.py` has been modified to demonstrate this.
- Removed `get_data` and `init_data`
=> Removed get_data and init_data, changed TimeData.initialize()

devito/function_manager.py, devito/operator.py, devito/profiler.py, devito/propagator.py
- Added a Profiler class to manage the profiling of the code.
- Moved the logic for running the `cfunction` to `Propagator`.
- Added profiling for time loop stencils, space loop and kernel.
- Modified FunctionDescriptor and FunctionManager to accept struct
parameters (and also fixed to also add scalar parameters that 
weren't added by the manager)
=> Overhauled and improved profiling

devito/__init__.py, devito/interfaces.py, tests/test_symbolic_data.py
This provides a solution to issue #84 
The clean method needs to be explicitly called by the user. 
Otherwise, the symbolic cache keeps expanding and keeping a reference to every data object ever created, blowing up the memory usage.
=> Added clean() method to `SymbolicData` and `Operator`

devito/compiler.py, devito/propagator.py, devito/tools.py
Added alignment pragma, which replaces ivdep pragma if running with OpenMP
=> Alignment pragma

devito/propagator.py
In `acoustic_example` we have a stencil of this form:
```
Eq(U[t, x, y, z], 2.85234567901235*(0.70117728531856*u[t, x, y, z] - 0.35058864265928*u[t - 1, x, y, z] - 0.35058864265928*u[t + 1, x, y, z])*dm[x, y, z]/m[x, y, z] + U[t, x, y, z])
```
That generates this line of code with the current rules:
```
U[t2][i1][i2][i3] = 2.85234567901235F*(-3.5058864265928e-1F*u[t1][i1][i2][i3] + 7.0117728531856e-1F*u[t2][i1][i2][i3] - 3.5058864265928e-1F*u[t2 + 1][i1][i2][i3])*    dm[i1][i2][i3]/m[i1][i2][i3] + U[t2][i1][i2][i3];
```
This goes out of bounds when `t2 = 2`.
This PR fixes that.
=> Added missing rules to Propagator.t_replace

devito/interfaces.py, devito/memmap_manager.py
Add some comments.
Add the ability to have files of repeated name, which happened in acoustic_example(though in this case it may not cause an issue, but similar cases can happen in the future).
Add the ability to retain created file, default behaviour is to delete all files created.
Please ignore changes at places other than devito/interface.MemmapManager, those are just merge conflict.
=> Refinement over use of memmap

devito/profiler.py
`Profiler.gflops` can sometimes fail if the time is recorded as 0 for some entries. It now returns `NaN` instead.
=> Check for timings > 0 when calculating GFLOPS

devito/operator.py, devito/propagator.py, examples/tti_operators.py
This PR solves:
- an issue with the collection of terms that change during the execution of the loop
For example, this could happen:
```
double temp = u[t2][i1][i2]
u[t2][i1][i2] = ….
U[t2][i1][i2] = temp + ….
```
After this fix, this is what we'd get:
```
double temp;
temp = u[t2][i1][i2]
u[t2][i1][i2] = ….
temp = u[t2][i1][i2]
U[t2][i1][i2] = temp + ….
```
- an issue with temporaries depending on other temporaries causing compiler errors (this slows down the code quite a bit)
Thanks to @mloubout for pointing out the issues
EDIT: Also changed tti_operators.ForwardOperator not to use `factorized`.
EDIT2: Fixed another bug that caused some temporaries to be reverted when not needed, making the second issue pointed out in the original post disappear in the process
=> CSE bug fixes

.travis.yml, devito/profiler.py, devito/propagator.py, devito/tools.py, examples/TTI_codegen.py, examples/tti_benchmark.py, examples/tti_example.py
This is on top of #102 #103 and #106 
Allows users to benchmark and plot `tti_example.py` using `opescibench`.
```
usage: tti_benchmark.py [-h] [-o] [-d DIMENSIONS DIMENSIONS DIMENSIONS]
[-s SPACING SPACING] [-t TN] [-c] [-a]
[-cb CACHE_BLOCKING CACHE_BLOCKING] [-r RESULTSDIR]
[-p PLOTDIR] [--max_bw MAX_BW] [--max_flops MAX_FLOPS]
[{run,bench,plot}] [{gnu,intel,clang,mic,knl}]
Example script for TTI.
positional arguments:
{run,bench,plot}      Script mode. Either 'run', 'bench' or 'plot'
{gnu,intel,clang,mic,knl}
optional arguments:
-h, --help            show this help message and exit
-o, --omp             Enable OpenMP
-d DIMENSIONS DIMENSIONS DIMENSIONS, --dimensions DIMENSIONS DIMENSIONS DIMENSIONS
Dimension of the grid
-s SPACING SPACING, --spacing SPACING SPACING
Spacing on the grid …
```
=> Benchmark for TTI example

devito/propagator.py
Now, All the temps in the generated code is defined in this way:
```c
float temp = ....;
```
instead of : 
```c
float temp;
temp = ....;
```
Reduce the file size.
=> Fixed the issue #108 (quality of generated code), reduced the generated file size

devito/interfaces.py, examples/acoustic_example.py, examples/tti_benchmark.py, examples/tti_example.py
The origin and spacing should be a three dimensional tuple because it's acoustic wave modelling in 3d.
=> Fixed the inconsistence between shape of spacing and dimensions in acoustic example

examples/benchmark.py
`benchmark.py` used the data for the whole kernel, while only the main loop is needed (according to discussion with @mloubout on Slack)
=> Benchmark saves only loop_body data

devito/profiler.py, devito/propagator.py
The `dtype` was never passed to the Profiler, so it always calculated OI based on 4 bytes long floats. This fixes it by having the propagator pass its dtype to the profiler.
Also changed name from `byte_size` to `float_size`
=> Profiler: Byte size fix

examples/acoustic/Acoustic_codegen.py, examples/benchmark.py, examples/tti/TTI_codegen.py
A small set of tweaks to the roofline plotting routine in `benchmark.py` that ensure pretty diagrams. Requires `opescibench` PR #2 to go in with this.
Further pretty plotting (with colour!) will follow soon.
=> Improved roofline plotting

devito/at_controller.py, devito/codeprinter.py, devito/logger.py, devito/profiler.py, devito/propagator.py, examples/acoustic/Acoustic_codegen.py, examples/acoustic/acoustic_example.py, tests/test_cse.py, tests/test_gradient.py, tests/test_symbolic_data.py
There are two spurious commits in this PR, which fix the ``acoustic`` example when benchmarking. 
Apart from those, with this PR a number of issues concerning the AT are fixed:
- Avoid unacceptably long AT runs, because too many block sizes were attempted. Now a heuristic is used: only square blocks whose size is a multiple of 2 are picked. This can be refined by extending the corresponding method ``at_controller.py:AutoTuner:_filter`` 
- Avoid executing useless sample runs. 
- Avoid executing a dry run, which was just a hack to populate some lists and make things work. The dry run was also using block sizes that could go beyond the limits imposed by ``minimum`` and ``maximum``, so this might also result in a C-level bug. 
- Fill in output arrays with some random values, to ensure that …
=> Many AT fixes

.travis.yml
This merge adds a new build matrix to the travis setup that includes a thread-parallel GCC builder to address issue #144. It also seems to fix recent OSX builder instabilities by updating the OXC builder to xcode8.
=> Travis parallel testing

examples/acoustic/acoustic_example.py, examples/containers.py
Profiling the model startup on acoustic suggests that the expression `vp**(-2)` takes up large chunks of time, presumably because it does not use NumPy vectorisation. Replacing it with `1. / vp * vp` seems to be much faster. 
The change in `IGrid.padm()` gives approximately 2x speedup for the initialisation of `m` in `fwi_operators.py:ForwardOperator` and the change in `acoustic_example.py:run()` reduces it's impact from 30% to around 5% in a single-timestep run on a 256^3 grid.
=> Vectorise `vp**(-2)` via NumPy

LICENSE.md, README.md, setup.cfg, setup.py
This merge adds a license file (MIT) and a `setup.py` to allow Devito to be installed via pip, as well as other minor housekeeping changes.
=> Pip install, license and housekeeping

.travis.yml, devito/codeprinter.py, devito/compiler.py, devito/function_manager.py, devito/stencilkernel.py
This merge adds version-specific compiler presets for the GNU toolchain `gcc-4.9` and `gcc-5` and switches travis to use both. It also adds a `CustomCompiler` class which reads the `CC`, `CFLAGS`, `LD` and `LDFLAGS` flags if `DEVITO_ARCH` is not set.
EDIT: This merge now also switches back to C99 compilation during JIT.
=> More compiler presets

examples/acoustic/Acoustic_codegen.py, examples/acoustic/acoustic_example.py, examples/acoustic/fwi_operators.py, examples/containers.py, examples/tti/TTI_codegen.py, examples/tti/tti_example.py, examples/tti/tti_example2D.py, examples/tti/tti_operators.py, tests/test_adjointA.py, tests/test_gradient.py, tests/test_rewriter.py
Small PR to make the examples a bit more usable by people. The source and data are now separated avoiding the `None` argument at every operator call. Everything else is the same.
=> Source separated

devito/dimension.py, devito/expression.py, devito/interfaces.py, devito/iteration.py, devito/memory.py, devito/stencilkernel.py, devito/tools.py, examples/diffusion/example_diffusion.py, examples/source_type.py, tests/test_stencil_arithmetic.py
Ok, this is a bit of a blanket PR for the next steps in the re-development of the low-level code generator (currently `StencilKernel`). It adds a set of features that allow us to switch the diffusion example over to the new API and includes in detail:
* Additional tests for the low-level "indexed" API in stencil kernels
* Compatibility with the high-level API through "indexification" in `Expression`
* Automatic derivation of loop bounds from the stencil indices
* Automatic derivation and substitution of loop variables in `Iteration`
* Global symbol substitution in stencil kernel
* `Dimension` objects define "buffered" loops, eg. over dimension "time"
Note: `StencilKernel` objects now behave equivalently to `Operator/Propagator` objects in terms of "baked-in" loop limits. However, these …
=> More work towards a recursive code generator

devito/compiler.py
Currently the `CustomCompiler` ignores OpenMP mode. This change adds the OpenMP-specific linker flags from either `OMP_LDFLAGS` or using the GNU defaults.
=> Add OpenMP linker flags from `OMP_LDFLAGS` to CustomCompiler

devito/interfaces.py, devito/memory.py, tests/test_symbol_caching.py, tests/test_symbolic_data.py
This merge introduces a range of tests for the various cases of symbol caching we do on top of SymPy, as well as a fix for the current aliasing bug (thanks @navjotk).
One `xfailed` test also highlights another remaining caching bug, where we fail to cache new instances of the same function object as SymPy does. Presumably this causes `clear_cache()` to fail if we are running multiple test instances in a single session, but this will be dealt with separately.
=> Fix and test cache aliasing

devito/dse/extended_sympy.py, devito/dse/graph.py, devito/dse/inspection.py, devito/dse/symbolics.py, devito/function_manager.py, devito/interfaces.py, devito/logger.py, devito/propagator.py
This PR introduces:
* the concept of ``DSE transformation step`` (see the ``dse_transformation`` decorator in symbolics.py)
* a complete new DSE transformation step: code motion. This is implemented in ``_replace_time_invariants``. Time-invariant sub-expressions are sought and given a score. If the score is greater than an empirically determined threshold, then the sub-expression at hand is "lifted" outside the time loop and evaluated in a temporary
* taylor-based approximation of sin/cos. The default choice, however, is still Bhaskara, as tests start failing with Taylor. I wonder if this is due to the remarkably bad approximation that Taylor gives as one gets far from default center, 0
* refactoring and improvements of various nature for the DSE
* extended propagator to emit …
=> DSE - code motion and other features

devito/dse/extended_sympy.py, devito/dse/inspection.py, devito/dse/manipulation.py, devito/dse/symbolics.py, devito/function_manager.py, devito/operator.py, devito/profiler.py, devito/propagator.py, examples/benchmark.py, tests/test_rewriter.py
This PR makes a step forward towards Devito 2.0
The obsolete, hacky, and bug-prone profiler.py module is drastically trimmed, and its key functionality of "counting flops in the generated code" is moved to the DSE. It is indeed possible to count the number of operations by applying the DSE function ``estimate_cost``, which in turn wraps Sympy's  ``count_ops``, to any Sympy expression.
The operation of counting the memory accesses performed by a Sympy expression is also moved to the DSE (from Propagator).
Summing up, now the DSE returns a data structure containing:
- the transformed expressions
- a mapper to identify time-invariant expressions, out of the transformed expressions
- operations count
- memory accesses count
This PR depends on #170
=> Move profiling to DSE

devito/compiler.py
On GCC version 4.8.4 our compiles otherwise fail with the recent denormals fix due to SSE not being enabled.
=> Compiler: Adding `march=native` to `GNU/CustomCompiler` to enable SSE

devito/dimension.py, devito/dle/__init__.py, devito/dle/inspection.py, devito/dle/transformer.py, devito/dse/__init__.py, devito/dse/inspection.py, devito/dse/symbolics.py, devito/interfaces.py, devito/logger.py, devito/nodes.py, devito/stencilkernel.py, devito/visitors.py, tests/test_dle.py, tests/test_visitors.py
*** Note ***
This PR has been opened to promote discussion, but it still lacks:
- flake8 fixes, isort fixes
- a full run of the test suite (let's see what Travis says...)
- more tests (either tomorrow or Monday)
*************
*** EDIT 1 ***
- passing all tests
- added some DLE tests
*************
Now ``StencilKernel`` is a very special node in an Iteration/Expression tree -- a node that can be JIT-compiled and that is allowed to call the optimization engines. As part of this generalization, more nodes and visitors have been introduced. Further, some performance information is now emitted.
Moreover, the PR introduces the DLE -- Devito Loop Engine. This is an analogous of DSE, but for loop optimization (eg, tiling, parallelization). Only one transformation step is at this stage applied, …
=> Toward Devito 3.0: extended StencilKernel, introduce DLE

devito/tools.py, devito/visitors.py, tests/test_dle.py
This merge should fix the spurious breakages in current master. 
It adds a new utility routine `filter_sorted()` that behaves like
`filter_ordered` but also enforces sorting according to a key.
=> FindSymbols: Filter symbol names and sort them

devito/dimension.py, devito/interfaces.py, devito/nodes.py, devito/stencilkernel.py, devito/tools.py, devito/visitors.py, tests/test_visitors.py
This merge includes a set of utility routines and visitors for the `StencilKernel` that bring us closer to being able to handle the FWI examples. Most notably it includes:
* Pretty-print an AST with a custom visitor. This visitor has a `verbose` mode that:
* If `False` returns a nicely indented short description string of the loop structure.
* If `True` incorporates all relevant meta-information about the core node types, allowing us to use it as the base of the kernel hash key.
* A new `MergeOuterIteration` transformer that recursively merges matching `Dimension`s so that we can group expressions under them. This is very useful for source terms.
* Fix to include the zero-offset for each `Dimension` in `Expression.index_offset`, which allows us determine "dimensions used in an expression" …
=> Outer iteration merge and other niceties

devito/dle/inspection.py, devito/dle/transformer.py, devito/nodes.py, devito/stencilkernel.py, devito/tools.py, devito/visitors.py, requirements.txt
This PR mainly introduces two transformation steps in the DLE:
- Generation of pragmas for OpenMP parallelism
- Generation of pragmas to trigger compiler auto-vectorization
The OpenMP parallelization looks way simpler than that in the Propagator, but it should be effective in exactly the same way. I talked to @pvelesko , and it turns out the original OpenMPization through the propagator had been done by a number of people, or perhaps mostly by @navjotk ? I'm interested in your thoughts.
Some generated code follows, from our Diffusion example:
```
#include "stdlib.h"
#include "math.h"
#include "sys/time.h"
#include "xmmintrin.h"
#include "pmmintrin.h"
struct profiler
{
double loop_t_0;
} ;
int Kernel(const int t_size, float *u_vec, const int x_size, const int y_size, struct profiler …
```
=> DLE: OpenMP and SIMD

devito/dimension.py, devito/interfaces.py, devito/memory.py, devito/nodes.py, devito/stencilkernel.py, devito/visitors.py, examples/acoustic/Acoustic_codegen.py, examples/acoustic/fwi_operators.py, examples/source_type.py, tests/test_adjointA.py, tests/test_gradient.py
**WARNING: This merge contains temporary hacks that are necessary due to legacy restrictions. It also attempts to clean a few things for acoustic test, but it does not attempt a full clean-up of our seismic examples. A full clean-up of the examples and a more rigorous generalisation of the temporary hacks will be attempted soon.**
So, this PR really contains a series of "as-clean-as-currently-possible" changes and fixes to adjust the Acoustic Forward runs to the 3.0 API. It introduces a `legacy` flag on the acoustic examples classes that allows us to switch between the two modes seamlessly and thus compare and contrast. The 3.0 route is not exhaustively tested yet, but it should allow us to run preliminary performance benchmarks to get an overview of how 3.0 will do and fix issues before …
=> Tweaks, hacks and fixes to make Acoustic-Forward run with Devito-3.0

devito/nodes.py, devito/visitors.py, examples/acoustic/Acoustic_codegen.py, examples/acoustic/acoustic_example.py, examples/acoustic/fwi_operators.py, examples/benchmark.py, examples/tti/TTI_codegen.py, examples/tti/tti_example.py, examples/tti/tti_operators.py, tests/test_rewriter.py, tests/test_tti.py, tests/test_visitors.py
This merge applies the same type of trickery to allow TTI to be run through the new `StencilKernel` interface, hidden behind a `legacy` flag for now. It comes with a small set of bug fixes and the necessary test modifications and also hooks up profiling information for the acoustic and TTI wrappers for the new API.
Travis does not test the new code path yet due to the heavy nature of all tests involving TTI, but I have verified correctness of the relevant tests locally. This merge is intended to allow us to like-for-like test the current with the 3.0 API and gather performance data ahead of the switch. Support for 3.0 on acoustic and TTI is currently still on a "best effort" basis, until we have a better handle on some of the outstanding issues.
=> Tweak TTI to run via Devito3.0

examples/acoustic/fwi_operators.py
Simple stencil fix for Born. I though it was in one of my previous PR but I guess I messed up somewhere with the merge/rebase.
Anyway, it is a simple typo fix `u->U` in the second stencil and diff operators for Born.
=> Though that was fixed, guess it disapeared in some master merge

devito/dimension.py, devito/dse/symbolics.py, devito/interfaces.py, devito/nodes.py, devito/operator.py, devito/stencilkernel.py, devito/tools.py, tests/test_timestepping.py, tests/test_tools.py
After long deliberation and experimentation we finally introduce the ability to add reverse-time operators through the new 3.0 API. To the outside this looks pretty similar to the previous approach where an operator argument `StencilKernel, eq, subs=subs, time_axis=Forward/Backward` determines the direction of the time loop.
Under the hood this now behaves slightly different, where the `Dimension.reverse` on the dedicated `time` dimension is set according to the given parameter. This ensures that:
a) We can use the same `time`/`t`symbols in forward and backward runs
b) Custom dimensions may also be inverted if desired
We also introduce a new high-level utility object `TimeAxis` that describes the particular mode of "time" to use in an operator and will hopefully be extended soon.
This …
=> Reverse time interface for 3.0

devito/propagator.py
- They don't need to be that big
- Breaks `cgen` on 32 bit machines
This is expected to fix #213
=> Change the type of block sizes to np.int32

devito/compiler.py
In its current state, master is broken on my machine - OSX 10.11.6 with python 2.7.
This is the stack trace: 
```
Traceback (most recent call last):
File "examples/acoustic/acoustic_example.py", line 103, in <module>
run(full_run=True, auto_tuning=False, space_order=6, time_order=2)
File "examples/acoustic/acoustic_example.py", line 88, in run
auto_tuning=auto_tuning, compiler=compiler, legacy=legacy,
File "/Users/navjotkukreja/Work/ipcc/devito/examples/acoustic/Acoustic_codegen.py", line 103, in Forward
fw.apply()
File "/Users/navjotkukreja/Work/ipcc/devito/devito/operator.py", line 155, in apply
self.propagator.run(self.get_args())
File "/Users/navjotkukreja/Work/ipcc/devito/devito/propagator.py", line 134, in run
f = self.cfunction
File …
```
=> Fix wrong library extension

devito/compiler.py, devito/finite_difference.py
Small PR that allow any order for the second derivative while the old version had hard-codded order [2,4,6,8,10,12,14,16] only.
=> all orders second derivative

devito/compiler.py
When using the `CustomCompiler`, the pragma used for ignoring vector dependencies is the one for the intel compiler. This change allows the pragma to be set with an environment variable.
This continues the thought behind having a compiler completely configurable by environment variables.
=> Allow pragma to be set by env variable

devito/compiler.py, devito/exceptions.py, devito/stencilkernel.py, tests/test_stencil_arithmetic.py
In response to #220 
This PR adds:
- The ability to do `op.apply(m=m1)`
- A test for this
There is one tiny caveat in this implementation though. In order to do `op.apply(m=m1)`, both `m` and `m1` need to have the same `name` property. In case this is not true, the expected syntax is `op.apply(m=m1.data)`. 
Edit: Never mind, the above has been fixed as well. `op.apply(m=m1)` would work regardless of the symbol names.
=> Allow symbol data to be substituted at the time of applying the Operator

devito/stencilkernel.py, examples/acoustic/Acoustic_codegen.py, tests/test_stencil_arithmetic.py
Issue #228 points out a case where changing the name of a `SymbolicData` object changes the order in which dimension sizes are inferred and this causes the size of the `time` dimension to be inferred incorrectly. 
This was being caused because of the way sizes are being inferred. Particularly, when a `BufferedDimension` is encountered, a parent dimension was [added](https://github.com/opesci/devito/blob/master/devito/stencilkernel.py#L166) to the list of `Dimension`s if not already present. This last condition introduced a requirement on the order in which the `Dimension`s are presented to this loop since if the parent `Dimension` appears later in the list of dimensions, its size would already be set by the child `Dimension` and its real size would never be captured. 
This PR fixes that …
=> Fix wrong size inferred for buffered dimension

devito/__init__.py, devito/dle/transformer.py, devito/interfaces.py, devito/memory.py, devito/pointdata.py, examples/source_type.py, tests/conftest.py, tests/test_declarator.py, tests/test_dle.py, tests/test_point_data.py, tests/test_visitors.py
This merge moves the `PointData` class into it's own sub-module and provides an explicit API for supporting `point.interpolate(expr)` and `point.inject(expr)` methods to perform sparse-point interpolation of custom user-defined expressions in and out of grid variables. This is a pre-requisite for providing more general source/receiver terms in our seismic examples. 
Note, the merge does not yet integrate this new API with our actual examples, since there is more required to make this shine (to come in a separate PR). The current test set is also limited, in that it only interpolates the expression "1" at the moment. Input with more advanced expressions and their analytical solutions would be greatly appreciated.
Other details in this PR:
* We now store the sparse point coordinates as plan …
=> `PointData` generalisation

devito/__init__.py, devito/logger.py, devito/parameters.py, examples/acoustic/Acoustic_codegen.py, examples/acoustic/fwi_operators.py
This PR:
- Introduces a global configuration dictionary named `parameters` since we like to take inspiration from Firedrake. 
- Changes the logger to pick up its log-level from this configuration rather than setting the default in the logger itself. This is provided as an example of the intended use of this dictionary plus @mloubout seemed to want something like this anyway. 
- The `Forward`, `Adjoint` etc. methods of `Acoustic` had a superfluous parameter `data` which is also removed in this PR. 
Nearly a year after this issue was raised in #26 
In the next iteration, the config can be extended to read from a file/environment variables but I believe this should do for the current purposes.
=> Global configuration

devito/interfaces.py, devito/memory.py, examples/acoustic/gradient_example.py
This PR adds an example in the `examples` folder based on `test_gradient`, however it reproduces this test without any wrappers on the operators. This way the operators are available directly in the example code to play around with, for feature development.
This is especially helpful for #216 since this can be the basis for the example that is required to build the interface to the revolve checkpointer. 
This can serve as an example of how something complex like the gradient test can be implemented with pure Operators with (relative) ease. 
This PR also adds a utility function to the `CMemory` class (the one that wraps devito allocated memory) to do a quick `memset`. This is required to be able to reuse the same block of memory for multiple passes.
This PR includes the changes from #241 …
=> Gradient test based example without wrappers

docs/devito.rst, docs/heat.rst
Following the reinstatement of the auto-documentation deployment, this PR updates the module list for the core `devito` documentation (excluding DLE and DSE). It also adds minor updates to the diffusion tutorial for the website to align with the new 3.0 API.
=> (Incomplete) documentation cleanup

tests/test_operator.py
New test for `external=True`
This will ensure that 
- There is no initialization/compilation bug
- It actually produces the same result than `OperatorCore`
=> test_foreign

docs/deploy.sh, docs/devito.rst
Due to some problems with the configuration of the documentation generator, the last merge build failed on master. This attempts to fix those issues.
=> Fix doc generator problems

devito/interfaces.py, devito/operator.py, docs/devito.rst, tests/test_operator.py, tests/test_save.py
The primary goal of this PR is to fix the derivation of dimension sizes so that we can supply the number of timesteps as `op(time=no_timesteps)` or `op(t=no_timesteps)`. The PR _should_ make that part of `Operator.arguments()` easier to understand, and also fixes various other issues in the process: issues #236, #250 #251 and the problem outlines in #255. In particular it does:
* Add a separate test for symbol overrides via numpy arrays
* Fix the `TimeData` constructor so that the `dimensions` parameter now works as the `shape` one - ie. user-supplied argument for `shape` and `dimensions` ignore time and we implicitly add the time dimension based on `save`/`time_order`/`time_dim`.
* We now explicitly warn if the user sets `time_dim` on a buffered time object (`save=False`), since the …
=> Various fixes to runtime argument derivation

devito/dse/graph.py, tests/test_dse.py
Much faster expression scheduler (noticeable in TTI -- significantly shorter waiting time between the DSE and the DLE outputs to terminal)
Achieved through a different implementation of `is_index`, now also supported by some tests
=> Speedup schedule expressions

devito/interfaces.py, docs/deploy.sh
Smal tweaks and fixes to the docstrings in `interfaces.py`, partially in response to comments on #236. Also some tentative fixes to the deploy script that hopefully will fix the docs build.
=> Fix docstrings for `TimeData` and `DenseData`

examples/seismic/acoustic/acoustic_example.py
#274 
The keyword names now match and the correct dimensions argument is propagated through to the setup() call
=> Correct spelling mistake in acoustic example setup

devito/compiler.py, devito/dle/__init__.py, devito/dle/backends/__init__.py, devito/dle/backends/yask.py, devito/exceptions.py, devito/interfaces.py, devito/memory.py, devito/tools.py, tests/test_yask.py
* Support for data movement through YaskGrids, which basically wrap YASK Grid objects and act like numpy arrays. Why wrapping was preferred over inheritance? see comments in code, but basically to avoid wasting twice as much memory, because of the difference in storage layouts (what YASK uses and what the users wanna see)
* Add tests!
* Update to more recent YASK API
* Handle many more types of grids
* Many other small features
Next step: restructuring our source directory in a way that YASK acts like a different backend, not just a different sequence of DLE passes.
=> Yask integration phase2

devito/cgen_utils.py, devito/dimension.py, devito/dle/__init__.py, devito/dle/backends/advanced.py, devito/dle/backends/basic.py, devito/dle/backends/common.py, devito/dle/backends/utils.py, devito/dle/blocking_utils.py, devito/dle/inspection.py, devito/dle/manipulation.py, devito/dse/clusterizer.py, devito/dse/graph.py, devito/dse/manipulation.py, devito/dse/symbolics.py, devito/exceptions.py, devito/interfaces.py, devito/nodes.py, devito/operator.py, devito/profiling.py, devito/tools.py, devito/visitors.py, tests/test_dle.py, tests/test_operator.py
This PR does three main things:
1- it ships a range of (relatively small) improvements all over the codebase
2- bug fixes
3- it "generalizes" the loop blocking algorithm
1 - Improvements
=============
1.1 Simpler and more effective DLE ``create_elemental_functions()``
1.2 More powerful DLE inspection routines (eg, ``filter_iterations()``)
1.3 Better, refreshed documentation
1.4 Introduction of ``OperatorDebug`` to ease C-level debugging
1.5 Refactoring. Profiling now in a separate module; dropped legacy functions (now unused); more visitors, enhanced Transformer; updated tests
2 - Bug fixes
=========
2.1 Always attempt to generate parametric array sizes
2.2 Fix data type construction at code generation time (see changes in ``cgen_utils.py``)
2.3 Attach pragmas to ``Iteration``, not …
=> Generalized loop blocking

requirements.txt, setup.py
Added missing entry in the `setup.py` file.
Also for some reason install wants `cached-property` instead of `cached_property`
=> cached-property install

environment.yml
Should fix travis testing and needs to be rebased/merged into ongoing development.
=> Travis: Drop external conda channels and use pip instead

devito/memory.py, devito/operator.py
1) Pre-load `libc` in `memory.py` to avoid race-conditions on unclean shutdowns in Python3, eg.:
```
ImportError: sys.meta_path is None, Python is likely shutting down
```
2) Use `filter_ordered` instead of `list(set(...))` during parameter derivation in `operator.py` (the former is deterministic, the latter is not).
=> Small fixes for Python3 environments

examples/seismic/acoustic/operators.py, examples/seismic/acoustic/wavesolver.py, examples/seismic/tti/operators.py, examples/seismic/tti/wavesolver.py
Should be fairly uncontroversial and fix the flood of "Explicit time dimension" warnings generated by our seismic wavesolver wrappers for forward operators.
=> Seismic: Fix "Explicit time dimension" warning for forward wavefields

devito/__init__.py, devito/backends.py, devito/compiler.py, devito/core/autotuning.py, devito/core/operator.py, devito/dle/transformer.py, devito/dse/symbolics.py, devito/interfaces.py, devito/logger.py, devito/parameters.py, examples/PERFORMANCE.md, tests/test_autotuner.py
fixes #334 
This makes it possible to access ``configuration`` from basically everywhere in Devito, w/o having to use local imports
=> Remove critical circular dependencies

devito/arguments.py, devito/cgen_utils.py, devito/dse/extended_sympy.py, devito/nodes.py, devito/pointdata.py, devito/visitors.py, devito/yask/__init__.py, devito/yask/interfaces.py, devito/yask/operator.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/test_point_data.py, tests/test_yask.py
~NOT ready for merge yet, although we're basically there.~
Now we can execute through YASK any Devito kernels mixing sources/receivers-like loop nests (w/ indirect memory accesses) and parallel loops (ie, loops that can be "offloaded" to YASK).
In the generated code ...
... The offloadable loops are replaced by a function call to YASK
... All other loops remain "explicit" in the generated code, but array accesses are replaced with YASK grid accesses. This involves some shared pointer magic in the compiler and in the generated code.
Tests are also added
=> YASK: Support for loops with indirect accesses

devito/interfaces.py, devito/yask/__init__.py, devito/yask/interfaces.py, devito/yask/operator.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/test_yask.py
Two critical fixes in the **YASK backend**:
- The following is now supported, as expected in Devito:
```
u0 = TimeData(name='u', shape=S, dimensions=D, ...)
u1 = TimeData(name='u', shape=S, dimensions=D, ...)
``` 
Clearly u0 and u1 cannot be used in the same Operator. Previously, attempting to create two shared object with same name/shape/dimensions would have raised an error
- A data object shape now corresponds to the "domain size"; the halo, inferred from ``space_order``, is "constructed" on top of the shape, not by removing inner points. This matches the YASK behavior. This represents an API divergence points w.r.t. the default backend. However, we expect the default backend to adopt this semantics as well in the (close) future, in particular when the Grid abstraction will become …
=> yask: More fixes and change semantics of data.shape

devito/interfaces.py
Tiny fix for `ConstantData` that was skipping `eval=false` in the `new options`.
Was making sympy solve fail.
=> ConstantData new_cls fix

environment.yml
This should get our trvis testing back online and green (he said hopefully). :wink:
=> Travis: Get utility packages from conda-forge

devito/interfaces.py, examples/seismic/acoustic/operators.py, examples/seismic/acoustic/wavesolver.py, examples/seismic/model.py, examples/seismic/tti/wavesolver.py, tests/test_adjointJ.py, tests/test_gradient.py
Cleanup according to #358 
> have a single ArgumentParser, used by both acoustic and TTI and any other future seismic equations. Perhaps to be moved to a utils.py module under examples/seismic
Not sure about this one, it would make it easier to run/benchmark for us but will start to make the example inaccessible for a lot of users IMO. 
> Use memoization in acoustic, in the same way we did for TTI
Done
> Move legacy leftovers of the following sort to model:
This will end up in `if-else` somewhere anyway, not sure it should/where it sould be moved.
`demo_model` docstring updated
=> Examples cleanup

.travis.yml, devito/compiler.py, devito/yask/__init__.py, devito/yask/wrappers.py, examples/seismic/plotting.py, examples/seismic/source.py, tests/conftest.py, tests/test_adjointA.py, tests/test_adjointJ.py, tests/test_autotuner.py, tests/test_derivatives.py, tests/test_dimension.py, tests/test_dle.py, tests/test_dse.py, tests/test_finite_difference.py, tests/test_gradient.py, tests/test_operator.py, tests/test_point_data.py, tests/test_save.py, tests/test_symbol_caching.py, tests/test_timestepping.py, tests/test_tools.py, tests/test_tti.py, tests/test_visitors.py, tests/test_yask.py
Depends on #364. 
This merge adds a dedicated YASK builder to our travis setup that pulls the current YASK development branch and executes a dedicated small test suite with it while skipping all other tests. This will allow us to gradually enable more of our regular test base on the YASK-backend as it develops.
One thing I note is that despite `-j3` the YASK compile times are quite severe, making the test suite quite slow;  but that might need to be addressed upstream.
=> Travis setup for YASK testing

.travis.yml, devito/compiler.py, devito/interfaces.py, devito/nodes.py, devito/tools.py, devito/yask/__init__.py, devito/yask/utils.py, devito/yask/wrappers.py, environment.yml
As it turns out our `python3` travis builder has been silently reverting to `python2.7` for some time, meaning a few small bugs have crept in. Since the old trick of separating the two environments doesn't seem to work any more, this PR will switch to Python-3.6 for testing exclusively. The Python version is now also hard-defined in the `environment.yml`.
=> Switching to and fixing Python3.6

devito/arguments.py, devito/dimension.py, devito/dle/backends/basic.py, devito/function.py, devito/types.py, devito/visitors.py, tests/test_symbol_caching.py
First part of an internal data type shake up that should make `Constant` objects more compatible with the various backends. The primary idea is to
* Split our internal caching data types into `Function`s, symbols representing tensor/array data that carry indices, and `Symbol`s, dimension-free, scalar symbols.
* By providing `AbstractSymbol` in addition to `AbstractFunction`, we can now add our internal `Symbol` types (spacing symbols, iteration size variables, etc.) to our caching hierachy, but also better emulate the expected meta-data of functions. This means:
* We now have to initialise them as `Symbol(name='symbols_name')`, and `s0 = Symbol(name='s'); s1 = Symbol(name='s')` don't cache anymore.
* We can provide all the meta-data expected of functions, eg. `dtype`, `indices`, etc...
* …
=> Turn `Constant` into a `Symbol`, not `Function`

devito/algorithms.py, devito/dle/backends/advanced.py, devito/dle/backends/basic.py, devito/dle/backends/common.py, devito/dle/backends/utils.py, devito/dle/blocking_utils.py, devito/dle/transformer.py, devito/dse/__init__.py, devito/dse/clusterizer.py, devito/dse/graph.py, devito/dse/transformer.py, devito/flow.py, devito/nodes.py, devito/operator.py, devito/types.py, devito/visitors.py, devito/yask/utils.py, tests/test_dle.py, tests/test_operator.py
Lots of edits, but, in practice very, very, very little is actually changing.
The reason you see lots of edits is that I've moved a few things around, or (in the case of the DLE edits) I've improved the structuring so that compiler passes work at the level of individual abstract syntax trees, rather than "lists of abstract syntax trees" as was before. So the edits are due to
previously:
```
def pass(ASTs):
for i in ASTs:
do_something(i)
```
now:
```
def pass(i):
do_something(i)
```
Perhaps you don't appreciate it from this description, but the code is now much nicer in the DLE
The main change of this PR is that now data dependence analysis (leading to decoration of ASTs with properties such as PARALLEL, SEQUENTIAL, etc.) is performed **before** the DLE, through the ``flow.py`` module. …
=> Preliminaries to timeslot optimization

devito/__init__.py, devito/backends.py, devito/compiler.py, devito/parameters.py, devito/tools.py, devito/yask/__init__.py, environment.yml
Shuffles the configuration options around a little to enable us to switch to the YASK backend dynamically from within a single Python interpreter - for example an Azure notebook session.
=> Enable dynamic backend switching

devito/__init__.py, tests/test_operator.py
When setting the `openmp` option explicitly from Python, we need to re-initialise the `Compiler` object to update the linker flags, etc. **This now enable seamless switching between sequential and threaded mode in notebooks** via `configuration['openmp'] = True`!  @ggorman @FabioLuporini  
Also adding a small fix for a debug leftover that has crept in somehow.
=> Configuration: Fix dynamic OpenMP switch

tests/test_operator.py
Small test fix.
The test was actually failing but wasn't caught as only three time-steps were ran and the modulo was hiding it (modulo 3)
`a` needs to be reinitialized to get correct result.
=> Test op fix

devito/function.py, devito/profiling.py, tests/test_operator.py
This PR adds a new `staggered` keyword to `Function` and `TimeFunction` objects that adjusts the data shape and the casts in the generated code according to staggering offsets. That means that, for example, a 2D `Function` staggered in `y` (`staggered=(0, 1)` stores DoFs on the side-edges and allocates a shape of `nx, ny-1`.
Note: **This does not affect any symbolics for staggered grids or derivatives. I'm still playing with that!**
=> Staggered grid allocation

.travis.yml, docs/tutorials.rst
They have not been updated in the latest tutorial push - so this PR fixes that. It also enables the auto-docs for the `yask` sub-package.
=> Fix seismic weblinks

devito/dse/backends/advanced.py, devito/dse/backends/speculative.py, devito/dse/transformer.py, devito/ir/clusters/__init__.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/iet/analysis.py, devito/operator.py, tests/conftest.py, tests/test_dse.py, tests/test_operator.py
~*** This should go in after #421, which will make the diff much cleaner ***~
EDIT: ready for review
This PR exploits the previously merged #401 and #406 PRs to perform advanced data dependence analysis in Devito. Some details about this had already been provided in the descriptions of these two PRs.
There are three major things going on here:
* Reimplementation of cluster fusion, based on vector distance analysis. This is what will fix loop construction for staggered, @mlange05 . So this new piece of code **is** actually fixing bugs that weren't exposed with the currently available use cases. This happens in ``ir/clusters/algorithms.py``.
* Reimplementation of Iteration analysis; that is, the engine that detects, for example, parallel and sequential loops. This happens in …
=> ir: Introduce new data dependence analysis engine

devito/ir/iet/analysis.py, tests/test_symbol_caching.py
It's a class-level cache of sympy expressions, that otherwise keeps our functions alive.
=> IET: Drop `Analysis` cache, to fix memory leak

devito/function.py, devito/ir/iet/nodes.py, devito/ir/support/stencil.py, devito/operator.py, examples/seismic/acoustic/gradient_example.py, examples/seismic/acoustic/operators.py, examples/seismic/acoustic/wavesolver.py, examples/seismic/tutorials/02_rtm.ipynb, examples/seismic/tutorials/03_fwi.ipynb, examples/seismic/tutorials/06_skimage_tv.ipynb, tests/test_checkpointing.py, tests/test_operator.py, tests/test_save.py, tests/test_timestepping.py
With this PR, we change the `TimeFunction` API so that instead of using `save=True` in combination with `time_dim=nt`, we just use `save=nt` (and `save=None` for the `save=False` case). All tests and examples have been updated to use the new API which looks cleaner. 
`time_dim` is now changed as a means of setting the symbolic `Dimension` object used to represent the `TimeFunction`'s time dimension internally. This is currently being debated in slack.
Also included are two unrelated bug-fixes from @FabioLuporini :
1. `repr(Operator)` now works
2. Loop scheduling bug when `time` and `t` are used in the same expression - we now generate the correct loop nest. Test included for this.
=> Update TimeFunction API to generalise save

devito/arguments.py, examples/seismic/tutorials/01_modelling.ipynb, examples/seismic/tutorials/02_rtm.ipynb, tests/test_checkpointing.py, tests/test_operator.py, tests/test_save.py, tests/test_yask.py
**Problem:** The current implementation enforces a different indexing scheme for explicitly passed dimension arguments to the one used throughout the rest of the codebase (allocation, codegen, etc.) by adding stencil offsets to the provided values. Since we currently do not capture user-induced buffer overruns (see #426), this can lead to user-induced buffer overruns that cause sporadic failures in the test base if explicitly passed arguments do not account for this magic behaviour.
**This merge reverts this behaviour and enforces a consistent index addressing scheme throughout the code base.** It accordingly adjusts to the _currently(!) correct_ usage of explicitly provided values for the time dimension in all failing test cases (mostly YASK and checkpointing), and reverts the previous …
=> Fix offsets for explicitly passed arguments

devito/__init__.py, devito/compiler.py, devito/dimension.py, devito/function.py, devito/ir/clusters/algorithms.py, devito/ir/iet/analysis.py, devito/ir/iet/nodes.py, devito/tools.py, devito/types.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/test_yask.py
Yet another consolidation PR
- Improved (up-to-date) docs
- Fix output reports (reported iteration counts might be a small quantity (O(1)) off)
- Refactor the ``codepy.Compiler`` hierarchy and (finally!) get rid of all annoying gcc-induced warnings. Travis' trace will now be much cleaner. 
- If the specific compiler version supports OpenMP 4.0, we now unconditionally add the appropriate ``-openmp`` flag so that ``#pragma simd omp`` are reconognised and vectorization properly triggered
- Drop support for Intel MIC (untested => broken; unused => useless; broken + useless => drop)
- Fix a subtle bug by adding a specialised ``_hashable_content`` to ``Dimensions``
- Minor fixes in YASK
=> Misc: cleanup, fixes, improvements, docs

.travis.yml, devito/__init__.py, devito/base.py, devito/compiler.py, devito/core/__init__.py, devito/data.py, devito/parameters.py, devito/tools.py, devito/types.py, devito/yask/__init__.py, devito/yask/data.py, devito/yask/function.py, devito/yask/types.py, examples/seismic/acoustic/wavesolver.py, examples/seismic/benchmark.py, examples/seismic/tti/wavesolver.py
* Our memoizer caches at the class level; for the seismic wrappers, instead, it'd be better to cache at the instance level. Otherwise, these are unusable from benchmark.py as we would start leaking memory. This PR introduces a new memoizer suitable for instance-level caching. 
* Better compilation infrastructure
* ``benchmark.py`` tweaks; in particular, better memory clean up, use preemptive AT in yask mode
* Allow per-backend specialisation of caching clean up
* Fix up potential memory leak in YASK
=> Some consolidation

.travis.yml
Turns out my previous laziness and lack of understanding/patience for `bash` was causing individually executed examples to fail silently. This hotfix fixes this oversight and the missing import for the `foreign` backend that brought this to light.
Many apologies for the inconvenience caused - I guess `bash` and I will never be friends. :frowning:
=> Fix conditional examples execution

devito/data.py
correctly propagate instance attributes after numpy array views / operations
fixes #471
=> core.Data hotfix

devito/arguments.py, devito/dle/backends/advanced.py, devito/dle/blocking_utils.py, devito/dse/backends/advanced.py, devito/dse/transformer.py, devito/exceptions.py, devito/ir/__init__.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/equations/__init__.py, devito/ir/equations/equation.py, devito/ir/iet/__init__.py, devito/ir/iet/analysis.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/ir/support/basic.py, devito/ir/support/stencil.py, devito/operator.py, devito/yask/operator.py, tests/test_dle.py, tests/test_dse.py, tests/test_operator.py, tests/test_visitors.py
~The diff is huge, but mainly because this PR needs #468 to go in first. I'm filing it just to show progress is being made.~
EDIT: Ready for review
OK, so, this took a while because I basically had to rethink (simplify) and cleanup the process that lowers equations down to loops. Main features of the PR are
- ``ir.Eq`` is now a first-class citizen in the compiler; it represents a "lowered equation". It is attached an ``IterationSpace``
- ``clusterize`` now groups ``ir.Eq``s and doesn't need stencils anymore; the required information is carried by the equations themselves, through ``IterationSpace``.
- ``Stencil`` is now less powerful, as ``IterationSpace`` does (in a much better and cleaner way) most of the job. 
- an ``IterationSpace`` carries ``sub_iterators``. In essence, a …
=> Rethink loop generation before domain-allocation switch (PART 2)

devito/dse/backends/advanced.py, devito/symbolics/manipulation.py
@mloubout this at least fixes the TTI compilation issue (shifted mode)
I cannot reproduce the segfault in aggressive mode though, and I tried really hard
anyway, let's start taking a look at this
=> symbolics: Fix xreplace_constrained when providing pure symbols

.travis.yml
This PR unrolls the apt-package specs in the travis file for each builder in the build matrix. This means we now only install one compiler version per builder, rather than all of them, dropping the apt-install time from ~10min to about 1-2min.
=> Travis separate compilers

devito/base.py, devito/core/__init__.py, devito/dimension.py, devito/function.py, devito/ir/iet/scheduler.py, devito/types.py, devito/yask/__init__.py, examples/seismic/source.py, tests/test_derivatives.py, tests/test_interpolation.py, tests/test_operator.py, tests/test_symbol_caching.py, tests/test_yask.py
Distinguish between ``SparseFunction`` and ``SparseTimeFunction``. Significant use of inheritance to avoid redundant code. 
~Should go in after #481 and #482 ~
A requirement for the domain-allocation switch, as I need to see the ``time_order`` value in all time functions (including the sparse ones, indeed)
~EDIT: this PR is open to debate of course~
EDIT: turns out I had to do deeper clean up and changes. I think the function hierarchy now looks way better. One caveat is that now modulo buffered iteration works in a slightly different way -- better in my view.
If you say that a time function has for example ``time_order=3`` **and** your equations are actually usually a number of slots ``N`` such that ``N < 3 + 1``, then only those ``N`` slots will be iterated over. Look at the small …
=> Better SparseFunction

.travis.yml, examples/cfd/01_convection_revisited.ipynb
Since the commit referenced below, nbval doesn't like it if a cell says it hasn't been executed but still has output.  I guess nbval recently got updated in conda, and so now everything in travis is failing as a result.
https://github.com/computationalmodelling/nbval/commit/4f2c983b51f6a5fb2a94d5e1344b96cd1872d351#diff-806fb60ab15974e9a2fe3495b18ac7d9
=> examples/cfd: fixup execution counts to match the presence of output

Dockerfile.jenkins, Jenkinsfile, examples/seismic/tutorials/05_dask.ipynb
This PR adds two files for Jenkins configuration:
- Jenkinsfile, which defines the Jenkins pipeline
- Dockerfile.jenkins, which is used by the Jenkins pipeline as build rules for the Jenkins test image
The functionality *should* be identical to Travis-CI apart from the automatic doctr gh-pages push that happens on Travis and needs to be re-implemented on Jenkins.
One additional fix is included, ignoring output for a tutorial example which causes a fail on Jenkins
Worth noting is that as well as running the CI it pushes a test environment image out to dockerhub, giving the option of locally running tests in an identical environment to that which Jenkins uses. This could also do with some refinement going forwards in terms of the docker image labelling.
=> Initialise Jenkins configuration

devito/dimension.py, devito/function.py, devito/operator.py, devito/tools.py, devito/types.py, examples/checkpointing/checkpoint.py, tests/test_interpolation.py
This PR:
- Adds (brings back) a `FixedDimension` class, used when the size of a dimension is known at the time of creation
- Adds a `PrecomputedSparseFunction` class that can do interpolation of sparse points using precomputed coefficients - this can be used to implement arbitrary interpolation schemes. 
- Adds a test for the new `PrecomputedSparseFunction` class by precomputing coefficients using a bilinear scheme
~This branch currently does not pass tests due to a DSE bug where symbols used as indices for `Indexed` types are not found by the visitors. @FabioLuporini could you look into this please. An alternate branch `interpolation2` has a few hacks in place to work around the bug and passes this test.~
=> Interpolation with precomputed coefficients

README.md, examples/PERFORMANCE.md
Change opesci.org to devitoproject.org throughout. Change `PERFORMANCE.md` to reflect the fact that 320 is a devito bug, not a GCC bug.
=> Small updates to docs

README.md, docker-compose.yml, docker/Dockerfile, docker/entrypoint.sh, docker/run-jupyter.sh, docker/run-print-defaults.sh, docker/run-tests.sh
=> Dockerize devito application

devito/data.py, tests/test_data.py
I was motivated to add this after wasting time tracking down a mistake which turned out to be a stupid one (using `u.forward` on a `TimeFunction` with `time_order=0`), and getting errors like this:
```
Fatal Python error: GC object already tracked
```
or this:
```
Fatal Python error: XXX block stack underflow
Current thread 0x00007f4d9882f740 (most recent call first):
Aborted
```
or various others, all with useless tracebacks under gdb, since the memory had been corrupted long before the crash.
It adds a new allocator, the `GuardAllocator`, which inserts a 1MB (by default) padding both before and after every allocation, and sets `mprotect` to cause a segfault if the padding area is accessed.  This causes more crashes, but at least they crash where they should, and can be debugged.
It sets …
=> RFC: ALLOC_GUARD to raise segfaults rather than causing silent corruption

devito/dimension.py
Since the change to inclusive bounds, `d_s==d_e` is no longer a zero-iteration loop.  The ability to have these is very handy, e.g. for disabling a receiver or source loop without needing to recompile the Operator.
This patch pretty much does what it says in the title - allows the specific case of `d_M==d_m-1`, to express this intention.  Open to suggestions for something more elegant.
=> allow max == min-1 for 0-sized loops

devito/__init__.py, devito/base.py, devito/core/__init__.py, devito/function.py, devito/types.py, tests/test_interpolation.py
This PR replaces #554, which will now be closed. 
It contains:
1. the test from #554 , which was failing there. 
2. A new class `PrecomputedSparseTimeFunction` which is the precomputed counterpart of `SparseTimeFunction`. 
3. With the introduction of the above class, the test now passes.
=> Introduce SparseTimeFunction

devito/symbolics/extended_sympy.py, devito/symbolics/manipulation.py, environment.yml, requirements.txt, tests/test_dse.py
When C code is written, sympy Pow operations remaining in the expressions are converted to pow().  This is a double-valued function, and I have seen it inadvertently cause whole expressions to be evaluated as doubles rather than as floats.
pow_to_mul already converts most such powers into chains of multiplications, and this PR extends that to negative powers, which often appear in 2nd-derivative operators, e.g. as ``pow(h_x,-2)``.  It also adds some sanity checks/limits.
Please comment, in particular on how I should handle the (possibly nonexistent) case of exp=0.0
=> dse: extend pow_to_mul to handle negative integer powers

devito/dle/backends/parallelizer.py, devito/dse/backends/basic.py, devito/equation.py, devito/function.py, devito/grid.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/ir/support/basic.py, devito/mpi/distributed.py, devito/operator.py, devito/tools/abc.py, devito/types.py, devito/yask/dle.py, devito/yask/utils.py, examples/checkpointing/checkpoint.py, examples/seismic/acoustic/operators.py, examples/seismic/model.py, tests/conftest.py, tests/test_ir.py, tests/test_mpi.py
The title is self-explanatory
At this stage I think it's more important to state what's **missing**:
* support for SparseFunction injection/interpolation when these operators have a stencil, implying that a same sparse point may need to be communicated to more than one MPI rank
* use cached_property for _dist_* methdos, as they are expensive. The cached value needs to be invalidated upon an access to ``coordinates.data``
* tests of the above features
Once we have all of the above, in theory we can run some fairly advanced examples (wave equations)
=> MPI: initial support for SparseFunction and related operators

devito/compiler.py
This should shut off clang when unused variables are encountered (yes, we still occasionally generate some)
@mloubout can you check on your Mac that this doesn't break jit in any stupid way
=> compiler: Make clang behave similarly to gcc

devito/symbolics/queries.py
This is some juicy low-hanging fruit that showed up in profiling.  For me, this speeds up the python component of Operator creation by ~20%.
Happy to pretty it up a bit and/or remove the debug info about the slow path - this is really just to start a discussion.
=> explicitly test for the most common cases in q_affine

devito/compiler.py, devito/function.py, devito/mpi/distributed.py, tests/conftest.py, tests/test_mpi.py
Two things shipped by this PR:
* MPI is not automatically initialized when importing a module from devito. This means that from a different Python session we can exec ``mpirun python my_devito_program.py``  and this will work. I needed it for our testing framework, but I suspect it's gonna be useful in general in other situations, especially if MPI_Spawn is unsuitable or if we are going through a third-party library and we don't have direct control . However, when running with ``DEVITO_MPI=1``, MPI is initialized (unless already initialized) as soon as the first ``Grid`` is created. 
* Generalize the testing framework so that it can be run with OpenMPI (previously only MPICH was working)
=> Lazy MPI initialization and OpenMPI support

docs/tutorials.rst
Fix a typo in tutorials docs (double parenthesis: "))" )
=> Fix a typo in tutorials docs

tests/test_adjoint.py, tests/test_gradient.py, tests/test_yask.py
Small fix in tests to use vector norm instead of matrix norm.
=> force vec norm instead of matrix norm in tests

devito/dimension.py, devito/function.py, devito/grid.py, devito/ir/support/space.py, devito/mpi/distributed.py, devito/yask/function.py
Currently `_prepare_arguments` (located in `operator.py`) is fairly time consuming. Upon repeated calls to `op.apply()` many arguments are being 're-prepared' when there is no need. This begins to address this problem by caching certain properties e.t.c.
Note that this is a first step and more work is required to further reduce the overheads of repeated operator calls.
=> Caching some properties for efficiency. See issue #657.

devito/__init__.py, devito/builtins.py, devito/data/allocators.py, devito/data/data.py, devito/data/decomposition.py, devito/function.py, devito/grid.py, devito/yask/function.py, examples/seismic/acoustic/acoustic_example.py, examples/seismic/source.py, examples/seismic/utils.py, tests/test_checkpointing.py, tests/test_data.py, tests/test_derivatives.py, tests/test_gradient.py, tests/test_mpi.py, tests/test_operator.py, tests/test_pickle.py
This PR adds:
* some built-in Operators to compute norms/inner products/... of Functions when over MPI. These are meant to be used in place of NumPy linalg functions when MPI is used.
* bunch of tweaks to Data indexing and manipulation over MPI
* cleanup and minor fixes
* lots of new MPI-related tests
=> MPI: support for running isotropic acoustic

devito/__init__.py, devito/core/autotuning.py, devito/core/operator.py, devito/dle/backends/common.py, devito/operator.py, devito/yask/wrappers.py, tests/test_autotuner.py
* 'runtime' mode for 'core' so that we don't waste time
* more tests
* enhanced ``op.apply`` interface (now can pass basic/aggressive/... directly as ``op.apply(autotune=aggressive)`` instead of setting them globally via ``configuration``)
see tests for more info
=> Revamp autotuning

devito/ir/support/space.py
This tripped me up a lot in the early days.  It's fairly easy to end up with a numpy integer instead of an int, and then unexpected things happen.
=> replace isinstance(...,int) with is_integer(...)

.travis.yml, Jenkinsfile
not a bug in our code (neither devito nor yask). We apparently just need to get swig from conda-forge .
This avoids a nasty bug due to importing a fauly Qt-based backend in matplotlib. Apparently the conda-forge install does not downgrade matplotlib/qt to the faulty versions
=> fix YASK segfault

azure-pipelines.yml
Add yaml configuration to restrict pipelines runs to master branch and PRs which target master branch
Documentation for this is found at:
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml
=> Restrict testing on pipelines

devito/dle/backends/basic.py, devito/ir/stree/algorithms.py, devito/ir/support/basic.py, devito/mpi/halo_scheme.py, devito/symbolics/queries.py, devito/types/basic.py, devito/types/constant.py, devito/types/dimension.py, devito/yask/data.py, devito/yask/operator.py, devito/yask/transformer.py, devito/yask/wrappers.py, tests/test_data.py, tests/test_ir.py, tests/test_mpi.py
the AFFINE property detection is now much smarter than it used to be , hence YASK can now offload more IETs (in particular, higdon-like boundary condition loops)
=> YASK: misc fixes

devito/core/operator.py, devito/dle/backends/advanced.py, devito/ir/iet/analysis.py, devito/ir/iet/nodes.py, devito/ir/iet/properties.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, devito/ir/support/basic.py, devito/mpi/halo_scheme.py, devito/mpi/routines.py, tests/test_mpi.py
This is based on #754 , which explains the diff
The main thing this PR does is changing the way the HaloSpots are scheduled and analysed within an IET.
Previously, HaloSpots were flatten out, so we could have:
```
HaloSpot(u)
HaloSpot(v)
Iteration
Iteration
Iteration
Expression involving u and v
```
Now, a HaloSpot embeds the Iteration nest it "refers to" -- meaning, the Iteration nest requiring the halo exchange described by the HaloSpot itself. 
```
HaloSpot(u,v)
Iteration
Iteration
Iteration
Expression involving u and v
```
This has no immediate effect, but it will simplify implementation of computation/communication overlap (2 PRs far from this one)
=> MPI enhancements 

devito/types/constant.py, tests/test_constant.py
Setting `_arg_defaults` to be a `memoized_meth` of course resulted in things such as `const.data=j` not working. This fixes that and adds a little test ensuing that constant can be set as the user desires.
=> Fix constant bug

examples/seismic/source.py, examples/seismic/tti/operators.py, examples/seismic/tti/tti_example.py, examples/seismic/tti/wavesolver.py, tests/test_adjoint.py, tests/test_dse.py, tests/test_tti.py
To small main thing:
- fix the `__new__` in sources that was ignoring the cache and therefore failing with time derivative for these sources
- reduces the number of test in test_adjoint to speed up Travis and spread the different space orders over these OT 4 test so that we still test all of it.
=> Minor fixes and speedup

devito/__init__.py, devito/compiler.py, devito/core/autotuning.py, devito/core/operator.py, devito/data/allocators.py, devito/dle/parallelizer.py, devito/dse/backends/advanced.py, devito/dse/backends/common.py, devito/ir/iet/nodes.py, devito/mpi/routines.py, devito/profiling.py, devito/types/basic.py, devito/yask/types.py, examples/seismic/acoustic/acoustic_example.py, scripts/set_omp_pinning.sh, tests/test_autotuner.py, tests/test_dle.py
This PR adds:
* A first version of nested shared-memory parallelism, still based on OpenMP
* The capability of autotuning in presence of MPI (the MPI ranks tune themselves autonomously in preemptive/destructive mode)
Also it fixes/tweaks:
* Autotuning when there are multiple blocked loop nests in the same operator (now it doesn't tune over the cartesian product of all possible block shapes, but rather it tunes each loop nest individually)
* The use of OpenMP collapsing in some nasty cases
Finally, it ships (as usual) a number of small tweaks throughout the codebase
PR equipped with new tests oc
fixes #143
=> Performance optimisation improvements

benchmarks/user/benchmark.py, devito/__init__.py, devito/archinfo.py, devito/compiler.py, devito/core/__init__.py, devito/core/autotuning.py, devito/data/allocators.py, devito/dle/parallelizer.py, devito/dle/rewriters.py, devito/dle/transformer.py, devito/dse/transformer.py, devito/logger.py, devito/ops/__init__.py, devito/parameters.py, devito/profiling.py, devito/yask/__init__.py, devito/yask/dle.py, devito/yask/operator.py, devito/yask/utils.py, devito/yask/wrappers.py, tests/test_dse.py, tests/test_yask.py
This PR adds the Platform class hierarchy (CPU64, Intel64, KNL, ... ARM, ..., Power, ...) so that the compiler can make platform-specific choices when it comes to optimization. 
The nice thing now is that if you want to cross-compile (note: I'm talking about the code that devito generates, not the actual machine code) for a certain target architecture, now you can do it with ``DEVITO_PLATFORM=...`` and for example ``knl`` rather than ``hsw``. On KNL, for example, nested parallel loops are collapsed and nested parallelism is enabled.
By default, we stick to the ``cpu64`` mode, which is essentially what we have in master
This PR also drops now uselss environment variables: DEVITO_DLE_OPTIONS and DEVITO_ISA. In particular, the highest ISA now is bound directly to a Platform, so no need to …
=> Rework Platform-related machinery

devito/dle/parallelizer.py, devito/dle/rewriters.py, devito/tools/utils.py, tests/test_autotuner.py, tests/test_dle.py
all non-affine loop nests now use ``schedule(static)`` rather than ``schedule(static,1)``. This improve performance of ompized sparse loops
=> openmp scheduling fixes

devito/types/dense.py
Name says it all, really.  Without this, I think that TimeFunctions declared over non-standard time dims (e.g. ConditionalDimensions) are not unpickled correctly.
=> pickle TimeFunction.time_dim

devito/data/allocators.py
Trivial fixes to KNL flat mode detection.  The "is KNL" doesn't work anymore because there is a second definition of the KNL7210 platform now, which is a distinct object.
=> knl detection fix

devito/operator.py
The devito configuration dictionary at the time an operator is constructed is now saved to that operator's state, accessible via Operator._state['optimizations']. 
The purpose of this is to allow reproducibility in the case that a user did not modify their Python script (same operator, space_order, etc.) but maybe called a Python script from a terminal or runscript where certain environment variables (e.g. DEVITO_DSE) were set. New printouts include pertinent configuration settings for a given operator.
=> operator: configuration settings are saved and printed in performance logging

devito/compiler.py, devito/operator.py, devito/yask/wrappers.py
This allows Compiler subclasses to customise the locations of the build directories etc, for cases where `tempfile.gettempdir()` returns something that we don't want to use.
=> compiler: change load/save/make/get_jit_dir/get_codepy_dir into methods

examples/seismic/model.py, examples/seismic/source.py
Tiny fix as currently `src.resample(dt=src.dt)` returns None instead of itself.
=> seismic: source return itself if resampling not required

devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, tests/test_ir.py
eg: `foo(bar(baz()))`
This will be used when nesting `ops_arg` calls within `ops_par_loop`
=> Allowing calls to be nested

devito/ops/types.py, example.py, tests/test_ops.py
See #893.
The problem was that `hashable_content` in `OpsAccess` only used `self.base`, meaning that sympy would cache them incorrectly
=> Fixed OPS code gen bug

devito/ir/iet/utils.py, devito/ir/iet/visitors.py, devito/logger.py, devito/ops/types.py, devito/profiling.py, devito/tools/visitors.py, devito/yask/data.py, devito/yask/transformer.py, devito/yask/types.py, devito/yask/utils.py, tests/test_dimension.py, tests/test_ir.py, tests/test_operator.py, tests/test_ops.py, tests/test_yask.py
This PR is for removing obsolete `:class:` from commentaries.
=> removing :class: from comments

devito/data/__init__.py, devito/data/data.py, devito/data/decomposition.py, devito/data/utils.py, devito/mpi/distributed.py, devito/types/dense.py, tests/test_data.py, tests/test_docstrings.py, tests/test_interpolation.py
In the current master, slicing function data does not work correctly when the step is negative i.e. something along the lines of `u.data[5::-1]` does not return the expected result.
This problem occurs due to how the `start` and `stop` of a `slice` are set in `convert_index` (found in `devito/data/decomposition.py`).
The purpose of this PR will be to fix the bug stated above and to add some tests checking slicing with negative steps is carried out correctly.
Note that the main purpose PR in its current state is to ensure that the update passes all tests. The manner in which the bug is addressed in `convert_index` can still potentially be tidied up.
=> Data slice fix

examples/seismic/viscoelastic/operators.py
In `viscoelastic/operators.py` the ordering of the equations was incorrect, tau and r were flipped. This PR corrects this.
=> viscoelastic.operators: Fix ordering of equations

devito/dse/manipulation.py, tests/test_dse.py
Tiny fix to DAG setup.
Mainly, the `Indexed` have to be added to depency list if the yare lhs of one of the eq of the cluster of equations. Currently was assuming all indexed in rhs are not lhs.
Now 
```
from devito import *
from devito.types import *
from sympy import pprint
grid = Grid((10, 10, 10))
t = TimeFunction(name="t", grid=grid, space_order=4)
r = TimeFunction(name="r", grid=grid, space_order=4)
eq_t = Eq(t.forward, r.forward)
eq_r = Eq(r.forward, 2*r)
op = Operator([eq_t, eq_r])
```
produces
```
#pragma ivdep
#pragma omp simd aligned(r,t:32)
for (int z = z_m; z <= z_M; z += 1)
{
r[t1][x + 4][y + 4][z + 4] = 2*r[t0][x + 4][y + 4][z + 4] + 2;
t[t1][x + 4][y + 4][z + 4] = r[t1][x + 4][y + 4][z + 4] + t[t0][x + 4][y + 4][z + 4];
}
```
that has the correct dependency
=>  topology fix

devito/data/utils.py, tests/test_data.py
This PR fixes a problem for data slicing when `slice.start` is negative.
=>  index_dist_to_repl fix

tests/test_subdomains.py
dle fixes mean that the `'noop'` flags on these tests are no longer needed and should be removed.
=> test_subdomains_dle

benchmarks/user/benchmark.py, devito/builtins.py, examples/seismic/acoustic/acoustic_example.py, examples/seismic/elastic/elastic_example.py, examples/seismic/model.py, examples/seismic/viscoelastic/viscoelastic_example.py
This PR makes the following contributions:
- Enables the use of `mpirun` with non constant `vp` that was causing hanging by changing the way minimum is returned from `builtins.py`
- Changes parameters in `model.py` for a more stable `viscoelastic` model.
- Changes the order of the returned values from elastic and `viscoelastic` in order to
be compatible with `benchmark.py`.
=> examples+MPI: Several fixes related to MPI benchmarking and execution of examples

devito/mpi/distributed.py, tests/test_autotuner.py, tests/test_data.py, tests/test_mpi.py
In master we decompose z -> y -> x
Now we decompose x -> y -> z
that is, the fastest varying dimension is decomposed last.
so if I have a grid `(16, 16, 16)` and 2 MPI ranks, each rank gets
* with master: `(16, 16, 8)`
* with this PR `(8, 16, 16)`
The larger the fastest (innermost) dimension, the better the performance should be
=> MPI: flip domain decomposition

benchmarks/user/benchmark.py, benchmarks/user/make-pbs.py, devito/ir/clusters/cluster.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/stree/algorithms.py, devito/ir/stree/tree.py, devito/ir/support/space.py, devito/operator.py, devito/profiling.py, devito/types/grid.py, devito/yask/operator.py, examples/compiler/01_data_regions.ipynb, tests/test_autotuner.py, tests/test_dse.py
This one can clearly wait until after holidays, but basically it enables MPI-level profiling. Rank-0 derives the global execution time as described [here](https://stackoverflow.com/a/5301414)
Potentially, this can be wired with `benchmark.py`
I'd like reviewers to actually **try** the code and take a look at the profiling output
=> Revamp profiling and support for MPI timing

devito/compiler.py
It seems strange to find this bug so please correct me if I'm missing something. 
CustomCompiler, as it is in master, effectively seems to ignore the `CC` and other environment variables. Even though it reads these values once but they are overwritten by the hardcoded values in the lines I changed below. 
Changed the lines so the values are always read from the environment.
=> CustomCompiler should respect environment variables

devito/operator.py, devito/types/sparse.py, tests/test_mpi.py
Fixes SparseFunction with mpi.
Currently, any SparseFunction out of an operator loses the *mandatory and defining* 
map coords[i] -> data[i]
This fixes so that a give trace `data[:,i]` has its coordinates into `coords[i,:]`. This is mandatory for any operation on SparseFunction such has data residual (rec1- rec2) in FWI/RTM or just saving the result of an operator as the data just by itself doesn't mean anything
=> SparseFunction mpi

devito/compiler.py, devito/types/dense.py, examples/checkpointing/checkpoint.py, tests/test_data.py
This PR:
1. Changes the the c contiguous test in tests/test_data.py to use data_allocated and to check for a space_order > 0 to really test the condition that is likely to fail. 
2. Changes the checkpoint API with pyrevolve to use data_allocated instead of data. 
Note: ~This PR includes #925 so merge that first.~ 
TODO: Remove class attributes like `CC` etc from `CustomCompiler`
=> Change from using data to data_allocated in checkpointing

.travis.yml, azure-pipelines.py, devito/dse/flowgraph.py, devito/finite_differences/differentiable.py, devito/ir/support/basic.py, devito/symbolics/manipulation.py, devito/symbolics/queries.py, tests/test_dse.py, tests/test_ir.py, tests/test_operator.py
Re-engineer code to improve the devito compilation times. 
I've used python's cProfile to find out the hotspots
I've also dropped unused code (which is always a good thing)
for example, `tti -so16` is now **vastly** faster to generate code. Let's see the overall CI times
[profiling_test_dse_v6.pdf](https://github.com/opesci/devito/files/3595120/profiling_test_dse_v6.pdf)
Attached you find the last profile I got from `test_tti_rewrite_aggressive_opcounts(16, 270) `, which I have left within ``__main__`` in ``test_dse.py`` as I hope soon we can get back at this. In particular, now most of the time is spent in API calls (basically to take derivatives, to compute derivatives shortcuts, etc)
=> Accelerate compilation

.travis.yml, azure-pipelines.py
Running the 3d elastic example was time consuming and the example was not being 'tested'. This PR removes running (untested) elastic and viscoelastic examples during build testing and now only the 2d simulations with norm tests are run.
=> Tweak elastic and viscoelastic testing

devito/ops/node_factory.py, devito/ops/operator.py, devito/ops/transformer.py, devito/ops/types.py, devito/ops/utils.py, devito/symbolics/extended_sympy.py, tests/test_ops.py
**Add ops_dat_fetch_data call to the OPS backend**    
- This OPS API call is responsible to get data from the GPU and returning to the pointer allocated from Devito in the main memory.
- For all ops_dat created, it is then created an ops_dat_fetch_dat call, that will bring the result from the GPU.
- Modified Byref class to use ccode instead of plain str.
- Created new tests for this OPS feature and modified tests for ops_dat.
- Modified `ops_args` dictionary to hold more information about the `OpsAccessible` creation.
- Modified dict name_to_ops_dat to only have values that are OpsDat or Array of OpsDat, instead of also having Indexed.
**This is basically #927 + rebasing on top of latest master**
=> Feature - add ops fetch

devito/ops/operator.py, devito/ops/transformer.py, tests/test_ops.py
Since ops iterates a loop until the value is < x_Max and devito iterates
a loop until the value is <= x_Max, we lose a value when going to OPS.
This commit solves this adding one to each dimension max-value, making
OPS iterate the ops_par_loop until the value is < x_Max + 1
=> Adds one to dimension max-value in create_ops_par_loop

devito/dle/parallelizer.py, devito/dle/rewriters.py, devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, devito/mpi/routines.py, tests/test_mpi.py
Improve the `DEVITO_MPI=full` mode such that:
- one OpenMP thread continuously prods the asynchronous progress engine until all comms have finished
- dynamic scheduling is used in place of static if we are prodding
tests updated and enriched accoringly
EDIT: yes, this makes the code go faster according to my measurements
=> Optimize MPI computation/communication overlap

devito/ops/operator.py, tests/test_ops.py
Currently, the backend OPS isn't calling __finalize_ for generated kernels, this will generate code like:
```
void OPS_Kernel_0(...)
{
r2 = 1.0/(*h_y**h_y);
r1 = 1.0/(*h_x**h_x);
r0 = 1.0/(*dt**dt);
}
```
The correct code must be:
```
void OPS_Kernel_0(...)
{
float r2 = 1.0/(*h_y**h_y);
float r1 = 1.0/(*h_x**h_x);
float r0 = 1.0/(*dt**dt);
}
```
=> ops: applying declarations for each generated OPS kernel

devito/builtins.py, devito/data/data.py, devito/data/utils.py, devito/dle/transformer.py, devito/tools/utils.py, devito/types/dense.py, devito/types/dimension.py, devito/types/grid.py, examples/seismic/model.py, tests/test_builtins.py, tests/test_data.py, tests/test_docstrings.py, tests/test_mpi.py
This PR:
1) Includes some bug fixes associated with MPI data slicing along with the relevant tests.
2) A gaussian smoother builtin for Devito functions that mimics the `scipy.ndimage` `gaussian_filter`.
Note: Some changes and tidying are still required.
=> MPI fixes + smoother builtin

devito/finite_differences/differentiable.py, tests/test_dse.py
@mloubout after all, I think monkey-patching sympy.Basic is too horrible, even if it works. So I'm here resurrecting one of your former approaches -- rebuilding as devito core types upon sympy.flatten. There are a few differences w.r.t. what you did:
- technically, this is now based on the single dispatch pattern
- only the immediate children are reconstructed
- the sympy assumptions are propagated too
=> RFC: revisit symbolic processing

devito/ops/operator.py, devito/ops/transformer.py, devito/ops/utils.py, tests/test_ops.py
This PR is for renaming some variable names, and also for avoiding the return of unnamed results when declaring OPS Dats and OPS Args.
=> ops: naming the return of some functions

devito/dse/manipulation.py, devito/dse/rewriters.py, devito/finite_differences/differentiable.py, devito/ops/types.py, devito/symbolics/queries.py, devito/symbolics/search.py, tests/test_differentiable.py, tests/test_dse.py, tests/test_ops.py
Basically forces diffify to replace args at `doit` as currently it is ignored so eben if arguments are turned back to our type if the top class is our it ignores the replacement.
=> Fix sympy type 

devito/dle/parallelizer.py, devito/ir/iet/nodes.py, devito/ir/iet/scheduler.py, devito/ir/iet/visitors.py, tests/test_autotuner.py, tests/test_dle.py, tests/test_dse.py, tests/test_operator.py
Two main things:
- use `schedule(dynamic,1)` for FD loops (delivers better performance than `schedule(static,1)` on all tested xeons)
- use `schedule(dynamic,chunk_size)` for sparse loops, where `chunk_size` is `number_of_iterations / (nthreads * alpha)` where `alpha` is currently set to 3 (found empirically)
Would appreciate some performance testing
=> Better OpenMP

devito/archinfo.py, devito/core/autotuning.py, devito/core/operator.py, devito/dle/__init__.py, devito/dle/blocking_utils.py, devito/dle/parallelizer.py, devito/logger.py, devito/operator.py, devito/types/basic.py, tests/test_autotuner.py, tests/test_dle.py
In master:
* the `nthreads0` variable is used for both "FD loops" and "sparse loops"
* the `nthreads1` variable is used for nested "FD loops" (applies to KNL only ATM)
with this PR:
* the `nthreads0` variable is used for "FD loops"
* the `nthreads1` variable is used for nested "FD loops" (applies to KNL only ATM)
* the `nthreads2` variable is used for "sparse loops"
performance-wise nothing changes unless one supplies different (non-default) values for `nthreads0` and `nthreads2` to `op.apply`
=> nthreads2 for nonaffine loops

devito/builtins.py, examples/seismic/model.py, tests/test_builtins.py
This small PR:
- Allows `nbl` to be zero when calling `initialize_function` hence allowing a `Model` be created with no damping region (as was previously the case).
- If a `Model` is created with no damping region a damping field is now not created.
- A test has been added for when `initialize_function` is called with `nbl=0`.
=> Allow nbl to be zero in initialize_function

devito/finite_differences/differentiable.py
Flip inheritance so that we don't end up with sympy types because of `__neg__`
`__neg__` is unary so cannot be forced via `op_priority` that is only for binary opertations
=> Sympy __neg__ fix

devito/ops/node_factory.py, devito/ops/transformer.py, devito/ops/utils.py, tests/test_ops.py
The `save` parameter is not currently supported by the OPS backend. [issue #908](https://github.com/opesci/devito/issues/908)
_u = TimeFunction(name='u', grid=grid, **save=nt**)_
**Equation:**
`Eq(u.forward, u + 1)`
**Currently code:**
`ops_par_loop(OPS_Kernel_0,"OPS_Kernel_0",block,2,(int *)OPS_Kernel_0_range,ops_arg_dat(u_dat[time], 1, "float", OPS_WRITE));`
```
void OPS_Kernel_0(ACC<float> & utime)
{
utime(0, 0) = 1 + utime(0, 0);
}
```
**New Version:**
`ops_par_loop(OPS_Kernel_0,"OPS_Kernel_0",block,2,(int *)OPS_Kernel_0_range,ops_arg_dat(u_dat[time], 1, "float", OPS_READ),ops_arg_dat(u_dat[time + 1], 1, "float", OPS_WRITE));`
```
void OPS_Kernel_0(const ACC<float> & utime0, ACC<float> & utime1)
{
utime1(0, 0) = 1 + utime0(0, 0);
}
```
=> ops: Enabling save parameter

devito/mpi/distributed.py, devito/operator.py, tests/test_operator.py
This small PR fixes issue #998. Operator objects `comm` and `nb` now have their argument values correctly updated if a grid with a new distributor is 'passed' to the operator.
Note: Still need to add some comments in the code.
=> Update `comm` and `nb` argument values from grid

tests/test_mpi.py, tests/test_operator.py
The `test_new_distributor` test in `tests/test_operator.py` has been split into two tests which have been cleaned up and simplified.
The numerical section of the test has been moved to `test_mpi`.
=> Split test_new_distributor into two tests and simplify them

devito/ops/operator.py, devito/ops/utils.py, tests/test_ops.py
OPS was using a list to store all the kernels that will go into the .h file, but Devito already has one dictionary for this.
=> Replace _ops_kernels by _func_table in OPS    

.codecov.yml, examples/seismic/preset_models.py, tests/test_adjoint.py, tests/test_autotuner.py, tests/test_dse.py, tests/test_tti.py, tests/test_yask.py
Improved `test_dse/tti` tests so that
- Model is created only once (with max space_order) so that only a single call to pad/smooth is done
- Doesn't run operators for tests that don't need it
On top of #1038
=> Test speedup

.travis.yml, Dockerfile.pipelines, azure-pipelines.yml, environment.yml, examples/seismic/acoustic/acoustic_example.py, tests/test_adjoint.py, tests/test_installation.py, tests/test_mpi.py
This one is on me, setup of the Acoustic Class in `test_mpi` was pretty stupid and not doing what I thought i made it do, this should save quite the time in CI (~32 less PDE solve with mpi) and make `test_mpi.py/TestAcoustic` about two times faster (eyeballing it).
It is no super pretty but the "hack" is necessary because basically `purest.mark.parallel` starts a new `pytest` session each time and therefore creates a new class an "regenerate" the norms (and because at that point it's inside MPI it would recompute the norms with MPI). So now I just dump it locally (it's tiny so it's fine) so that the reference norms are computed once *in serial mode* instead of like 30 times.
Travis : Saves 2-4 min per MPI build
Pipeline: Saves ~10-15min per MPI build
=> MPI testing

examples/seismic/model.py
Fix an oversight that meant `subdomains` couldn't be passed to `ModelElastic` and `ModelViscoelastic`.
=> Alow ModelElastic and ModelViscoelastic to also receive subdomains

devito/types/sparse.py, examples/seismic/acoustic/acoustic_example.py, examples/seismic/elastic/elastic_example.py, examples/seismic/tti/tti_example.py, examples/seismic/utils.py, examples/seismic/viscoelastic/viscoelastic_example.py, tests/test_checkpointing.py
This basically makes `_dist_datamap` and `_support` memoized method based on the gridpoints (coordinates).
This reduce the call to `_dist_datamap` to 1 instead of 8 per operator call per sparse function
For example:
```
Allocating memory for rec(1355, 159600)
Allocating memory for rec(1355, 159600)
Allocating memory for rec(1355, 159600)
Allocating memory for rec(1355, 159601)
```
`args_defaults` (currently) takes 36 minutes on this size (4 MPI ranks), in testing with this
update
=> Sparse MPI redundant computation fix

benchmarks/user/benchmark.py
An 'option' within a list of options must now be hashable.
=> Fix for 'click' update

devito/types/dimension.py, tests/test_pickle.py
Without this, pickling operators can sometimes lead to:
```
TypeError: __new__() got an unexpected keyword argument 'step'
```
=> ShiftedDimension pickle fix

devito/data/decomposition.py, devito/mpi/distributed.py, devito/types/dense.py, devito/types/dimension.py, tests/test_data.py
This PR fixes the method `index_glb_to_loc` in `decomposition.py` for when an offset + side are received. Some appropriate tests have been added.
The computation of `_size_outhalo` in `dense.py` has also been fixed.
This fixes #1166.
Note: An MPI test for `_size_outhalo` must be added prior to merge. Submitting as it currently to ensure all tests passing.
=> Fix index_glb_to_loc and _size_outhalo

devito/operator/operator.py, devito/types/basic.py, devito/types/dimension.py, tests/test_dimension.py
fix subsampled dim FD.
A little bug was introduce by xreplace in indexify as `(-2*dt).xreplace({2*dt: 1}) = -2*dt` as xreplace doesn't recognise it with - sign, which breaks FD with subsampling. Wasn't caught in test because it's forward FD (only 2*dt, not -2*dt), so added a test for it too.
=> indexify fix

.github/workflows/pytest-core-mpi.yml
Update CI-mpi workflow to use our self-hosted runners.
=> Self-hosted CI-mpi

tests/test_benchmark.py
Similarly to the changes in conftest.py that happened in #1228 this PR will enable
`test_benchmark.py` to be passing when tested in non conda envs.
=> tests: enable bench testing out of conda envs

devito/compiler.py
by returning GNUCompiler, we eventually add `-fopenmp`  (as long as the gcc version is >= 4.9 as usual) , which ensures 1) our `#pragma omp simd` are interpreted and 2) no annoying warnings "unrecognised pragma omp simd" are emitted to screen
clearly, all of this useful only if one doesn't set DEVITO_ARCH
=> jit: Smarter CustomCompiler

examples/seismic/acoustic/acoustic_example.py, examples/seismic/elastic/elastic_example.py, examples/seismic/tti/tti_example.py, examples/seismic/viscoacoustic/viscoacoustic_example.py, examples/seismic/viscoelastic/viscoelastic_example.py
Adding shape option in examples.
Overwrites previous `-nd` option as a length of the tuple.
In general adds another enhanced option.
=> Add `shape` option in examples

.github/azure/stopVM.ps1
To stop charges stopped VMs also need to be deallocated so adding the deallocate command to the stop script.
=> Deallocate stopped VMs

.github/azure/startVM.ps1, .github/azure/stopVM.ps1, .github/workflows/asv.yml
Seemed like some strange hangs were occasionally happening since adding the deallocate. From testing, these tweaks appear to make the workflow more robust.
=> Tweak asv workflow next

.github/workflows/asv.yml
Add `--strict` to `asv run` so that a non-zero exit code is returned if a benchmark fails.
=> strict asv

devito/types/dimension.py, devito/types/grid.py, tests/test_subdomains.py
Owing the inconsistency in how the thickness of subdimensions is defined (see #1183) a subdomain defined as, e.g.,
```
class sd0(SubDomain):
name = 'sd0'
def define(self, dimensions):
x, y = dimensions
return {x: x, y: ('right', 10)}
```
on a grid with shape `(N, 10)` doesn't currently work. This PR fixes that. Note that it doesn't fix the underlying issue raised in #1183.
=> Fix subdimension thickness

devito/builtins.py
Devito does not currently support `language=openacc` on cpu's. Hence if using the smoother flip to `openmp` for the smooth operations.
=> smooth language fix

benchmarks/user/tools/driver.py
When running the benchmark with MPI, all ranks try to make the result directory to save the json file. This might generate an exception, when a process tries to create an existing directory. This PR fix this issue by adding a parameter to the `os.makedirs` function. With the parameter `exist_ok = True`, the function does not generate an error when the directory already exists.
=> bench: fix results makedir to prevent exception with multiple MPI processes

devito/builtins.py
When using `openacc` + `mpi` we build `mpi4py` differently. Hence I don't think we can switch the smoothing over to `platform = 'cpu64'` when `mpi` is involved (until `openacc` is supported on CPUs). For the time being I think it's better we just carry out the smoothing on GPUs. Or we could check if `DEVITO_MPI /= 0` and not switch in that case only?
=> Smooth on GPUs (for now)

devito/core/gpu_openacc.py, devito/mpi/routines.py, devito/passes/iet/openmp.py, devito/symbolics/extended_sympy.py, devito/symbolics/printer.py, tests/test_pickle.py
=> Fix pickling with MPI full mode

.github/workflows/asv.yml
Tiny patch to ensure the asv runner is shutdown even if, for some reason, the benchmark fails.
=> Ensure av runner always shutdown

devito/symbolics/manipulation.py, tests/test_dse.py
Without this, integer powers that are constructed from floats result in the following error:
```
elif exp > 0:
>               return sympy.Mul(*[base]*exp, evaluate=False)
E               TypeError: can't multiply sequence by non-int of type 'Float'
```
=> fix pow_to_mul to handle float-represented integer powers

devito/mpi/routines.py, devito/operator/profiling.py, devito/symbolics/manipulation.py
I forget why xreplace didn't work here, but it didn't.
This saves more than 40 seconds of python overhead per operator.apply (admittedly on a CPU with fairly ordinary single-thread performance), in MPI mode.
The same code might well be reusable in the performance summary generation, where we've also seen poor performance due to `subs`.
=> optimisation of parameter substitution in MPIRegion.arg_values

devito/mpi/halo_scheme.py, tests/test_mpi.py, tests/test_subdomains.py
Fix for `SubDim`'s thickness not correctly being picked up with `DEVITO_MPI=overlap` or 'greater' when spatial blocking is involved. 
Fix for issue #1309. Suitable 3D test added.
=> MPI overlap+: Fix offset identification

devito/ir/equations/algorithms.py, tests/test_operator.py
This PR adds indexing support for indexing nested (deeply or not) functions that are used for directing a dimension index.
Still WIP. Waiting for discussion and reviews to improve.
=> WIP-RFC: Nested indexification Fix for #1283

devito/finite_differences/derivative.py, devito/types/basic.py, tests/test_derivatives.py
Small fix that makes sure `eval_at` does not overwritte user provided x0 (via `u.dx(x0=....)`)
=> enforce user provided x0

devito/types/dense.py, devito/types/sparse.py
This patch ensures that python holds a reference to objects that it passes to C for the duration of the call.  It was possible for this to not happen since the ctypes pointers are not sufficient to keep objects alive, but memoization of `arg_defaults`/`arg_values` had been covering up this issue.
Previously we didn't run into this since some of the functions that returned these objects
were memoized, which means they hung onto the objects indefinitely.  Removal of the memoization caused them to become eligible for GC, resulting in segfaults and other fun.
=> Avoid dererencing dangling pointers on GC'd objects

.github/workflows/examples.yml, examples/seismic/acoustic/acoustic_example.py, examples/seismic/acoustic/operators.py, examples/seismic/elastic/elastic_example.py, examples/seismic/model.py, examples/seismic/preset_models.py, examples/seismic/skew_self_adjoint/example_iso.py, examples/seismic/tti/tti_example.py, examples/seismic/utils.py, examples/seismic/viscoacoustic/viscoacoustic_example.py, examples/seismic/viscoelastic/viscoelastic_example.py
POC for freesurface with a subdomain. Only implemented for isotropic acoustic as elastic is another story. Can be added to TTI as well.
FYI generated code with sign wrap around `(((i2z - 2) > 0) - ((i2z - 2) < 0))`:
```
#pragma omp simd aligned(damp,u,vp:32)
for (int i1z = i1z_ltkn + z_m; i1z <= -i1z_rtkn + z_M; i1z += 1)
{
float r13 = 1.0/(vp[x + 4][y + 4][i1z + 4]*vp[x + 4][y + 4][i1z + 4]);
u[t1][x + 4][y + 4][i1z + 4] = (r13*(2*u[t0][x + 4][y + 4][i1z + 4] - u[t2][x + 4][y + 4][i1z + 4]) + dt*damp[x + 1][y + 1][i1z + 1]*u[t0][x + 4][y + 4][i1z + 4] + (dt*dt)*(3.70370379e-4F*(-u[t0][x + 2][y + 4][i1z + 4] - u[t0][x + 4][y + 2][i1z + 4] - u[t0][x + 4][y + 4][i1z + 2] - u[t0][x + 4][y + 4][i1z + 6] - u[t0][x + 4][y + 6][i1z + 4] - u[t0][x + 6][y + 4][i1z + 4]) + 5.92592607e-3F*(u[t0][x + …
```
=> Freesurface with subdomain (iso-acoustic)

.github/workflows/examples.yml, devito/types/basic.py, devito/types/caching.py, devito/types/dense.py, devito/types/sparse.py, examples/seismic/plotting.py, examples/seismic/source.py, examples/seismic/tti/operators.py, examples/seismic/tti/tti_example.py, examples/seismic/tti/wavesolver.py, tests/test_caching.py, tests/test_dse.py
Small change to AbstractFunction caching that prevents creating duplicates of function by caching on indices as well.
=> Prevent sympy cache blowup

devito/data/data.py
Start of a PR to address some of the issues raised in #1184.
Currently only a `__reduce__` override has been introduced to raise an error is directly pickling a `Data` object.
In #1184 @tjb900  also states:
> I read this to mean that you cannot rely even on __new__ being called, which means the self._memfree_args reference in __del__ causes an error. This is a simple case of setting _memfree_args to None in __array_finalize__.
But `_memfree_args` is set to None here: https://github.com/devitocodes/devito/blob/c55e7a7fe534124f0a4b4d2b48ccc5a6cc169d07/devito/data/data.py#L95
So I'm probably missing something?
=> `Data` tweaks

.github/workflows/examples.yml, examples/seismic/acoustic/acoustic_example.py, examples/seismic/tti/tti_example.py, examples/seismic/utils.py, examples/seismic/viscoacoustic/viscoacoustic_example.py, examples/seismic/viscoacoustic/wavesolver.py
Viscoacoustic examples is currently failing by default as its kernels are not in the usual ones. Adding explicit tests for them and restoring its working status.
=> tests: Fix args and test viscoacoustic

devito/compiler.py
Compiler version code now checks for empty output of version tests rather than expecting an exception for unsupported arguments. This allows devito to be imported and used inside a process that has ignored SIGCHLD.
If SIGCHLD has been ignored then subprocess.check_output will always see a zero return value and never throw a CalledProcessError exception. This results in StrictVersion being incorrectly initialized and causes 'import devito' to fail.
See also: https://bugs.python.org/issue15756 where subprocess calls were changed to return 0 when SIGCHLD is ignored
=> compiler: version checks avoid unreliable exception

.github/workflows/docker-publish.yml
Fix typos in action for docker.
=> docker: fix typos

.github/workflows/docker-publish.yml, requirements.txt
Last change.
- run created docker images (has to fore pull here for some reason)
WARNING: THis CI will still fail until the next release as the `devito:x-latest` does not exist currently.
=> Run docker test

devito/mpi/distributed.py, devito/types/dense.py, tests/test_mpi.py
- Fixes a bug where `glb_to_rank` in `distributed.py` returned an integer (instead of `tuple`) in 1d. Test updated appropriately.
- Fixes incorrect instances of a halo warning in `dense.py`.
=> MPI minor bug fixes

.github/workflows/docker-publish.yml, devito/core/cpu.py, devito/core/gpu_openmp.py, devito/ir/clusters/cluster.py, devito/passes/clusters/aliases.py, examples/performance/00_overview.ipynb, examples/performance/README.md, tests/test_dse.py, tests/test_gpu_common.py
The new `cire-maxpar` option is to be used to tradeoff storage for parallelism.
Defaults: true on GPU backends, false on CPU backends.
when on, generates:
```
for x
for y
r[x,y] = ...
for x
for y
... = ... r[x, y+1] ...
```
instead of
```
for x
for y
r[y] = ...
for y 
... = ... r[y+1] ...
```
=> Tweak CIRE for GPUs

.github/workflows/docker-publish.yml, requirements.txt
With the release of pytest 6.0.0 a previous warning seems to now be an error. See [here](https://github.com/computationalmodelling/nbval/issues/139) who have also noted this issue. Latest pytest issues [here](https://github.com/pytest-dev/pytest/issues).
=> Restrict pytest to < 6.0

devito/ir/equations/algorithms.py, devito/operations/interpolators.py, devito/types/sparse.py, tests/test_caching.py, tests/test_interpolation.py
Fixes interpolation using the wrong points with MPI (or without MPI and no BCs) due to rounding errors around zero in single precision.
- Added test for it
Fixes #1357 
Should fix #1251
=> Single precision interpolation

devito/types/dimension.py, tests/test_dimension.py
Small change to `SteppingDimension` that was returning multiple `t_sizes` into `arguments` that was unsuded but was preventing multiple functions with different buffer sizes. Added test for fix.
=> Buffer: remove unused  from args to allow multi buffers

devito/ir/clusters/algorithms.py, devito/ir/equations/equation.py, devito/ir/support/basic.py, devito/ir/support/utils.py, tests/test_dimension.py
=> Fix issue #1298

devito/compiler.py
Fix a typo when trying to run devito openmp-target for amdgcn-amd-amdhsa with AOMP:
error: unable to create target: 'No available targets are compatible with triple "amdgcn-amd-amdhs"'
=> fix misspelling of openmp-targets for amdgcn-amd-amdhsa

examples/seismic/acoustic/wavesolver.py, examples/seismic/elastic/operators.py, examples/seismic/elastic/wavesolver.py, examples/seismic/self_adjoint/wavesolver.py, examples/seismic/tti/tti_example.py, examples/seismic/tti/wavesolver.py, examples/seismic/viscoacoustic/wavesolver.py, examples/seismic/viscoelastic/wavesolver.py
Fixes the `opt` argument-passing to TTI and elastic.
=> examples: Fix `opt` arg-passing for elastic and TTI

examples/README.md, examples/seismic/tutorials/12_time_blocking.ipynb
Per discussion on slack. I also updated examples/README.md
=> Move time block notebook to seismic/tutorials

docker/Dockerfile.nvidia, requirements-nvidia.txt
=> Moved from PGI to HPC SDK.  New NVIDIA Based-Container.

devito/ir/support/basic.py, devito/passes/iet/openmp.py, tests/test_dle.py, tests/test_gpu_openmp.py
* Two bug fixes concerning the generation of `reduction` clauses and `pragma omp atomic` (now avoided if unnecessary)
* Ships tests
* Supersedes #1433
=> Fix parallel increments

devito/data/data.py, devito/operator/operator.py, tests/test_data.py, tests/test_subdomains.py
Fixes a bug that meant that equations assocciated with a `SubDomainSet` had to be ordered in 'groups'. Fixes issue #1453. Thanks to @mloubout.
=> Fix SubDomainSet bug

devito/types/grid.py
Added and origin_map analogous to spacing_map. The idea is to have a shortcut to obtain the float values of the tuple rather than having to do [i.data for i in grid.origin]
=> Added origin_map attribute to Grid

devito/ir/equations/equation.py
Fix for the issue where derivatives in ConditionalDimension conditions would cause a python-level error.
=> Conditonals: Added diff2sympy to conditionals

devito/ir/iet/visitors.py, devito/tools/utils.py, devito/types/basic.py, tests/test_visitors.py
ASV spotted a regression in compilation time, see spike [here](https://www.devitoproject.org/devito-performance/#codegen.TTI.time_forward) on https://github.com/devitocodes/devito/commit/891bfc4c 
This patch fixes it.
It also speeds-up `filter_ordered` (now `key` only computed once) and adds a simple tree visitor test
=> Patch compilation time

devito/passes/equations/linearity.py, devito/types/basic.py, devito/types/equation.py, devito/types/tensor.py, tests/test_exprs_lowering.py, tests/test_tensors.py
Add robustness grid detection in the constructor. Should prevent errors when a `TensorFunction` is created with components that are not devito types.
TODO:
- Cleanup and force return sympy Matrix at first construction as well
fixes #1476
=> Tensor grid fixup

devito/types/dense.py, tests/test_mpi.py
Tiny PR adding a quick method to `Function`'s for returning `size_global`.
But see #1498 re. the naming.
=> Function globabl size method

devito/types/dense.py
=> Outhalo size warning

devito/passes/iet/mpi.py, tests/test_mpi.py
=> Fixup _drop_halospots

devito/passes/iet/mpi.py, tests/test_mpi.py
=> Fixup _hoist_halospots

.github/workflows/examples.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-gpu.yml, .github/workflows/tutorials.yml
Updating various workflows owing to the [deprecation](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) of `set-env`.
=> Remove use of set-env from workflows

tests/test_tools.py
`tests/test_tools.py::test_sorting` was failing on my local machine. It is not clear to me that the test makes sense unless you are choosing between two different implementations for performance reasons. I suggest @mloubout takes a look at this lines of code (git blame) - my suggested fix is to convert this to a warning and changed to higher precision timer.
=> make test tools less random

.github/workflows/pytest-core-mpi.yml
Move back github hosted runners for the time being.
Note that workflow is being kept in the current format since we should be moving this back to our own cluster in the new year.
=> Migrate MPI CI

.github/workflows/docker-publish.yml, .github/workflows/pytest-gpu.yml
This, for the time being, supersedes #1537. GPU tests will now be run on demand via workflow dispatch and the runners started and stopped during the workflow.
=> CI: Update gpu workflow

.github/workflows/examples-mpi.yml
MPI examples also need moving over.
=> Move mpi examples to new runner

.github/workflows/asv.yml, benchmarks/regression/asv.conf.json
As the title says.
Note that the setting of environment variables looks a bit weird, but is the new [recommended](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) way.
=> Migrate asv workflow to new runner

examples/seismic/viscoacoustic/viscoacoustic_example.py
Owing to what looks like a [compiler bug](https://github.com/devitocodes/devito/runs/1726964978), the viscoacoustic tests will be skipped for the time being if openacc offloading to gpu.
See issue #1560.
=> Skip viscoacoustic tests with openacc

benchmarks/user/benchmark.py, devito/operator/operator.py, devito/operator/profiling.py, examples/userapi/05_conditional_dimension.ipynb
Each self._section in an IET will now hold FD-Gpts instead of GPts.
This metric will be propagated to profiling.
=> operator: Use FD-Gpts/s instead of Gpts/s

benchmarks/user/benchmark.py, devito/__init__.py, devito/arch/__init__.py, devito/arch/archinfo.py, devito/arch/compiler.py, devito/compiler.py, devito/core/__init__.py, devito/core/autotuning.py, devito/operator/operator.py, devito/operator/registry.py, tests/conftest.py, tests/test_gpu_common.py
This PR moves `archinfo.py` and `compiler.py` from `devito/devito` to `devito/devito/arch`
=> Introduce devito/arch

devito/core/gpu_openmp.py, devito/ir/iet/efunc.py, devito/ir/iet/nodes.py, devito/ir/iet/utils.py, devito/ir/iet/visitors.py, devito/ir/support/utils.py, devito/operator/operator.py, devito/operator/symbols.py, devito/passes/iet/definitions.py, devito/passes/iet/orchestration.py, devito/tools/utils.py, devito/types/array.py, devito/types/basic.py, devito/types/dense.py, devito/types/dimension.py, devito/types/misc.py, devito/types/sync.py, tests/test_gpu_common.py, tests/test_gpu_openacc.py, tests/test_iet.py, tests/test_pickle.py
* Only tested (no surprise) with clang and aomp
* the adjoint operators do not work yet because of clang/aomp bugs, which have already been flagged
* Data streaming is now performed in pure C, not C++ (now using pthreads instead of std::threads -- this was necessary because of compatibility issues with clang/aomp)
* Further improvements to the compiler passes implementing data streaming
=> Data streaming support with OpenMP offloading

.github/workflows/pytest-core-nompi.yml
This PR contains a small adjustment to the `pytest-core-nompi` workflow to 'parallelize' tests with names containing the string `'adjoint'` and those without.
Subject to no queues forming, this should speed up core CI by roughly 12 minutes.
=> Separate adjoint based tests

devito/types/basic.py, tests/test_caching.py
Fixes #1575 
Switch from `__init_finalize` to `__new__` to make sure the extra `u.function` is  cought by the cache and added extra line to `clear_cache` test to test it (breaks on master)
=> BoundSymbol constructor to be cached

examples/seismic/viscoacoustic/operators.py, examples/seismic/viscoacoustic/wavesolver.py, tests/test_adjoint.py
Hi guys,
Once the issue (#1513)  was discussed here and also in [slack ](https://devitocodes.slack.com/archives/C1HSXP6KB/p1605747162212800?thread_ts=1603204771.133200&cid=C1HSXP6KB), we were able to develop a set of first-order adjoint viscoacoustic equations.
Thus, we finalized the implementation of the forward and adjoint viscoacoustic equations to first and second-order formulation.
The next step will be the implementation of the viscoacoustic Born operators!
=> examples: add first order adjoint viscoacoustic equations

examples/seismic/tti/operators.py, examples/seismic/tti/tti_example.py, examples/seismic/tti/wavesolver.py, tests/test_adjoint.py, tests/test_gradient.py
At this point @FabioLuporini might be asking: where is @ofmla? xD  well, I've been extra-busy with some other projects and preparing classes, but here is a small contribution. This PR adds new operators to the anisotropic solver. In the absence of Mathias @jkwashbourne could take a look.
=> examples: Born approximation for TTI media

devito/finite_differences/coefficients.py, devito/finite_differences/tools.py, tests/test_symbolic_coefficients.py
Fix for the bug where derivatives with symbolic coefficients on staggered grids default to incorrect values. Fixes one of the two issues detailed in #1589.
=> dsl: Patch symbolic coefficients with staggered grids

.github/workflows/pytest-gpu.yml
Move CI-gpu from Azure and over to our new self-hosted runners.
Work in progress.
=> ci: Transfer gpu workflow to self-hosted runners

benchmarks/regression/benchmarks/arguments.py, devito/operator/operator.py, devito/types/dense.py, devito/types/dimension.py, devito/types/grid.py, devito/types/sparse.py
bonus: Adding one more performance regression test to our ASV
the second (and future) `op.arguments(...)` call in the test, on this branch, takes about 45ms on my workstation. 
Ah, the `_arg_defaults` 's memorization in `sparse.py` turns out to be unsafe for MatrixSparseFunction
=> types: Drop unsafe/unnecessary memoization in the arguments processing engine

tests/conftest.py
Small conftest fix so that `skipif-language` is only skipping if on gpu.
=> ci: Re-enable adjoint tests

requirements.txt
to <8 since new version breaks on osx
=> deps: fix py-cpuinfo

docker/Dockerfile.nvidia
Update Dockerfile.nvidia to HPC SDK 21.3
=> gpu: Update Dockerfile.nvidia to HPC SDK 21.3

devito/types/dense.py, tests/test_mpi.py
This duplicates the logic used for `Function.__shape_setup__` into `TimeFunction` as well - essentially sanity-checking the provided shape matches the grid and dimensions, if both are provided.
This allows for `TimeFunction`s over smaller numbers of dimensions to still work correctly with MPI.
=> compiler: Check consistency between shape and grid for TimeFunction, too

devito/passes/iet/parpragma.py, tests/test_dle.py
compiler: Tweak nested-par candidate condition.
Can help preserve parallelism in cases where bounds are expressions.
=> compiler: Tweak nested-par candidate condition

.github/workflows/asv.yml
To discover new benchmarks it seems we need to add `asv run --bench just-discover` to the workflow. This worked locally so hopefully will do the trick now.
=> Allow asv workflow to discover new benchmarks

devito/operations/interpolators.py, tests/test_interpolation.py
Although the interpolation using PrecomputedInterpolator was working fine, the injection tries to access the `gridpoints` and `interpolation_coeffs` in `self` instead of in `self.obj`.
Also, when injecting with the PrecomputedInterpolator, the preparation of the arguments for the operator calls the `self._parent._arg_defaults` for the gridpoints SubFunction, which does not exist. By changing the parent of the SubFunction to `self.obj` this is solved.
=> API: fixed callback of PrecomputedInterpolator injection

.gitignore
=> misc: git ignore *.npy files

environment-dev.yml
Fixing according to new pip reqs format
According to: https://stackoverflow.com/questions/68571543/using-a-pip-requirements-file-in-a-conda-yml-file-throws-attributeerror-fileno
=> reqs: pip new file arg format

devito/core/cpu.py, devito/core/gpu.py, devito/ir/clusters/algorithms.py, devito/ir/support/space.py, devito/passes/clusters/aliases.py, devito/passes/clusters/misc.py, devito/tools/abc.py, tests/test_dse.py, tests/test_fission.py
Add loop fission, a compiler pass that is currently used to trade-off data locality for more collapsable loops on GPUs.
Example:
```
#pragma acc collapse(1)
for x
for y0
...
for y1
...
```
after loop fission (I emphasize that **currently** this only gets applied if running on GPUs) we get:
```
#pragma acc collapse(2)
for x
for y0
...
#pragma acc collapse(2)
for x
for y1
...
```
fixes #1725
=> compiler: Loop fission

devito/passes/clusters/blocking.py, tests/test_skewing.py
Another PR to help towards time-tiling. When in blocking, skewed bounds are lifted to outer loops. Will help to easier handle skewing factors as the factor is used at the outer levels of blocking.
```
41       for (int x0_blk0 = time + x_m; x0_blk0 <= time + x_M; x0_blk0 += x0_blk0_size)
42       {
43         for (int y0_blk0 = time + y_m; y0_blk0 <= time + y_M; y0_blk0 += y0_blk0_size)
44         {
45           for (int x = x0_blk0; x <= MIN(x0_blk0 + x0_blk0_size - 1, time + x_M); x += 1)
46           {
47             for (int y = y0_blk0; y <= MIN(y0_blk0 + y0_blk0_size - 1, time + y_M); y += 1)
48             {
49               for (int z = z_m; z <= z_M; z += 1)
50               {
51                 u[t0][x - time + 1][y - time + 1][z + 1] = v[t0][x - time + 1][y - time + 1][z + 1] + …
```
=> compiler: lift skewing in higher block levels

tests/test_gradient.py
I just realized there were not linearization tests for tti case. This PR only adds a couple of tti cases to `gradientJ ` test
=> tests: add tti_setup to gradientJ test

.github/workflows/pytest-core-nompi.yml, .github/workflows/tutorials.yml
Ubuntu 16.04 is no longer available via github hosted runners hence upgrade various ubuntu versions.
=> ci: Update Ubuntu versions

docker/Dockerfile.nvidia, docker/Singularity.nvidia.def, requirements-nvidia.txt, requirements.txt
same as #1743 , but without the `fsspec` package in `requirements.txt`
also rebased on latest master
=> install: Udpate to HPCSDK 21.7, Update to Jupyter>=3.0

devito/builtins/initializers.py, devito/builtins/utils.py, devito/data/data.py, devito/data/decomposition.py, devito/data/utils.py, tests/test_data.py
Fixes a bug where slices of `Function`'s of the form `f.data[0:0]` were returning all data instead of an empty array of shape `(0, n, ...)`.
Fixes #1756.
=> compiler: Fix zero to zero slices

devito/mpi/distributed.py
From the MPI specs (for example [at this link](https://mpi.deino.net/mpi_functions/MPI_Cart_rank.html)):
> MPI_ERR_ARG
>    Invalid argument. Some argument is invalid and is not identified by a specific error class (e.g., MPI_ERR_RANK). 
In master, we're catching the MPI_ERR_ARG as if that were an indication that the MPI rank is at the boundary. This is the case for many many MPI distributions and configurations, but (unsurprisingly) not for all. I have a server with several GPUs and the NVidia MPI configured as per our `Dockerfile.nvidia` where `Get_cart_rank` does **not** trigger `MPI_ERR_RANK` for MPI ranks at the boundary -- rather, it provides the MPI rank of the process at the opposite side of the virtual topology.
With this patch, we explicitly use `MPI.PROC_NULL`, when necessary, …
=> mpi: Patch neighborhood construction

devito/ir/equations/algorithms.py, devito/types/basic.py, examples/seismic/tutorials/14_creating_synthetics.ipynb, tests/test_operator.py
Fxes bug that comes with the test (fails to compile on master since the functuion `u1` only appear as an index and is never lowered and indexified)
=> compiler: Nested indexification

.github/workflows/examples.yml, .github/workflows/pytest-core-nompi.yml, devito/arch/compiler.py
Tested python 3.10 via docker seems ok, just spinning a python 3.10 CI
=> ci: add python 3.10, gcc-10 option

devito/arch/archinfo.py
` cuda.cuInit(0) ` needs to be called before cuda.cuDeviceComputeCapability and not inside.
Tests were passing accidentally before. Now it should be fine before the offloading dockerfile comes in.
=> compiler: gpu cc detection fix

.github/workflows/examples.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-gpu.yml
Fixes #1812 
According to their repo, `v1` will be retired Feb 1st so switching to v2.
https://github.com/codecov/codecov-action
=> CI: update codecov action version

benchmarks/user/benchmark.py, examples/misc/linalg.py, requirements.txt
Fixes issue with mulit-params with latest click and benchmark.
Superseeds #1831 and #1692
=> benchmarks: custom click type for grid params

devito/passes/iet/linearization.py, devito/tools/utils.py, tests/test_linearize.py
=> compiler: Use int64_t, not unsigned int, for linearization

requirements.txt, tests/conftest.py, tests/test_gradient.py
Supersedes #1833 
`pytest` now has a `setup` function that was badly conflicting with an import, this should fix compat.
=> CI: prevent  conflict with pytest

devito/arch/compiler.py
Hello guys,
I was here packaging devito for my distribution and got into a bug saying
```
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```
for the line I changed with this simple commit. As a consequence I simply fixed the issue. I've made some tests and this shouldnt and mustn't break anything on anyone's computer.
This may sound simple and non important, but Devito is written in Python, which is a distro agnostic language. It is expected that the code will run on any linux or mac, and if it doesn't I think it should be treated as a bug (at least in my humble opinion).
I have every intention to make Devito work on [NixOS package manager (Nix)](https://nixos.org/) since it is completely reproducible and distro agnostic, which will relieve me from the …
=> arch: Fix CustomCompiler instantiation

devito/types/dense.py, tests/conftest.py, tests/test_mpi.py
This change is both a tiny optimisation and also a fix for a potential correctness issue in the case where the application provides a customised padding, since the provided padding is not required to be the same on all ranks.
There are three commits here which hopefully make sense. 
* add a timeout to MPI tests
* add a test which fails with the two ranks having different padding (it hangs without the first commit)
* a fix
The timeout one can be a separate PR if you like, or we can drop it altogether. It's needed for the tests to behave as expected (i.e. fail) with the second commit, but after the third commit they pass again (and obviously don't hang) so I don't mind either way. 
I'm also not sure if 30s is an appropriate timeout, or if we should make it e.g. an environment variable to be …
=> mpi: Do not send padding region when doing pythonland halo exchange

devito/finite_differences/derivative.py, devito/finite_differences/finite_difference.py
This is in preparation for the "derivative evaluation overhaul" (DEO from now on!) that we've talked about recently.
-- A glimpse of the future --
I will need to introduce an `evaluate_partial` to `Derivative` (I cannot touch `evaluate` because we don't want API-level surprises). Such `evaluate_partial` (better name needed) will expand the `Derivative` to an intermediate high-level object, for example
```
Derivative(f, x).dx.evaluate_partial
->
DotDerivative(f, coeff)
```
Representing the dot product between `f` and an array of coefficients, that is, a "rolled" Derivative. This will be the object used by Devito throughout compilation and in particular throughout (and until) Cluster specialization.
So, back to this PR... moving that `.evaluate` will allow me to share the first two steps of …
=> compiler: Move derivative.evaluate

devito/finite_differences/differentiable.py, tests/test_lower_exprs.py
diff2sympy patch in case the expresssion is already a non-evaluable sympy expression
=> compiler: Do not evaluate unevaluable expressions

devito/data/utils.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/analysis.py, devito/ir/support/space.py, devito/passes/clusters/blocking.py, devito/passes/clusters/buffering.py, examples/seismic/tti/tti_example.py, tests/test_interpolation.py, tests/test_operator.py
- minor refresh in `def decompose`
- do not `AnalyzeSkewing` if not needed
- Ensure `sub_iterator` keys exist in mappers rather than always defaulting to `None` (see: https://github.com/devitocodes/devito/pull/1845/files#r822563785)
=> compiler: Minor blocking.py refactorings

examples/seismic/tutorials/14_creating_synthetics.ipynb
Updated pyvista to use new attribute names and notebook backend in the synthetics notebook. Should hopefully fix the notebook CI failures.
=> examples: Update attribute names and backend for synthetics notebook

devito/passes/iet/mpi.py
=> mpi: Always generate MPIComm with MPI enabled

devito/core/cpu.py, devito/core/gpu.py, devito/ir/equations/algorithms.py, devito/ir/support/space.py, devito/operator/operator.py, devito/passes/clusters/__init__.py, devito/passes/clusters/implicit.py, devito/passes/clusters/misc.py, devito/passes/clusters/subdomains.py, devito/tools/threading.py, devito/types/caching.py, devito/types/grid.py, tests/test_subdomains.py
At last...
The reason I had to rework this now is that I have a compiler pass in Pro where, during clustering (!), I create a further equation that requires the MultiSubDomain thickness assignments, which wouldn't be generated due to premature lowering without this PR
=> compiler: Revamp generation of implicit equations

devito/checkpointing/checkpoint.py, devito/types/dense.py
When using Checkpoint and `save != None` (eg. `save != time_order + 1`) the value returned for size of a TimeFunction will be larger than necessary. 
Closes #1907
=> compiler: Fix checkpoint size when save != None

devito/passes/clusters/buffering.py, tests/test_buffering.py
=> compiler: Patch buffer initialization

devito/types/basic.py, devito/types/caching.py, examples/compiler/04_iet-B.ipynb, examples/performance/01_gpu.ipynb, tests/test_caching.py
Scalar data carriers are unique, so why attempt to cache them?
=> compiler: Uncache data carriers

devito/arch/compiler.py, devito/core/gpu.py, devito/finite_differences/elementary.py, devito/passes/iet/languages/openmp.py, versioneer.py
Had this locally (maybe from 3 months ago?)
did a minor change...PRing for a test...
If anyone wants to continue on this..feel free..
It helps to avoid all the warnings created by this:
https://peps.python.org/pep-0632/#:~:text=In%20Python%203.10%20and%203.11,platforms%20will%20not%20be%20added.
=> deps: Drop deprecated distutils imports

benchmarks/user/advisor/run_advisor.py, devito/core/autotuning.py, examples/misc/linalg.py, tests/test_dle.py
- Avoid autotuning when children's block shapes are the same as the parent's block shapes
- Slightly refresh advisor
=> compiler: Add blockrelax tests and refresh advisor profiling

devito/operations/interpolators.py, devito/types/sparse.py, tests/test_dimension.py
~TODO: add a reasonable assert to the added test~
=> compiler: Support interpolation with user-provided implicit dims

devito/finite_differences/derivative.py, tests/test_derivatives.py
Fixes @EdCaunt issue with substitutions.
=> api: Fix Derivative substitution

docker/Dockerfile.cpu
Adds mpicc compiler to the image.
Before it was runtime only:
```bash
root@90fab5c37e20:/# /opt/intel/oneapi/mpi/latest/bin/
IMB-MPI1            IMB-P2P             hydra_nameserver    mpiexec.hydra       tune/
IMB-MPI1-GPU        IMB-RMA             hydra_pmi_proxy     mpirun              tune_fast/
IMB-MT              cpuinfo             impi_info           mpitune             
IMB-NBC             hydra_bstrap_proxy  mpiexec             mpitune_fast
```
Now:
```bash
root@dfcf4ccd986f:/# /opt/intel/oneapi/mpi/latest/bin/
IMB-MPI1            cpuinfo             mpicxx              mpigcc              mpitune
IMB-MPI1-GPU        hydra_bstrap_proxy  mpiexec             mpigxx              mpitune_fast
IMB-MT              hydra_nameserver    mpiexec.hydra       mpiicc              tune/ …
```
=> install: Update to intel-oneapi-mpi-devel

devito/finite_differences/differentiable.py, setup.cfg, tests/test_derivatives.py, tests/test_dse.py
=> compiler: Patch premature lowering of EvalDerivative

devito/mpi/routines.py
`Diag2HaloExchangeBuilder` does not use or require the `MPIRegion` that the base class `Overlap2HaloExchangeBuilder` wants to create.
=> compiler: Fix MPI mode diag2 does not need a MPIRegion

devito/finite_differences/derivative.py, tests/test_derivatives.py
Fix for manually specifying the derivative order of cross-derivatives via the call API. Makes `f.dxdy(fd_order={x: 2, y: 2})` behave as expected rather than raising `TypeError`.
=> dsl: Patched cross-derivative fd_order bug

devito/data/data.py, devito/data/decomposition.py, devito/data/utils.py, tests/conftest.py, tests/test_data.py
Fix for issues #1862 and  #1892 + associated tests.
=> mpi: Fix data distribution bugs [part 2]

devito/core/cpu.py, devito/core/gpu.py, devito/core/operator.py, devito/passes/clusters/cse.py, tests/test_dse.py
Make sure that exsiting temps stay as "first statement". Nested index as function get extracted as temp and end up mixed up with the case extracted temps without this patch.
=> compiler: Prevent reordering of existing temps in CSE

devito/tools/data_structures.py
When looking for unique values in `ReducerMap.unique`, the order of candidates alters the result:
- If the candidates are `[1, frozenset({1, 2, 3})]` the method will run as expected.
- If the candidates are `[frozenset({1, 2, 3}), 1]` the method will fail to find a unique value among the candidates
This is fixed by adding another branch to the local function `compare_to_first` checking if `first` is a `Set`.
=> compiler: Ensure order invariance of candidates in ReducerMap.unique

.github/workflows/pytest-core-nompi.yml, devito/symbolics/printer.py, requirements.txt
Small PR than fixes the newly introduced bug in sympy for `_print_Add`. We should keep that bug fix in our printer even once 1.12 is released so that we stay compatible with sympy 1.11
=> dependencies: sympy 1.11 compatibility

.github/workflows/pytest-core-nompi.yml, .github/workflows/tutorials.yml, README.md, devito/ir/support/basic.py, devito/passes/iet/mpi.py
Works around an issue in PRO in which diag2 fallbacks to basic due to too conservative data dependence analysis
the tests are in PRO... I can't think of an easy way of testing this here. Not ideal, but this fixes an issue @jkwashbourne is facing
=> compiler: Relax _mark_overlappable

devito/ir/clusters/visitors.py, devito/passes/clusters/misc.py
This affects only PRO.
While CI runs, I'll think about whether there's a way of testing this in OSS as well (in PRO it's tested, it's trivial)
=> compiler: Prevent topofusion of homogeneous sync Clusters

devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, tests/test_iet.py
This is mostly for people that don't use devito interactively in python
This basic machinery is exploited in PRO
=> compiler: Support template parameters

docker/Dockerfile.nvidia
see Slack (@ggorman comments) but basically MPI-level CPU illegal instruction exceptions without this option, because nvc compiles with -native silently (unlike gcc)
=> install: Make mpi4py portable across intel and amd

devito/passes/iet/languages/openacc.py, devito/passes/iet/parpragma.py, tests/test_dle.py, tests/test_gpu_openacc.py
A proposal to allow the use of multiple tile sizes in the same operator, through the _part-tile_ flag.
Passing multiple tuples to the _part-tile_ flag is already supported, but only the first tuple is applied in the __make_partree_ method of _DeviceAcczier_ class.
The changes consist of supplying the nesting index in the _make_parallel_ method of _PragmaShmTransformer_ to the __make_partree_ method and using the tile size with the respective index.
Cases with different tile and nesting sizes are handled. Given `n` tile sizes for an operator with `m` nests:
If `n = m`: The i-th tile size is assigned to the i-th nesting.
If `n > m`: The first `m` tile sizes are assigned to the `m` nests (i-th tile size -> i-th nesting), and the remaining `n-m` is not used.
If `n < m`: The `n` tile sizes are …
=> compiler: Change tile use in DeviceAcczier to allow multiple tile sizes

examples/cfd/tools.py
Temporary fix to avoid breaking since this update...
```
TypeError                                 Traceback (most recent call last)
Cell In[15], line 15
12 init_smooth(field=u.data[0], dx=grid.spacing[0], dy=grid.spacing[1])
13 init_smooth(field=u.data[1], dx=grid.spacing[0], dy=grid.spacing[1])
---> 15 plot_field(u.data[0])
File ~/Desktop/Work/devito/examples/cfd/tools.py:38, in plot_field(field, xmin, xmax, ymin, ymax, zmin, zmax, view, linewidth)
36 y_coord = np.linspace(ymin, ymax, field.shape[1])
37 fig = pyplot.figure(figsize=(11, 7), dpi=100)
---> 38 ax = fig.gca(projection='3d')
39 X, Y = np.meshgrid(x_coord, y_coord, indexing='ij')
40 ax.plot_surface(X, Y, field[:], cmap=cm.viridis, rstride=1, cstride=1,
41                 linewidth=linewidth, antialiased=False)
TypeError: …
```
=> reqs: Fix for matplotlib >=3.6.3

devito/core/cpu.py, devito/core/gpu.py, devito/core/operator.py, devito/ir/clusters/cluster.py, devito/ir/iet/nodes.py, devito/ir/stree/algorithms.py, devito/ir/support/properties.py, devito/ir/support/utils.py, devito/mpi/halo_scheme.py, devito/operator/profiling.py, devito/passes/clusters/asynchrony.py, devito/passes/clusters/buffering.py, devito/passes/iet/asynchrony.py, devito/passes/iet/definitions.py, devito/passes/iet/engine.py, devito/passes/iet/linearization.py, devito/passes/iet/mpi.py, devito/passes/iet/parpragma.py, devito/symbolics/extended_sympy.py, devito/symbolics/manipulation.py, tests/test_gpu_common.py, tests/test_iet.py, tests/test_linearize.py, tests/test_mpi.py, tests/test_symbolics.py
Context: essentially all of this is necessary for new features and bug fixes in PRO
I'd like to start getting reviews ASAP because we gonna need to merge this rapidly
=> compiler: Misc compiler tweaks and improvements

devito/ir/clusters/algorithms.py, devito/ir/support/basic.py, devito/operator/operator.py, devito/passes/clusters/derivatives.py, devito/passes/clusters/misc.py, devito/passes/iet/linearization.py, devito/passes/iet/misc.py, devito/tools/abc.py, devito/types/dimension.py, devito/types/misc.py, tests/conftest.py, tests/test_dse.py, tests/test_symbolics.py, tests/test_unexpansion.py
More use cases covered, better generated code (e.g. more fusion).
PR equipped with tests
=> compiler: Improve lowering of IndexDerivatives

devito/operator/operator.py
When changing platform, language, or compiler using keyword arguments to the operator, these are not recorded to be used by downstream operators, which instead default to the global configuration.
This makes the information available by storing it in the `ArgumentsMap`.
=> compiler: Pass operator arguments to downstream operators

devito/ir/iet/algorithms.py, devito/ir/stree/algorithms.py, devito/mpi/routines.py, tests/test_gpu_common.py
This reverts commit 4a184e0fcfc04553897e4bc39a8299d4b56c0f49.
Explanation: this was done only to change the profiling scope of the WaitLock regions . However, it turns out it breaks code generation in CUDA/HIP + streaming. Hence, reverting for now, until I will have the time to find a better solution
=> compiler: Revert "compiler: Relax WaitLock regions in a ScheduleTree"

devito/ir/iet/efunc.py, devito/mpi/routines.py, devito/operator/profiling.py, devito/passes/iet/instrument.py, tests/test_mpi.py
This PR aims to make compute0 "more special" for instrumenting
and then adds a timer for the compute0 core area in FULL mpi mode  (for advanced2 profiling)
e.g now we get:
```
Global performance: [OI=6.55, 15.50 GFlops/s, 0.19 GPts/s]
Local performance:
* section0[rank0]<21,50,50,8,8,40> ran in 0.72 s [OI=6.55, 15.56 GFlops/s, 0.19 GPts/s]
+ haloupdate0 ran in 0.00 s [0.01%]
+ halowait0 ran in 0.00 s [0.01%]
+ remainder0 ran in 0.55 s [76.68%]
+ compute0 ran in 0.17 s [23.32%]
```
Generated code-diff:
```bash
*** 42,48 ****
double haloupdate0;
double halowait0;
double remainder0;
-   double compute0;
} ;
struct region0
--- 42,47 ----
***************
*** 81,89 ****
START_TIMER(haloupdate0)
haloupdate0(u_vec,comm,msg0,6,t0,nthreads);
STOP_TIMER(haloupdate0,timers)
- …
```
=> mpi: Instrument compute0 core after specialising as ComputeCall

devito/operator/operator.py
PR adds `opkwargs` property to `ArgumentsMap`. `opkwargs` returns a dictionary containing compiler, language and platform keyword arguments usable by downstream operators.
=> compiler: Add opkwargs property to ArgumentsMap

devito/passes/clusters/buffering.py, tests/test_buffering.py, tests/test_gpu_common.py
Using the time derivative of a streamed buffer with a ConditionalDimension results in OOB within `init_to_host`. This was not captured in existing tests.
A new test has been added `test_gpu_common.py::test_streaming_multi_input_conddim_foward` that fails with this OOB; and a new guard is now introduced in `Buffering` to prevent it.
=> compiler: Add guards to prevent OOB when streaming buffers with ConditionalDimension

.github/workflows/docker-bases.yml, .github/workflows/docker-devito.yml, .github/workflows/examples.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-gpu.yml, .github/workflows/tutorials.yml, conftest.py, devito/arch/compiler.py, devito/core/autotuning.py, devito/types/dense.py, devito/types/dimension.py, docker/Dockerfile.amd, docker/Dockerfile.cpu, docker/Dockerfile.devito, docker/Dockerfile.nvidia, docker/README.md, examples/cfd/08_shallow_water_equation.ipynb, examples/seismic/source.py, requirements-optional.txt, requirements-testing.txt, requirements.txt
- Revamp base deployment not to rebuild nvhpc. Reduces the number of jobs and should reduce CI time since all extras are mostly an env var on top of the existing image. Little bit more verbose but I don't think it's really an issue there
- Added icx as a separate image
- Fix MPI flags for oneapi
=> docker: revamp base deployment

devito/passes/clusters/aliases.py, tests/test_dse.py
=> compiler: fix non arithmetic distances

devito/arch/compiler.py, tests/test_mpi.py
Passes locally
After icx 2023.2.0, reductions should are passing
=> compiler: Keep -qopenmp by default after icx 2023.2

docker/Dockerfile.nvidia, examples/seismic/elastic/elastic_example.py, examples/seismic/viscoelastic/viscoelastic_example.py, pytest.ini, setup.cfg, tests/test_mpi.py
Fixes pytest config issue, `setup.cfg` is ignored if `pytest.ini` exsists so our options were being ignored
=> CI: pytest setup fix

devito/passes/equations/linearity.py, tests/test_symbolic_coefficients.py
=> api: prevent factorization for symbolic coefficients

devito/__init__.py, devito/arch/compiler.py, devito/logger.py, devito/operator/operator.py, devito/parameters.py, devito/types/parallel.py
Adds `deviceid` to `configuration` and updates `switchconfig` so that it can act both as a decorator and a context manager.
=> misc: Add deviceid to configuration and enhance switchconfig

.github/workflows/examples-mpi.yml, devito/parameters.py, devito/passes/equations/linearity.py, tests/test_symbolic_coefficients.py
=> dsl: prevent aggregation for symbolic coefficients 

devito/arch/compiler.py
This should be a very minor change: Switch between -march=native (x86) and -mcpu=native -mtune=native (PowerPC)
fixes #2146 
I am not sure if you are testing on PPC (I guess not since the error never showed up) so not sure what to do for an appropriate test.
=> arch: Correct `march` to `mcpu` for ppc

devito/arch/archinfo.py, devito/arch/compiler.py
Use configuration['platform'].isa == 'avx512' to determine whether AVX512 is supported rather than DEVITO_PLATFORM. This adds compiler options for long vectors for Intel Skylake and later generations.
=> compiler: Enable AVX512 compiler support when available.

devito/passes/clusters/factorization.py, devito/symbolics/printer.py, devito/symbolics/queries.py, devito/types/dense.py, devito/types/sparse.py, examples/seismic/inversion/inversion_utils.py, tests/test_dse.py, tests/test_interpolation.py, tests/test_pickle.py, tests/test_sparse.py
Fixes #2192 
- Fixes `subs/rebuild` of SparseFunction to properly propagate through the subfunctions (coords, ...)
- Add tests
=> api: Cleanup and improve SubFunction

devito/ir/clusters/algorithms.py, tests/test_dse.py
Fix sparse loop to avoid weird access (see slack for issue with GPU)
=> compiler: prevent radius dependent temps for sparse operations

devito/ir/support/syncs.py, devito/passes/clusters/asynchrony.py, devito/passes/clusters/buffering.py, devito/passes/clusters/misc.py, devito/passes/clusters/utils.py, devito/types/dimension.py, tests/test_dle.py
See comments next to code for more info
=> compiler: Rework multi-level buffering

docker/Dockerfile.cpu, requirements-mpi.txt
=> ci: add intel missing gpu drivers

devito/passes/clusters/implicit.py
Can't easily make a test for it here. Breaks `abox` with extra dims
=> compiler: prevent multisubdimension expressions duplicates

devito/symbolics/inspection.py, tests/test_unexpansion.py
hitting another piece of legacy code, sigh
=> compiler: Patch compare_ops for IndexDerivatives

devito/arch/compiler.py, devito/core/operator.py, devito/passes/clusters/blocking.py, devito/passes/iet/languages/openacc.py, devito/passes/iet/parpragma.py, devito/tools/data_structures.py, docker/Dockerfile.nvidia, tests/test_tools.py, tests/test_unexpansion.py
=> misc: fix UnboundTuple for None partile

devito/arch/compiler.py, devito/mpi/distributed.py, devito/types/dense.py, tests/test_mpi.py
Add newer compilers to outdated CustomCompiler
=> compiler: add extra platforms and language to the custom compiler

devito/symbolics/extended_sympy.py, devito/types/dense.py, devito/types/dimension.py, devito/types/grid.py, tests/test_dimension.py
Fix issue with overwrties with different factor
=> api: Always make subsampling factor symbolic

.github/workflows/pytest-core-nompi.yml, devito/arch/archinfo.py, devito/arch/compiler.py, devito/mpi/distributed.py, tests/test_gpu_common.py
currently removes the `Xcompile` flag needed for host side as a duplicate flag
Fixes #2260
=> arch: support rocm for gpu info

.github/workflows/tutorials.yml, devito/finite_differences/differentiable.py, devito/finite_differences/operators.py, devito/types/tensor.py, tests/test_derivatives.py, tests/test_tensors.py
Add options so can do things like `div(u, order=so, shift=.5)` for left/right laplacian
=> api: Add shift and fd order option to all FD operators:

devito/passes/clusters/aliases.py, devito/passes/iet/misc.py, devito/tools/abc.py, devito/types/grid.py, examples/performance/00_overview.ipynb, tests/test_dimension.py, tests/test_dle.py, tests/test_dse.py, tests/test_fission.py, tests/test_operator.py, tests/test_subdomains.py
Making the PR to run it through CI and get some opinions. Still needs tests and probably the option to pass a keyword argument to `Operator` along the lines of `shorten_subdims=False` (lmk if anyone has a snappier name).
=> compiler: Add pass to abridge SubDimension names where possible

devito/ir/support/utils.py, devito/passes/iet/misc.py, devito/types/basic.py, devito/types/equation.py
=> api: Minor fixes to arithmetic operations with scalar and tensors

devito/passes/iet/misc.py
Slight improvement to the coverage of `abridge_dim_names` as a couple of things were getting missed.
=> compiler: Check DeviceFunctions for SubDimensions

devito/__init__.py, devito/data/allocators.py, devito/data/data.py, examples/compiler/01_data_regions.ipynb, tests/test_autotuner.py, tests/test_data.py
This was a legacy thing. Pointless.
In fact, potentially harmful for data transfer performance since aligned based addresses will result in higher performance with most device backends
=> misc: Switch off develop-mode

devito/passes/clusters/derivatives.py, tests/test_unexpansion.py
Tiny enhancement to avoid useless stupid temporary variables in the generated code
=> compiler: Improve IndexDerivative lowering

devito/arch/archinfo.py, devito/arch/compiler.py, devito/builtins/utils.py, devito/types/dimension.py, examples/seismic/preset_models.py, examples/seismic/tti/operators.py, tests/test_dse.py
Minor cleanup for easier call from other places
=> example: small cleanup of tti for easier reuse

devito/ir/clusters/cluster.py, devito/ir/support/utils.py, devito/passes/clusters/derivatives.py, tests/test_unexpansion.py
tiny PR that shifts the stencil loops by as much as needed so that we can index e.g. `w[i0] (i0=0)`instead of `w[i0 + 2] (i0 = -2)`
=> compiler: Generate less integer arithmetic

devito/core/cpu.py, devito/core/gpu.py, devito/core/operator.py, devito/passes/clusters/blocking.py
Test is in PRO
I also took the chance to create opt-options to allow specifying different par-tiles for reduction loops
=> compiler: Block reductions irrespective of par-tile

.github/workflows/asv.yml, .github/workflows/docker-bases.yml, .github/workflows/docker-devito.yml, .github/workflows/examples-mpi.yml, .github/workflows/examples.yml, .github/workflows/flake8.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-gpu.yml, .github/workflows/pythonpublish.yml, .github/workflows/triggers.yml, .github/workflows/tutorials.yml
To address this warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> ci: Update actions for nodejs version deprecation

examples/cfd/07_cavity_flow.ipynb
There is a sign mistake in the Poisson equation. It doesn't significantly affect the solution of this particular example, but it can be important when solving Navier Stokes for other problems.
=> Correct the Poisson equation in the cavity flow example

devito/mpi/halo_scheme.py
Overlap mode did not have deterministic code generation.
```c
static void remainder0(struct dataobj *restrict u_vec, const float a, const float dt, float r0, float r1, float r2, int t0, int t1, const int x_M, const int x_m, const int y_M, const int y_m, const int nthreads)
{
compute0(a,u_vec,dt,r0,r1,r2,t0,t1,x_M - 2,x_m + 2,MIN(y_M, y_m + 1),y_m,nthreads);
compute0(a,u_vec,dt,r0,r1,r2,t0,t1,x_M - 2,x_m + 2,y_M,MAX(y_m, y_M - 1),nthreads);
compute0(a,u_vec,dt,r0,r1,r2,t0,t1,MIN(x_M, x_m + 1),x_m,y_M - 2,y_m + 2,nthreads);
compute0(a,u_vec,dt,r0,r1,r2,t0,t1,MIN(x_M, x_m + 1),x_m,MIN(y_M, y_m + 1),y_m,nthreads);
compute0(a,u_vec,dt,r0,r1,r2,t0,t1,MIN(x_M, x_m + 1),x_m,y_M,MAX(y_m, y_M - 1),nthreads);
compute0(a,u_vec,dt,r0,r1,r2,t0,t1,x_M,MAX(x_m, x_M - 1),y_M - 2,y_m + 2,nthreads); …
```
=> mpi: Generate deterministic code for overlap mode

devito/core/cpu.py, devito/core/gpu.py, devito/core/operator.py, devito/finite_differences/differentiable.py, devito/finite_differences/finite_difference.py, devito/ir/equations/algorithms.py, devito/operator/operator.py, devito/passes/clusters/derivatives.py, devito/passes/iet/mpi.py, tests/test_derivatives.py, tests/test_operator.py, tests/test_unexpansion.py
This paves the way for external customisation, e.g.
* `w[i]*u[x + i]` vs `w[i]*(u[x + i] - u[x - i])`
* loops vs unroll
* etc
=> compiler: Revamp lowering of IndexDerivatives

devito/finite_differences/differentiable.py, devito/finite_differences/tools.py, tests/test_symbolic_coefficients.py
So can sort fd coeffs types such as with drp
=> api: add priority to fd coefficients for mixed derivatives

devito/ir/support/guards.py
=> compiler: Patch Guards.simplify_and

devito/arch/compiler.py
Use get_nvidia_cc to get Nvidia gpu architecture rather than using '-arch=native'.
This fixes compilation errors on the Nvidia Jetson.
=> Use get_nvidia_cc to get Nvidia gpu architecture

.github/workflows/pytest-core-mpi.yml, conftest.py, devito/operations/interpolators.py, devito/types/sparse.py, docker/entrypoint.sh, examples/seismic/acoustic/acoustic_example.py, examples/seismic/acoustic/operators.py, examples/seismic/source.py, examples/seismic/utils.py, tests/test_autotuner.py, tests/test_builtins.py, tests/test_dse.py, tests/test_interpolation.py, tests/test_mpi.py, tests/test_operator.py, tests/test_pickle.py
Add support for kaiser-windowed sinc interpolation
Fixes #595
=> api: Add Hicks (sinc) interpolation api

docker/Dockerfile.devito, docker/Dockerfile.intel
tested locally `cpu-icx` and pushed by hand to docker hub
=> docker: fix oneapi setup

FAQ.md, devito/logger.py, devito/operator/operator.py, devito/operator/profiling.py
This logging mode helps to reduce the output of MPI runs to only emit performance numbers once per MPI rank.
It is mostly aimed to reduce the redundant verbose performance output.
e.g. instead of:
```
Allocating host memory for u(2, 52, 72, 72) [2 MB]
Allocating host memory for u(2, 52, 72, 72) [2 MB]
Operator `Kernel` generated in 1.72 s
* lowering.IET: 0.71 s (41.5 %)
* specializing.IET: 0.66 s (38.6 %)
* make_mpi: 0.45 s (26.3 %)
* lowering.Expressions: 0.56 s (32.8 %)
* lowering.Clusters: 0.41 s (24.0 %)
Flops reduction after symbolic optimization: [209 --> 90]
Operator `Kernel` generated in 1.81 s
* lowering.IET: 0.72 s (40.0 %)
* specializing.IET: 0.66 s (36.6 %)
* make_mpi: 0.45 s (25.0 %)
* lowering.Expressions: 0.58 s (32.2 %)
* lowering.Clusters: 0.48 s (26.7 %)
Flops reduction …
```
=> misc: Add MPI0 logging level

.github/workflows/docker-bases.yml, .github/workflows/docker-devito.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-gpu.yml, .github/workflows/tutorials.yml, docker/Dockerfile.nvidia
`macos-latest` runner dropped support for 3.9
=> CI: fix macos runner python 

devito/finite_differences/derivative.py, tests/test_derivatives.py
Derivatives specified as `Derivative(f, (x, 2), (y, 0))` (zeroth-order wrt one dimension) are a valid request, but the resultant derivatives were not equal to those specified as `Derivative(f, (x, 2))` and certain routines such as substitution would fail. This PR patches this and adds a test.
=> dsl: Patch edge-case derivative specifications

conftest.py, tests/test_linearize.py
Should fix @georgebisbas issue with too verbose logging for him
SHould now allow -s for embed
=> ci: tweak mpi setup to allow -s and hide output

conftest.py, devito/__init__.py, devito/arch/archinfo.py, devito/builtins/arithmetic.py, devito/builtins/utils.py, devito/data/allocators.py, devito/data/data.py, devito/mpi/distributed.py, devito/mpi/routines.py, devito/operator/operator.py, devito/types/basic.py, devito/types/dense.py, devito/types/grid.py, devito/types/sparse.py
Mostly to support new features in PRO
=> compiler: Misc compiler improvements

conftest.py
fix `decoupler` to use `sys.python` (like for parallel) to avoid picking up wrong pytest
=> CI: fix decoupler config to use correct python

devito/__init__.py, devito/core/gpu.py, devito/ir/clusters/algorithms.py, devito/ir/clusters/cluster.py, devito/ir/iet/nodes.py, devito/ir/iet/utils.py, devito/ir/iet/visitors.py, devito/ir/support/basic.py, devito/operator/operator.py, devito/passes/__init__.py, devito/passes/clusters/blocking.py, devito/passes/clusters/misc.py, devito/passes/iet/engine.py, devito/passes/iet/languages/openacc.py, devito/passes/iet/languages/openmp.py, devito/passes/iet/languages/utils.py, devito/passes/iet/linearization.py, devito/passes/iet/parpragma.py, devito/symbolics/manipulation.py, devito/types/array.py, devito/types/basic.py, devito/types/dimension.py, tests/test_dimension.py, tests/test_dle.py, tests/test_dse.py, tests/test_gpu_openacc.py, tests/test_gpu_openmp.py, tests/test_linearize.py, tests/test_mpi.py
These are mostly to improve code generation and performance of elastic-like PDEs.
=> compiler: Yet another batch of compilation tweaks

devito/passes/clusters/implicit.py, tests/test_subdomains.py
Separated from #2405, since I think I need to go back to the drawing board on that one, but this patch fixes a bug currently in master.
=> compiler: Patch bug in SubDomainSet lowering

devito/ir/support/utils.py, devito/passes/clusters/cse.py, devito/types/equation.py, tests/test_dse.py
Fix cse to make sure expression from different conditionals get properly handled.
avoids things like
```
if (a){
f1 = expr
}
if (b){
f1 = expr
}
```
to be converted to
```
if (a){
r0 = expr
f1 = r0
}
if (b){
f1 = r0
}
```
CSE now counts expression based on the equation's conditional. We could also just lift all `rxx` out of conditionals but that would be computing those cse temps way more than needed which I don't think it great
=> compiler: fix cse with different conditionals

devito/ir/equations/equation.py, devito/types/dimension.py, devito/types/relational.py, tests/test_dimension.py
=> api: Support combination of condition and factor for ConditionalDimension

devito/types/dimension.py, tests/test_dse.py
=> compiler: Bump default block size

devito/__init__.py, devito/arch/archinfo.py, devito/arch/compiler.py, tests/test_arch.py
Generalizes gcc
suport graviton 2-3-4 and add cflags to use gcc with it as well
=> arch: Support more platforms

devito/__init__.py
Allow import of `CondEq` and `CondNe` from `devito` rather than requiring `devito.symbolics`. In due course, these should probably move to `devito.types.relational` and use the `AbstractRel` mixin.
=> dsl: Make CondEq and CondNe easier to import

FAQ.md, devito/__init__.py, devito/core/operator.py, devito/mpi/distributed.py, devito/parameters.py, devito/passes/clusters/blocking.py, devito/types/grid.py, tests/test_mpi.py
Admittedly two orthogonal things
=> compiler: Tweak par-tile unrolling and revamp MPI topology

devito/finite_differences/derivative.py, devito/passes/equations/linearity.py, devito/tools/abc.py, tests/test_derivatives.py
Fixes
https://devitocodes.slack.com/archives/C1HSXP6KB/p1721850267638059
=> api: Make Derivative Reconstructable

devito/finite_differences/derivative.py, devito/finite_differences/differentiable.py, devito/operations/interpolators.py, devito/tools/data_structures.py, devito/types/utils.py, tests/test_pickle.py, tests/test_staggered_utils.py
Fixes `EnrichedTuple` (and its hierarchy) rebuilding to an empty instance.
=> misc: Fix EnrichedTuple rebuilding

devito/tools/abc.py, devito/types/basic.py, tests/test_caching.py, tests/test_pickle.py, tests/test_symbolics.py
SymPy assumptions currently disappear when objects inheriting from `sympy.Symbol` are rebuilt. This PR adds a patch and tests.
#2431 needs rebasing on this patch.
=> dsl: Fix missing sympy assumptions during rebuilding

devito/finite_differences/derivative.py, devito/finite_differences/differentiable.py, devito/finite_differences/finite_difference.py, devito/finite_differences/tools.py, tests/test_derivatives.py, tests/test_differentiable.py, tests/test_dse.py, tests/test_mpi.py
Fix an FD hack to use proper interpolation.
=> api: make sure staggered FD interpolates shifts

devito/__init__.py, devito/finite_differences/differentiable.py, devito/types/basic.py, examples/seismic/acoustic/acoustic_example.py, examples/seismic/elastic/elastic_example.py, examples/seismic/model.py, examples/seismic/self_adjoint/test_utils.py, examples/seismic/self_adjoint/test_wavesolver_iso.py, examples/seismic/test_seismic_utils.py, examples/seismic/tti/tti_example.py, examples/seismic/viscoacoustic/viscoacoustic_example.py, examples/seismic/viscoelastic/viscoelastic_example.py, examples/userapi/03_subdomains.ipynb, tests/test_differentiable.py
Needed for accurate elastic simulations
On top of #2455
=> API: Support harmonic averaging for parameter Function

devito/arch/compiler.py
recent NVC has deprecated gpu=pinned and suggested to rather use what this patch uses
=> arch: Avoid deprecated compiler flags

.github/workflows/examples-mpi.yml, .github/workflows/examples.yml, devito/finite_differences/derivative.py, environment-dev.yml, tests/test_derivatives.py
Prevent __call___ to add wrong input at rebuild by only processing actual inputs
=> api: fix derivative kwargs at call

.github/workflows/pytest-core-nompi.yml, devito/finite_differences/tools.py, devito/symbolics/printer.py, tests/test_tensors.py
Was preventing this
https://github.com/devitocodes/devito/blob/779522508a45d677f233811846fcc7eb36cea916/examples/seismic/tti/operators.py#L158
to simplify leading to `u.dx2 + u.dy2 - u.dy2` expressions....
=> api: enforce sympy shifts

devito/types/basic.py, devito/types/constant.py, devito/types/dimension.py
Adds a default no-op `_arg_values`, `_arg_check` etc to any subclasses of `AbstractSymbol`.
=> dsl: Add ArgProvider inheritance to AbstractSymbol

docker/Dockerfile.nvidia
Useful to install third-party utilities (in my case, it was CUTLASS)
=> misc: Always search the CUDA SDK's math_libs include dir

devito/finite_differences/derivative.py, devito/finite_differences/differentiable.py, devito/finite_differences/operators.py, devito/types/tensor.py, tests/test_symbolic_coefficients.py, tests/test_tensors.py
=> api: support custom coeffs for div/grad/curl

devito/passes/iet/definitions.py
=> compiler: Avoid allocating Bundles on the host if transient

devito/ir/iet/visitors.py, tests/test_visitors.py
Add `MapNodes(..., mode='groupby')` back, which was dropped in #2477 and I didn't see this. It is useful for the PETSc lowering.
=> compiler: Add 'groupby' mode to MapNodes visitor

devito/arch/archinfo.py, devito/builtins/utils.py, devito/core/operator.py, devito/exceptions.py, devito/ir/clusters/algorithms.py, devito/ir/iet/visitors.py, devito/operator/operator.py, devito/passes/clusters/aliases.py, devito/passes/clusters/buffering.py, devito/passes/iet/definitions.py, devito/passes/iet/errors.py, devito/passes/iet/orchestration.py, devito/types/basic.py, devito/types/dense.py, tests/test_buffering.py
This was long due
Also improves handling of C-level errors
=> misc: Revamp exception hierarchy

tests/test_dimension.py
This case is valid but not currently tested. It is useful for creating switches that can be set in Python-land. Example applications include preventing accesses on empty ranks when performing sparse operations on functions defined on subdomains.
=> tests: Add test for using a Constant as a condition in a ConditionalDimension

devito/finite_differences/differentiable.py, devito/operator/operator.py, devito/passes/iet/misc.py, devito/symbolics/inspection.py, devito/symbolics/printer.py, devito/types/basic.py, examples/seismic/model.py, tests/test_differentiable.py, tests/test_symbolics.py
=> api: Misc fixes for builtins and harmonic averaging

devito/finite_differences/derivative.py, devito/finite_differences/tools.py, devito/types/equation.py, tests/test_symbolic_coefficients.py
Fix backward compat that was applying weights to all derivative missing the `coeff.function` check
=> api: fix backward compatibility of Substitution, missing function check

devito/finite_differences/finite_difference.py, devito/types/equation.py, examples/seismic/tutorials/07_DRP_schemes.ipynb, tests/test_symbolic_coefficients.py, tests/test_unexpansion.py
this is only an issue for the legacy custom coefficients API
=> api: Fix custom coefficients inlining

devito/arch/archinfo.py, devito/arch/compiler.py, devito/finite_differences/differentiable.py, devito/ir/clusters/cluster.py, devito/ir/support/properties.py, devito/ir/support/syncs.py, devito/passes/clusters/misc.py, devito/passes/iet/engine.py, devito/types/array.py, devito/types/basic.py, devito/types/dense.py, tests/test_mpi.py, tests/test_rebuild.py, tests/test_symbolics.py
In essence, this is a batch of tweaks to support GPU features in PRO
=> compiler: Misc improvements to code generation

.github/workflows/docker-devito.yml, .github/workflows/pytest-core-mpi.yml, .github/workflows/pytest-core-nompi.yml, .github/workflows/pytest-gpu.yml, .github/workflows/tutorials.yml, devito/arch/archinfo.py, docker/Dockerfile.amd, docker/Dockerfile.cpu
update rocm and various docker setup
=> docker: update compilers to more recent versions

devito/ir/support/basic.py, devito/types/array.py
Not much to see here honestly, just a couple of minor additions that I need in PRO
=> compiler: Enhance IR for GPU codegen

tests/test_symbolics.py
I'm guessing we are going to find more
=> tests: Remove floating point equality assertions

devito/finite_differences/derivative.py, devito/finite_differences/operators.py, devito/finite_differences/rsfd.py, devito/types/basic.py, devito/types/dense.py, devito/types/tensor.py, devito/types/utils.py, tests/test_staggered_utils.py, tests/test_tensors.py
Fix two issues
- Functions's rebuilt with new dimensions are broken when the function is staggerred
- Tensor rebuild isn't defined properly.
=> api: Fix staggering setup and tensor rebuilding

devito/types/basic.py, tests/test_symbolics.py
Fix backward compatibilty for sympy 1.12, where `is_imaginary` is sometimes called during arithmetic operations
=> api: Add retrocompat to is_imaginary for older sympy

requirements-nvidia.txt, requirements-optional.txt, requirements-testing.txt, requirements.txt
Add an upper bound to all dependencies to avoid nasty surprises, forcing every dependency change to go through CI with the dependabot.
=> deps: Add upper bound to all deps to avoid surprises

devito/mpi/routines.py
=> mpi: Fix halo exchanges from BundleViews

devito/builtins/initializers.py, devito/types/basic.py, devito/types/dense.py, devito/types/tensor.py, docker/Dockerfile.devito, tests/test_tensors.py
Fix handling of tensor kwargs when they are provided as per-compoenent
=> api: fix kwargs processing for tensor functions

devito/arch/archinfo.py, tests/test_gpu_common.py
Needed if one switches backend dynamically, e.g. via `switchconfig(platform='cpu64')`
=> arch: Use the node's max memory transaction size

devito/arch/archinfo.py
Makes cache line size detection error when there is no GPU (json.loads line 302 errors with empty lines)
=> arch: fix json erro with no card

devito/ir/iet/nodes.py, devito/ir/iet/visitors.py, devito/ir/support/basic.py, devito/mpi/halo_scheme.py, devito/passes/iet/mpi.py, tests/test_dle.py, tests/test_mpi.py
besides making things generally more efficient, by generating code that sometimes avoids redundant halo exchanges, we are here achieving:
fixes #2622
=> compiler: Revamp MPI hoisting and merging

devito/passes/clusters/cse.py, requirements.txt, tests/test_cse.py
`.pop` is `popright` by default, it reverses eq order right now breaking a lot of things.
=> compiler: fix deque pop order

requirements.txt
Missed by Dependabot for some reason
=> deps: Bump upper NumPy version to 2.3.1

devito/ir/iet/visitors.py, devito/symbolics/search.py
This PR implements lazy visitors in the IET layer which operate via generators instead of flattening lists of children's results at every node. Replaces `FindSymbols`, `FindNodes`, `FindWithin` and `FindApplications` with such versions, as well as introducing type hints for the affected visitors.
From my testing this results in a speedup in IET lowering of up to 50%.
Also reimplements `Search` similarly, benchmarks forthcoming.
=> compiler: Lazy IET visitors + Search

devito/passes/iet/asynchrony.py, devito/passes/iet/langbase.py
Without this, MPI+GPU runs might end up allocating extra memory (e.g. pinned memory buffers inside the runtime library) on rank0's GPU because each thread is expected to call set_device() explicitly (yes, even children threads)
=> compiler: Call set_device in pthreads

devito/finite_differences/derivative.py, devito/finite_differences/differentiable.py, devito/mpatches/__init__.py, devito/mpatches/as_independent.py, devito/mpatches/asindependent.py, tests/test_derivatives.py, tests/test_pickle.py
I want to be able to manipulate Devito derivative objects, more like sympy derivative objects.
(possibly only optionally)
=> dsl: Expand derivative

MANIFEST.in, devito/builtins/arithmetic.py, pyproject.toml
Removes unnecessary files from sdist and wheel builds.
This prevents directories such as `docker` appearing in `site-packages` when a non-editable install is performed
=> install: Remove files and directories not needed for install
